/* -----------------------------------------------------------------------------
  Filename:    can_par.c
  Description: Toolversion: 08.31.00.01.01.01.23.01.00.00
                
                Serial Number: CBD1010123
                Customer Info: Nxtr
                               Package: GM GMLAN_30_Indx 
                               Micro: TI TMS570 TMS570X5LS20216
                               Compiler: Code Composer Studio 4.6.4
                
                
                Generator Fwk   : GENy 
                Generator Module: DrvCan__base
                
                Configuration   : C:\_synergy\9BXX_CZ8L9T\GM_9BXX_EPS_TMS570\Tools\AsrProject\GENy\RT_2.0_Mod.gny
                
                ECU: 
                        TargetSystem: Hw_Tms470/570Cpu (Dcan)
                        Compiler:     TexasInstruments
                        Derivates:    TMS570PSFC66
                
                Channel "Channel0":
                        Databasefile: C:\_synergy\9BXX_CZ8L9T\GM_9BXX_EPS_TMS570\Tools\AsrProject\GENy\GlobalA_HS.dbc
                        Bussystem:    CAN
                        Manufacturer: General Motors
                        Node:         EPS_HS
                Channel "Channel1":
                        Databasefile: C:\Synergy\GM_C1XX_EPS_TMS570-zz4r1x1\GM_C1XX_EPS_TMS570\Tools\AsrProject\GENy\GlobalA_CE.dbc
                        Bussystem:    CAN
                        Manufacturer: General Motors
                        Node:         EPS_CE

  Generated by , 2016-07-05  13:47:31
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2008 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#define C_DRV_INTERNAL
#include "can_inc.h"
#include "can_par.h"
#include "v_inc.h"

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tCanTxId0 V_MEMROM2 CanTxId0[kCanNumberOfTxObjects] = 
{
  MK_STDID0(0x778u) /* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */, 
  MK_STDID0(0x706u) /* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */, 
  MK_STDID0(0x642u) /* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */, 
  MK_STDID0(0x542u) /* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */, 
  MK_STDID0(0x1E5u) /* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */, 
  MK_STDID0(0x184u) /* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */, 
  MK_STDID0(0x148u) /* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */, 
  MK_STDID0(0x642u) /* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  MK_STDID0(0x542u) /* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  MK_STDID0(0x335u) /* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */, 
  MK_STDID0(0x1E5u) /* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */, 
  MK_STDID0(0x1CAu) /* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxDLC[kCanNumberOfTxObjects] = 
{
  MK_TX_DLC(7) /* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */, 
  MK_TX_DLC(8) /* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */, 
  MK_TX_DLC(8) /* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */, 
  MK_TX_DLC(1) /* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  MK_TX_DLC(4) /* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */, 
  MK_TX_DLC(8) /* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */, 
  MK_TX_DLC(8) /* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
};
/* ROM CATEGORY 1 END */


#ifdef C_ENABLE_COPY_TX_DATA
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 TxDataPtr V_MEMROM2 CanTxDataPtr[kCanNumberOfTxObjects] = 
{
  (TxDataPtr) DTC_Triggered_778._c /* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */, 
  (TxDataPtr) Xcp_Slave_Msg._c /* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */, 
  (TxDataPtr) USDT_Resp_From_EHPS_EPS_HS._c /* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */, 
  (TxDataPtr) UUDT_Resp_From_EHPS_EPS_HS._c /* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */, 
  (TxDataPtr) PPEI_Steering_Wheel_Angle._c /* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */, 
  (TxDataPtr) LKA_Steering_Trq_Overlay_Stat_HS._c /* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */, 
  (TxDataPtr) Power_Steering_Information_HS._c /* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */, 
  (TxDataPtr) USDT_Resp_From_EPS_EPS_JR_CE._c /* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  (TxDataPtr) UUDT_Resp_From_EPS_EPS_JR_CE._c /* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  (TxDataPtr) Electric_Power_Steering_CE._c /* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */, 
  (TxDataPtr) PPEI_Steering_Wheel_Angle_CE._c /* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */, 
  (TxDataPtr) Steering_Torque_Overlay_Stat_CE._c /* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_PRETRANSMIT_FCT
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplPreTransmitFct V_MEMROM2 CanTxApplPreTransmitPtr[kCanNumberOfTxObjects] = 
{
  V_NULL /* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */, 
  V_NULL /* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */, 
  V_NULL /* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */, 
  V_NULL /* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */, 
  V_NULL /* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */, 
  V_NULL /* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */, 
  V_NULL /* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */, 
  V_NULL /* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  V_NULL /* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  V_NULL /* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */, 
  V_NULL /* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */, 
  V_NULL /* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_CONFIRMATION_FCT
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplConfirmationFct V_MEMROM2 CanTxApplConfirmationPtr[kCanNumberOfTxObjects] = 
{
  V_NULL /* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */, 
  XcpConfirmation /* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */, 
  TpDrvConfirmation /* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */, 
  DescUudtConfirmation /* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */, 
  Appl_1E5MsgTxAck_HS /* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */, 
  V_NULL /* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */, 
  V_NULL /* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */, 
  TpDrvConfirmation /* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  GgdaUudtConfirmation /* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  V_NULL /* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */, 
  Appl_1E5MsgTxAck_CE /* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */, 
  V_NULL /* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_PART_OFFLINE
/* ROM CATEGORY 2 START */

V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxSendMask[kCanNumberOfTxObjects] = 
{
  (vuint8) C_SEND_GRP_NONE /* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */, 
  (vuint8) C_SEND_GRP_NONE /* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */, 
  (vuint8) C_SEND_GRP_NONE /* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */, 
  (vuint8) C_SEND_GRP_NONE /* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */, 
  (vuint8) C_SEND_GRP_NONE /* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */, 
  (vuint8) C_SEND_GRP_LKA /* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */, 
  (vuint8) C_SEND_GRP_NONE /* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */, 
  (vuint8) C_SEND_GRP_NONE /* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  (vuint8) C_SEND_GRP_NONE /* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  (vuint8) C_SEND_GRP_APA /* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */, 
  (vuint8) C_SEND_GRP_NONE /* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */, 
  (vuint8) C_SEND_GRP_NONE /* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
};

/* ROM CATEGORY 2 END */

#endif


#ifdef C_ENABLE_CONFIRMATION_FLAG
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanConfirmationOffset[kCanNumberOfTxObjects] = 
{
  0 /* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */, 
  0 /* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */, 
  0 /* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */, 
  0 /* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */, 
  0 /* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */, 
  0 /* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */, 
  0 /* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */, 
  0 /* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  0 /* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  0 /* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */, 
  0 /* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */, 
  0 /* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanConfirmationMask[kCanNumberOfTxObjects] = 
{
  0x01u /* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */, 
  0x00u /* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */, 
  0x00u /* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */, 
  0x00u /* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */, 
  0x02u /* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */, 
  0x04u /* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */, 
  0x08u /* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */, 
  0x00u /* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  0x00u /* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  0x10u /* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */, 
  0x20u /* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */, 
  0x40u /* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
};
/* ROM CATEGORY 1 END */


#endif




/* Id table depending on search algorithm */
/* Linear search */
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tCanRxId0 V_MEMROM2 CanRxId0[kCanNumberOfRxObjects] = 
{
  MK_STDID0(0x7CBu) /* ID: 0x000007cb, Handle: 0, T1_HostToTarget [FC] */, 
  MK_STDID0(0x708u) /* ID: 0x00000708, Handle: 22, Xcp_Master_Msg [FC] */, 
  MK_STDID0(0x500u) /* ID: 0x00000500, Handle: 1, Wheel_Pulses_HS [FC] */, 
  MK_STDID0(0x4C1u) /* ID: 0x000004c1, Handle: 2, PPEI_Engine_General_Status_4 [FC] */, 
  MK_STDID0(0x3F1u) /* ID: 0x000003f1, Handle: 3, PPEI_Platform_Eng_Cntrl_Requests [FC] */, 
  MK_STDID0(0x3E9u) /* ID: 0x000003e9, Handle: 4, PPEI_Vehicle_Speed_and_Distance [FC] */, 
  MK_STDID0(0x34Au) /* ID: 0x0000034a, Handle: 5, NonDriven_Wheel_Grnd_Velocity_HS [FC] */, 
  MK_STDID0(0x348u) /* ID: 0x00000348, Handle: 6, Driven_Wheel_Grnd_Velocity_HS [FC] */, 
  MK_STDID0(0x242u) /* ID: 0x00000242, Handle: 23, USDT_Req_to_EHPS_EPS_HS [FC] */, 
  MK_STDID0(0x232u) /* ID: 0x00000232, Handle: 7, Driving_Mode_Control_HS [FC] */, 
  MK_STDID0(0x214u) /* ID: 0x00000214, Handle: 8, Brake_Pedal_Driver_Status_HS [FC] */, 
  MK_STDID0(0x1F5u) /* ID: 0x000001f5, Handle: 9, PPEI_Trans_General_Status_2 [FC] */, 
  MK_STDID0(0x1F1u) /* ID: 0x000001f1, Handle: 10, PPEI_Platform_General_Status [FC] */, 
  MK_STDID0(0x1E9u) /* ID: 0x000001e9, Handle: 11, PPEI_Chassis_General_Status_1 [FC] */, 
  MK_STDID0(0x180u) /* ID: 0x00000180, Handle: 12, LKA_Steering_Torque_Cmd_HS [FC] */, 
  MK_STDID0(0x17Du) /* ID: 0x0000017d, Handle: 13, Antilock_Brake_and_TC_Status_HS [FC] */, 
  MK_STDID0(0x101u) /* ID: 0x00000101, Handle: 24, USDT_Req_to_All_HS_ECUs [FC] */, 
  MK_STDID0(0x0D3u) /* ID: 0x000000d3, Handle: 14, PPEI_Hybrid_General_Status_3_HS [FC] */, 
  MK_STDID0(0x0C9u) /* ID: 0x000000c9, Handle: 15, PPEI_Engine_General_Status_1 [FC] */, 
  MK_STDID0(0x0C1u) /* ID: 0x000000c1, Handle: 16, PPEI_Driven_Whl_Rotational_Stat [FC] */, 
  MK_STDID0(0x34Au) /* ID: 0x0000034a, Handle: 17, NonDriven_Wheel_Grnd_Velocity_CE [FC] */, 
  MK_STDID0(0x348u) /* ID: 0x00000348, Handle: 18, Driven_Wheel_Grnd_Velocity_CE [FC] */, 
  MK_STDID0(0x337u) /* ID: 0x00000337, Handle: 19, Park_Assist_Parallel_CE [FC] */, 
  MK_STDID0(0x242u) /* ID: 0x00000242, Handle: 25, USDT_Req_to_EPS_EPS_JR_CE [FC] */, 
  MK_STDID0(0x182u) /* ID: 0x00000182, Handle: 20, Vehicle_Dynamics_ESC_Hyb_CE [FC] */, 
  MK_STDID0(0x180u) /* ID: 0x00000180, Handle: 21, Steering_Torque_Command_CE [FC] */, 
  MK_STDID0(0x101u) /* ID: 0x00000101, Handle: 26, USDT_Req_to_All_CE_ECUs [FC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanReceiveHandle V_MEMROM2 CanRxMsgIndirection[kCanNumberOfRxObjects] = 
{
  0 /* ID: 0x000007cb, Handle: 0, T1_HostToTarget */, 
  22 /* ID: 0x00000708, Handle: 22, Xcp_Master_Msg */, 
  1 /* ID: 0x00000500, Handle: 1, Wheel_Pulses_HS */, 
  2 /* ID: 0x000004c1, Handle: 2, PPEI_Engine_General_Status_4 */, 
  3 /* ID: 0x000003f1, Handle: 3, PPEI_Platform_Eng_Cntrl_Requests */, 
  4 /* ID: 0x000003e9, Handle: 4, PPEI_Vehicle_Speed_and_Distance */, 
  5 /* ID: 0x0000034a, Handle: 5, NonDriven_Wheel_Grnd_Velocity_HS */, 
  6 /* ID: 0x00000348, Handle: 6, Driven_Wheel_Grnd_Velocity_HS */, 
  23 /* ID: 0x00000242, Handle: 23, USDT_Req_to_EHPS_EPS_HS */, 
  7 /* ID: 0x00000232, Handle: 7, Driving_Mode_Control_HS */, 
  8 /* ID: 0x00000214, Handle: 8, Brake_Pedal_Driver_Status_HS */, 
  9 /* ID: 0x000001f5, Handle: 9, PPEI_Trans_General_Status_2 */, 
  10 /* ID: 0x000001f1, Handle: 10, PPEI_Platform_General_Status */, 
  11 /* ID: 0x000001e9, Handle: 11, PPEI_Chassis_General_Status_1 */, 
  12 /* ID: 0x00000180, Handle: 12, LKA_Steering_Torque_Cmd_HS */, 
  13 /* ID: 0x0000017d, Handle: 13, Antilock_Brake_and_TC_Status_HS */, 
  24 /* ID: 0x00000101, Handle: 24, USDT_Req_to_All_HS_ECUs */, 
  14 /* ID: 0x000000d3, Handle: 14, PPEI_Hybrid_General_Status_3_HS */, 
  15 /* ID: 0x000000c9, Handle: 15, PPEI_Engine_General_Status_1 */, 
  16 /* ID: 0x000000c1, Handle: 16, PPEI_Driven_Whl_Rotational_Stat */, 
  17 /* ID: 0x0000034a, Handle: 17, NonDriven_Wheel_Grnd_Velocity_CE */, 
  18 /* ID: 0x00000348, Handle: 18, Driven_Wheel_Grnd_Velocity_CE */, 
  19 /* ID: 0x00000337, Handle: 19, Park_Assist_Parallel_CE */, 
  25 /* ID: 0x00000242, Handle: 25, USDT_Req_to_EPS_EPS_JR_CE */, 
  20 /* ID: 0x00000182, Handle: 20, Vehicle_Dynamics_ESC_Hyb_CE */, 
  21 /* ID: 0x00000180, Handle: 21, Steering_Torque_Command_CE */, 
  26 /* ID: 0x00000101, Handle: 26, USDT_Req_to_All_CE_ECUs */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanRxDataLen[kCanNumberOfRxObjects] = 
{
  8 /* ID: 0x000007cb, Handle: 0, T1_HostToTarget [FC] */, 
  4 /* ID: 0x00000500, Handle: 1, Wheel_Pulses_HS [FC] */, 
  3 /* ID: 0x000004c1, Handle: 2, PPEI_Engine_General_Status_4 [FC] */, 
  8 /* ID: 0x000003f1, Handle: 3, PPEI_Platform_Eng_Cntrl_Requests [FC] */, 
  8 /* ID: 0x000003e9, Handle: 4, PPEI_Vehicle_Speed_and_Distance [FC] */, 
  5 /* ID: 0x0000034a, Handle: 5, NonDriven_Wheel_Grnd_Velocity_HS [FC] */, 
  5 /* ID: 0x00000348, Handle: 6, Driven_Wheel_Grnd_Velocity_HS [FC] */, 
  5 /* ID: 0x00000232, Handle: 7, Driving_Mode_Control_HS [FC] */, 
  6 /* ID: 0x00000214, Handle: 8, Brake_Pedal_Driver_Status_HS [FC] */, 
  6 /* ID: 0x000001f5, Handle: 9, PPEI_Trans_General_Status_2 [FC] */, 
  8 /* ID: 0x000001f1, Handle: 10, PPEI_Platform_General_Status [FC] */, 
  8 /* ID: 0x000001e9, Handle: 11, PPEI_Chassis_General_Status_1 [FC] */, 
  4 /* ID: 0x00000180, Handle: 12, LKA_Steering_Torque_Cmd_HS [FC] */, 
  1 /* ID: 0x0000017d, Handle: 13, Antilock_Brake_and_TC_Status_HS [FC] */, 
  2 /* ID: 0x000000d3, Handle: 14, PPEI_Hybrid_General_Status_3_HS [FC] */, 
  7 /* ID: 0x000000c9, Handle: 15, PPEI_Engine_General_Status_1 [FC] */, 
  8 /* ID: 0x000000c1, Handle: 16, PPEI_Driven_Whl_Rotational_Stat [FC] */, 
  5 /* ID: 0x0000034a, Handle: 17, NonDriven_Wheel_Grnd_Velocity_CE [FC] */, 
  5 /* ID: 0x00000348, Handle: 18, Driven_Wheel_Grnd_Velocity_CE [FC] */, 
  7 /* ID: 0x00000337, Handle: 19, Park_Assist_Parallel_CE [FC] */, 
  5 /* ID: 0x00000182, Handle: 20, Vehicle_Dynamics_ESC_Hyb_CE [FC] */, 
  8 /* ID: 0x00000180, Handle: 21, Steering_Torque_Command_CE [FC] */, 
  8 /* ID: 0x00000708, Handle: 22, Xcp_Master_Msg [FC] */, 
  0 /* ID: 0x00000242, Handle: 23, USDT_Req_to_EHPS_EPS_HS [FC] */, 
  0 /* ID: 0x00000101, Handle: 24, USDT_Req_to_All_HS_ECUs [FC] */, 
  0 /* ID: 0x00000242, Handle: 25, USDT_Req_to_EPS_EPS_JR_CE [FC] */, 
  8 /* ID: 0x00000101, Handle: 26, USDT_Req_to_All_CE_ECUs [FC] */
};
/* ROM CATEGORY 1 END */


#ifdef C_ENABLE_COPY_RX_DATA
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 RxDataPtr V_MEMROM2 CanRxDataPtr[kCanNumberOfRxObjects] = 
{
  (RxDataPtr) T1_HostToTarget._c /* ID: 0x000007cb, Handle: 0, T1_HostToTarget [FC] */, 
  (RxDataPtr) Wheel_Pulses_HS._c /* ID: 0x00000500, Handle: 1, Wheel_Pulses_HS [FC] */, 
  (RxDataPtr) PPEI_Engine_General_Status_4._c /* ID: 0x000004c1, Handle: 2, PPEI_Engine_General_Status_4 [FC] */, 
  (RxDataPtr) PPEI_Platform_Eng_Cntrl_Requests._c /* ID: 0x000003f1, Handle: 3, PPEI_Platform_Eng_Cntrl_Requests [FC] */, 
  (RxDataPtr) PPEI_Vehicle_Speed_and_Distance._c /* ID: 0x000003e9, Handle: 4, PPEI_Vehicle_Speed_and_Distance [FC] */, 
  (RxDataPtr) NonDriven_Wheel_Grnd_Velocity_HS._c /* ID: 0x0000034a, Handle: 5, NonDriven_Wheel_Grnd_Velocity_HS [FC] */, 
  (RxDataPtr) Driven_Wheel_Grnd_Velocity_HS._c /* ID: 0x00000348, Handle: 6, Driven_Wheel_Grnd_Velocity_HS [FC] */, 
  (RxDataPtr) Driving_Mode_Control_HS._c /* ID: 0x00000232, Handle: 7, Driving_Mode_Control_HS [FC] */, 
  (RxDataPtr) Brake_Pedal_Driver_Status_HS._c /* ID: 0x00000214, Handle: 8, Brake_Pedal_Driver_Status_HS [FC] */, 
  (RxDataPtr) PPEI_Trans_General_Status_2._c /* ID: 0x000001f5, Handle: 9, PPEI_Trans_General_Status_2 [FC] */, 
  (RxDataPtr) PPEI_Platform_General_Status._c /* ID: 0x000001f1, Handle: 10, PPEI_Platform_General_Status [FC] */, 
  (RxDataPtr) PPEI_Chassis_General_Status_1._c /* ID: 0x000001e9, Handle: 11, PPEI_Chassis_General_Status_1 [FC] */, 
  (RxDataPtr) LKA_Steering_Torque_Cmd_HS._c /* ID: 0x00000180, Handle: 12, LKA_Steering_Torque_Cmd_HS [FC] */, 
  (RxDataPtr) Antilock_Brake_and_TC_Status_HS._c /* ID: 0x0000017d, Handle: 13, Antilock_Brake_and_TC_Status_HS [FC] */, 
  (RxDataPtr) PPEI_Hybrid_General_Status_3_HS._c /* ID: 0x000000d3, Handle: 14, PPEI_Hybrid_General_Status_3_HS [FC] */, 
  (RxDataPtr) PPEI_Engine_General_Status_1._c /* ID: 0x000000c9, Handle: 15, PPEI_Engine_General_Status_1 [FC] */, 
  (RxDataPtr) PPEI_Driven_Whl_Rotational_Stat._c /* ID: 0x000000c1, Handle: 16, PPEI_Driven_Whl_Rotational_Stat [FC] */, 
  (RxDataPtr) NonDriven_Wheel_Grnd_Velocity_CE._c /* ID: 0x0000034a, Handle: 17, NonDriven_Wheel_Grnd_Velocity_CE [FC] */, 
  (RxDataPtr) Driven_Wheel_Grnd_Velocity_CE._c /* ID: 0x00000348, Handle: 18, Driven_Wheel_Grnd_Velocity_CE [FC] */, 
  (RxDataPtr) Park_Assist_Parallel_CE._c /* ID: 0x00000337, Handle: 19, Park_Assist_Parallel_CE [FC] */, 
  (RxDataPtr) Vehicle_Dynamics_ESC_Hyb_CE._c /* ID: 0x00000182, Handle: 20, Vehicle_Dynamics_ESC_Hyb_CE [FC] */, 
  (RxDataPtr) Steering_Torque_Command_CE._c /* ID: 0x00000180, Handle: 21, Steering_Torque_Command_CE [FC] */, 
  (RxDataPtr) Xcp_Master_Msg._c /* ID: 0x00000708, Handle: 22, Xcp_Master_Msg [FC] */, 
  (RxDataPtr) 0 /* ID: 0x00000242, Handle: 23, USDT_Req_to_EHPS_EPS_HS [FC] */, 
  (RxDataPtr) 0 /* ID: 0x00000101, Handle: 24, USDT_Req_to_All_HS_ECUs [FC] */, 
  (RxDataPtr) 0 /* ID: 0x00000242, Handle: 25, USDT_Req_to_EPS_EPS_JR_CE [FC] */, 
  (RxDataPtr) 0 /* ID: 0x00000101, Handle: 26, USDT_Req_to_All_CE_ECUs [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_PRECOPY_FCT
/* CODE CATEGORY 1 START */
/* CODE CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplPrecopyFct V_MEMROM2 CanRxApplPrecopyPtr[kCanNumberOfRxObjects] = 
{
  V_NULL /* ID: 0x000007cb, Handle: 0, T1_HostToTarget [FC] */, 
  IlMsgWheel_Pulses_HSPreCopy /* ID: 0x00000500, Handle: 1, Wheel_Pulses_HS [FC] */, 
  IlMsgPPEI_Engine_General_Status_4PreCopy /* ID: 0x000004c1, Handle: 2, PPEI_Engine_General_Status_4 [FC] */, 
  IlMsgPPEI_Platform_Eng_Cntrl_RequestsPreCopy /* ID: 0x000003f1, Handle: 3, PPEI_Platform_Eng_Cntrl_Requests [FC] */, 
  IlMsgPPEI_Vehicle_Speed_and_DistancePreCopy /* ID: 0x000003e9, Handle: 4, PPEI_Vehicle_Speed_and_Distance [FC] */, 
  IlMsgNonDriven_Wheel_Grnd_Velocity_HSPreCopy /* ID: 0x0000034a, Handle: 5, NonDriven_Wheel_Grnd_Velocity_HS [FC] */, 
  IlMsgDriven_Wheel_Grnd_Velocity_HSPreCopy /* ID: 0x00000348, Handle: 6, Driven_Wheel_Grnd_Velocity_HS [FC] */, 
  IlMsgDriving_Mode_Control_HSPreCopy /* ID: 0x00000232, Handle: 7, Driving_Mode_Control_HS [FC] */, 
  IlMsgBrake_Pedal_Driver_Status_HSPreCopy /* ID: 0x00000214, Handle: 8, Brake_Pedal_Driver_Status_HS [FC] */, 
  IlMsgPPEI_Trans_General_Status_2PreCopy /* ID: 0x000001f5, Handle: 9, PPEI_Trans_General_Status_2 [FC] */, 
  IlMsgPPEI_Platform_General_StatusPreCopy /* ID: 0x000001f1, Handle: 10, PPEI_Platform_General_Status [FC] */, 
  IlMsgPPEI_Chassis_General_Status_1PreCopy /* ID: 0x000001e9, Handle: 11, PPEI_Chassis_General_Status_1 [FC] */, 
  IlMsgLKA_Steering_Torque_Cmd_HSPreCopy /* ID: 0x00000180, Handle: 12, LKA_Steering_Torque_Cmd_HS [FC] */, 
  IlMsgAntilock_Brake_and_TC_Status_HSPreCopy /* ID: 0x0000017d, Handle: 13, Antilock_Brake_and_TC_Status_HS [FC] */, 
  IlMsgPPEI_Hybrid_General_Status_3_HSPreCopy /* ID: 0x000000d3, Handle: 14, PPEI_Hybrid_General_Status_3_HS [FC] */, 
  IlMsgPPEI_Engine_General_Status_1PreCopy /* ID: 0x000000c9, Handle: 15, PPEI_Engine_General_Status_1 [FC] */, 
  V_NULL /* ID: 0x000000c1, Handle: 16, PPEI_Driven_Whl_Rotational_Stat [FC] */, 
  IlMsgNonDriven_Wheel_Grnd_Velocity_CEPreCopy /* ID: 0x0000034a, Handle: 17, NonDriven_Wheel_Grnd_Velocity_CE [FC] */, 
  IlMsgDriven_Wheel_Grnd_Velocity_CEPreCopy /* ID: 0x00000348, Handle: 18, Driven_Wheel_Grnd_Velocity_CE [FC] */, 
  IlMsgPark_Assist_Parallel_CEPreCopy /* ID: 0x00000337, Handle: 19, Park_Assist_Parallel_CE [FC] */, 
  IlMsgVehicle_Dynamics_ESC_Hyb_CEPreCopy /* ID: 0x00000182, Handle: 20, Vehicle_Dynamics_ESC_Hyb_CE [FC] */, 
  V_NULL /* ID: 0x00000180, Handle: 21, Steering_Torque_Command_CE [FC] */, 
  XcpPreCopy /* ID: 0x00000708, Handle: 22, Xcp_Master_Msg [FC] */, 
  TpPrecopy /* ID: 0x00000242, Handle: 23, USDT_Req_to_EHPS_EPS_HS [FC] */, 
  TpFuncPrecopy /* ID: 0x00000101, Handle: 24, USDT_Req_to_All_HS_ECUs [FC] */, 
  TpPrecopy /* ID: 0x00000242, Handle: 25, USDT_Req_to_EPS_EPS_JR_CE [FC] */, 
  GgdaFuncPrecopy /* ID: 0x00000101, Handle: 26, USDT_Req_to_All_CE_ECUs [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_INDICATION_FCT
void CanRxWheel_Pulses_HSIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxWheelPulsesHS_x500(rcvObject);
  IlMsgWheel_Pulses_HSIndication(rcvObject);
}


void CanRxPPEI_Engine_General_Status_4IndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxEngineGeneralStatus4_x4C1(rcvObject);
  IlMsgPPEI_Engine_General_Status_4Indication(rcvObject);
}


void CanRxPPEI_Platform_Eng_Cntrl_RequestsIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxPlatformEngCntrlRequests_x3F1(rcvObject);
  IlMsgPPEI_Platform_Eng_Cntrl_RequestsIndication(rcvObject);
}


void CanRxPPEI_Vehicle_Speed_and_DistanceIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxVehicleSpeedAndDistance_x3E9(rcvObject);
  IlMsgPPEI_Vehicle_Speed_and_DistanceIndication(rcvObject);
}


void CanRxNonDriven_Wheel_Grnd_Velocity_HSIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxNonDrivenWheelGrndVelocityHS_x34A(rcvObject);
  IlMsgNonDriven_Wheel_Grnd_Velocity_HSIndication(rcvObject);
}


void CanRxDriven_Wheel_Grnd_Velocity_HSIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxDrivenWheelGrndVelocityHS_x348(rcvObject);
  IlMsgDriven_Wheel_Grnd_Velocity_HSIndication(rcvObject);
}


void CanRxDriving_Mode_Control_HSIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxDrivingModeControlHS_x232(rcvObject);
  IlMsgDriving_Mode_Control_HSIndication(rcvObject);
}


void CanRxBrake_Pedal_Driver_Status_HSIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxBrakePedalDriverStatusHS_x214(rcvObject);
  IlMsgBrake_Pedal_Driver_Status_HSIndication(rcvObject);
}


void CanRxPPEI_Trans_General_Status_2IndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxTransGeneralStatus2_x1F5(rcvObject);
  IlMsgPPEI_Trans_General_Status_2Indication(rcvObject);
}


void CanRxPPEI_Platform_General_StatusIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxPlatformGeneralStatus_x1F1(rcvObject);
  IlMsgPPEI_Platform_General_StatusIndication(rcvObject);
}


void CanRxPPEI_Chassis_General_Status_1IndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxChassisGeneralStatus1_x1E9(rcvObject);
  IlMsgPPEI_Chassis_General_Status_1Indication(rcvObject);
}


void CanRxLKA_Steering_Torque_Cmd_HSIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxLKASteeringTorqueCmdHS_x180(rcvObject);
  IlMsgLKA_Steering_Torque_Cmd_HSIndication(rcvObject);
}


void CanRxAntilock_Brake_and_TC_Status_HSIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxAntilockBrakeandTCStatusHS_x17D(rcvObject);
  IlMsgAntilock_Brake_and_TC_Status_HSIndication(rcvObject);
}


void CanRxPPEI_Hybrid_General_Status_3_HSIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxHybridGeneralStatus3_x0D3(rcvObject);
  IlMsgPPEI_Hybrid_General_Status_3_HSIndication(rcvObject);
}


void CanRxPPEI_Engine_General_Status_1IndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxEngineGeneralStatus1_x0C9(rcvObject);
  IlMsgPPEI_Engine_General_Status_1Indication(rcvObject);
}


void CanRxNonDriven_Wheel_Grnd_Velocity_CEIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxNonDrivenWheelGrndVelocityCE_x34A(rcvObject);
  IlMsgNonDriven_Wheel_Grnd_Velocity_CEIndication(rcvObject);
}


void CanRxDriven_Wheel_Grnd_Velocity_CEIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxDrivenWheelGrndVelocityCE_x348(rcvObject);
  IlMsgDriven_Wheel_Grnd_Velocity_CEIndication(rcvObject);
}


void CanRxPark_Assist_Parallel_CEIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxParkAssistParallelCE_x337(rcvObject);
  IlMsgPark_Assist_Parallel_CEIndication(rcvObject);
}


void CanRxVehicle_Dynamics_ESC_Hyb_CEIndicationFct(CanReceiveHandle rcvObject)
{
  SrlComInput_MsgProcess_RxVehicleDynamicsESCHybCE_x182(rcvObject);
  IlMsgVehicle_Dynamics_ESC_Hyb_CEIndication(rcvObject);
}


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplIndicationFct V_MEMROM2 CanRxApplIndicationPtr[kCanNumberOfRxObjects] = 
{
  GliwaT1_MsgProcess_RxT1HostToTarget /* ID: 0x000007cb, Handle: 0, T1_HostToTarget [FC] */, 
  CanRxWheel_Pulses_HSIndicationFct /* ID: 0x00000500, Handle: 1, Wheel_Pulses_HS [FC] */, 
  CanRxPPEI_Engine_General_Status_4IndicationFct /* ID: 0x000004c1, Handle: 2, PPEI_Engine_General_Status_4 [FC] */, 
  CanRxPPEI_Platform_Eng_Cntrl_RequestsIndicationFct /* ID: 0x000003f1, Handle: 3, PPEI_Platform_Eng_Cntrl_Requests [FC] */, 
  CanRxPPEI_Vehicle_Speed_and_DistanceIndicationFct /* ID: 0x000003e9, Handle: 4, PPEI_Vehicle_Speed_and_Distance [FC] */, 
  CanRxNonDriven_Wheel_Grnd_Velocity_HSIndicationFct /* ID: 0x0000034a, Handle: 5, NonDriven_Wheel_Grnd_Velocity_HS [FC] */, 
  CanRxDriven_Wheel_Grnd_Velocity_HSIndicationFct /* ID: 0x00000348, Handle: 6, Driven_Wheel_Grnd_Velocity_HS [FC] */, 
  CanRxDriving_Mode_Control_HSIndicationFct /* ID: 0x00000232, Handle: 7, Driving_Mode_Control_HS [FC] */, 
  CanRxBrake_Pedal_Driver_Status_HSIndicationFct /* ID: 0x00000214, Handle: 8, Brake_Pedal_Driver_Status_HS [FC] */, 
  CanRxPPEI_Trans_General_Status_2IndicationFct /* ID: 0x000001f5, Handle: 9, PPEI_Trans_General_Status_2 [FC] */, 
  CanRxPPEI_Platform_General_StatusIndicationFct /* ID: 0x000001f1, Handle: 10, PPEI_Platform_General_Status [FC] */, 
  CanRxPPEI_Chassis_General_Status_1IndicationFct /* ID: 0x000001e9, Handle: 11, PPEI_Chassis_General_Status_1 [FC] */, 
  CanRxLKA_Steering_Torque_Cmd_HSIndicationFct /* ID: 0x00000180, Handle: 12, LKA_Steering_Torque_Cmd_HS [FC] */, 
  CanRxAntilock_Brake_and_TC_Status_HSIndicationFct /* ID: 0x0000017d, Handle: 13, Antilock_Brake_and_TC_Status_HS [FC] */, 
  CanRxPPEI_Hybrid_General_Status_3_HSIndicationFct /* ID: 0x000000d3, Handle: 14, PPEI_Hybrid_General_Status_3_HS [FC] */, 
  CanRxPPEI_Engine_General_Status_1IndicationFct /* ID: 0x000000c9, Handle: 15, PPEI_Engine_General_Status_1 [FC] */, 
  SrlComInput_MsgProcess_RxNonDrivnWhlRotationlStat_x0C1 /* ID: 0x000000c1, Handle: 16, PPEI_Driven_Whl_Rotational_Stat [FC] */, 
  CanRxNonDriven_Wheel_Grnd_Velocity_CEIndicationFct /* ID: 0x0000034a, Handle: 17, NonDriven_Wheel_Grnd_Velocity_CE [FC] */, 
  CanRxDriven_Wheel_Grnd_Velocity_CEIndicationFct /* ID: 0x00000348, Handle: 18, Driven_Wheel_Grnd_Velocity_CE [FC] */, 
  CanRxPark_Assist_Parallel_CEIndicationFct /* ID: 0x00000337, Handle: 19, Park_Assist_Parallel_CE [FC] */, 
  CanRxVehicle_Dynamics_ESC_Hyb_CEIndicationFct /* ID: 0x00000182, Handle: 20, Vehicle_Dynamics_ESC_Hyb_CE [FC] */, 
  SrlComInput_MsgProcess_RxSteeringTorqueCmdCE_x180 /* ID: 0x00000180, Handle: 21, Steering_Torque_Command_CE [FC] */, 
  V_NULL /* ID: 0x00000708, Handle: 22, Xcp_Master_Msg [FC] */, 
  V_NULL /* ID: 0x00000242, Handle: 23, USDT_Req_to_EHPS_EPS_HS [FC] */, 
  V_NULL /* ID: 0x00000101, Handle: 24, USDT_Req_to_All_HS_ECUs [FC] */, 
  V_NULL /* ID: 0x00000242, Handle: 25, USDT_Req_to_EPS_EPS_JR_CE [FC] */, 
  V_NULL /* ID: 0x00000101, Handle: 26, USDT_Req_to_All_CE_ECUs [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_INDICATION_FLAG
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanIndicationOffset[kCanNumberOfRxObjects] = 
{
  0 /* ID: 0x000007cb, Handle: 0, T1_HostToTarget [FC] */, 
  0 /* ID: 0x00000500, Handle: 1, Wheel_Pulses_HS [FC] */, 
  0 /* ID: 0x000004c1, Handle: 2, PPEI_Engine_General_Status_4 [FC] */, 
  0 /* ID: 0x000003f1, Handle: 3, PPEI_Platform_Eng_Cntrl_Requests [FC] */, 
  0 /* ID: 0x000003e9, Handle: 4, PPEI_Vehicle_Speed_and_Distance [FC] */, 
  0 /* ID: 0x0000034a, Handle: 5, NonDriven_Wheel_Grnd_Velocity_HS [FC] */, 
  0 /* ID: 0x00000348, Handle: 6, Driven_Wheel_Grnd_Velocity_HS [FC] */, 
  0 /* ID: 0x00000232, Handle: 7, Driving_Mode_Control_HS [FC] */, 
  0 /* ID: 0x00000214, Handle: 8, Brake_Pedal_Driver_Status_HS [FC] */, 
  0 /* ID: 0x000001f5, Handle: 9, PPEI_Trans_General_Status_2 [FC] */, 
  0 /* ID: 0x000001f1, Handle: 10, PPEI_Platform_General_Status [FC] */, 
  0 /* ID: 0x000001e9, Handle: 11, PPEI_Chassis_General_Status_1 [FC] */, 
  0 /* ID: 0x00000180, Handle: 12, LKA_Steering_Torque_Cmd_HS [FC] */, 
  0 /* ID: 0x0000017d, Handle: 13, Antilock_Brake_and_TC_Status_HS [FC] */, 
  0 /* ID: 0x000000d3, Handle: 14, PPEI_Hybrid_General_Status_3_HS [FC] */, 
  0 /* ID: 0x000000c9, Handle: 15, PPEI_Engine_General_Status_1 [FC] */, 
  0 /* ID: 0x000000c1, Handle: 16, PPEI_Driven_Whl_Rotational_Stat [FC] */, 
  0 /* ID: 0x0000034a, Handle: 17, NonDriven_Wheel_Grnd_Velocity_CE [FC] */, 
  0 /* ID: 0x00000348, Handle: 18, Driven_Wheel_Grnd_Velocity_CE [FC] */, 
  0 /* ID: 0x00000337, Handle: 19, Park_Assist_Parallel_CE [FC] */, 
  0 /* ID: 0x00000182, Handle: 20, Vehicle_Dynamics_ESC_Hyb_CE [FC] */, 
  0 /* ID: 0x00000180, Handle: 21, Steering_Torque_Command_CE [FC] */, 
  0 /* ID: 0x00000708, Handle: 22, Xcp_Master_Msg [FC] */, 
  0 /* ID: 0x00000242, Handle: 23, USDT_Req_to_EHPS_EPS_HS [FC] */, 
  0 /* ID: 0x00000101, Handle: 24, USDT_Req_to_All_HS_ECUs [FC] */, 
  0 /* ID: 0x00000242, Handle: 25, USDT_Req_to_EPS_EPS_JR_CE [FC] */, 
  0 /* ID: 0x00000101, Handle: 26, USDT_Req_to_All_CE_ECUs [FC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanIndicationMask[kCanNumberOfRxObjects] = 
{
  0x00u /* ID: 0x000007cb, Handle: 0, T1_HostToTarget [FC] */, 
  0x00u /* ID: 0x00000500, Handle: 1, Wheel_Pulses_HS [FC] */, 
  0x00u /* ID: 0x000004c1, Handle: 2, PPEI_Engine_General_Status_4 [FC] */, 
  0x00u /* ID: 0x000003f1, Handle: 3, PPEI_Platform_Eng_Cntrl_Requests [FC] */, 
  0x00u /* ID: 0x000003e9, Handle: 4, PPEI_Vehicle_Speed_and_Distance [FC] */, 
  0x00u /* ID: 0x0000034a, Handle: 5, NonDriven_Wheel_Grnd_Velocity_HS [FC] */, 
  0x00u /* ID: 0x00000348, Handle: 6, Driven_Wheel_Grnd_Velocity_HS [FC] */, 
  0x00u /* ID: 0x00000232, Handle: 7, Driving_Mode_Control_HS [FC] */, 
  0x00u /* ID: 0x00000214, Handle: 8, Brake_Pedal_Driver_Status_HS [FC] */, 
  0x00u /* ID: 0x000001f5, Handle: 9, PPEI_Trans_General_Status_2 [FC] */, 
  0x00u /* ID: 0x000001f1, Handle: 10, PPEI_Platform_General_Status [FC] */, 
  0x00u /* ID: 0x000001e9, Handle: 11, PPEI_Chassis_General_Status_1 [FC] */, 
  0x00u /* ID: 0x00000180, Handle: 12, LKA_Steering_Torque_Cmd_HS [FC] */, 
  0x00u /* ID: 0x0000017d, Handle: 13, Antilock_Brake_and_TC_Status_HS [FC] */, 
  0x00u /* ID: 0x000000d3, Handle: 14, PPEI_Hybrid_General_Status_3_HS [FC] */, 
  0x00u /* ID: 0x000000c9, Handle: 15, PPEI_Engine_General_Status_1 [FC] */, 
  0x00u /* ID: 0x000000c1, Handle: 16, PPEI_Driven_Whl_Rotational_Stat [FC] */, 
  0x00u /* ID: 0x0000034a, Handle: 17, NonDriven_Wheel_Grnd_Velocity_CE [FC] */, 
  0x00u /* ID: 0x00000348, Handle: 18, Driven_Wheel_Grnd_Velocity_CE [FC] */, 
  0x00u /* ID: 0x00000337, Handle: 19, Park_Assist_Parallel_CE [FC] */, 
  0x00u /* ID: 0x00000182, Handle: 20, Vehicle_Dynamics_ESC_Hyb_CE [FC] */, 
  0x00u /* ID: 0x00000180, Handle: 21, Steering_Torque_Command_CE [FC] */, 
  0x01u /* ID: 0x00000708, Handle: 22, Xcp_Master_Msg [FC] */, 
  0x00u /* ID: 0x00000242, Handle: 23, USDT_Req_to_EHPS_EPS_HS [FC] */, 
  0x00u /* ID: 0x00000101, Handle: 24, USDT_Req_to_All_HS_ECUs [FC] */, 
  0x00u /* ID: 0x00000242, Handle: 25, USDT_Req_to_EPS_EPS_JR_CE [FC] */, 
  0x00u /* ID: 0x00000101, Handle: 26, USDT_Req_to_All_CE_ECUs [FC] */
};
/* ROM CATEGORY 1 END */


#endif




/* -----------------------------------------------------------------------------
    &&&~ Init structures
 ----------------------------------------------------------------------------- */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanInitObjectStartIndex[3] = 
{
  0, 
  1, 
  2
};

/* ROM CATEGORY 4 END */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitBRP_Reg[2] = 
{
  0x00u, 
  0x00u
};
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitBitTiming[2] = 
{
  0x7F05u, 
  0x2A89u
};
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitBasicMsk1[2][1] = 
{
  
  {
    0x0000u
  }, 
  
  {
    0x0000u
  }
};
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitBasicMsk2[2][1] = 
{
  
  {
    0xFFFCu
  }, 
  
  {
    0xFFFCu
  }
};
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitBasicCod1[2][1] = 
{
  
  {
    0x0000u
  }, 
  
  {
    0x0000u
  }
};
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitBasicCod2[2][1] = 
{
  
  {
    0x0304u
  }, 
  
  {
    0x0000u
  }
};
/* ROM CATEGORY 4 END */



/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanTransmitHandle V_MEMROM2 CanTxDynRomStartIndex[kCanNumberOfChannels] = 
{
  7, 
  12
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */

V_MEMROM0 V_MEMROM1 CanTransmitHandle V_MEMROM2 CanTxDynRamStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  0, 
  0
};

/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tCanChannelObject V_MEMROM2 CanChannelObject[kCanNumberOfChannels] = 
{
  
  {
    ApplCanChannelDummy, 
    CAN_RECEIVE_FCT_DUMMY, 
    
    {
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY
    }, 
    NmCanError, 
    IlCanCancelNotification, 
    ApplCanChannelDummy, 
    
    {
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u)
    }, 
    
    {
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u)
    }, 
    0x00u, 
    
    {
      kCanIdTypeStd, 
      kCanIdTypeStd, 
      kCanIdTypeStd, 
      kCanIdTypeStd
    }
  }, 
  
  {
    ApplCanChannelDummy, 
    CAN_RECEIVE_FCT_DUMMY, 
    
    {
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY
    }, 
    NmCanError, 
    IlCanCancelNotification, 
    ApplCanChannelDummy, 
    
    {
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u)
    }, 
    
    {
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u)
    }, 
    0x00u, 
    
    {
      kCanIdTypeStd, 
      kCanIdTypeStd, 
      kCanIdTypeStd, 
      kCanIdTypeStd
    }
  }
};
/* ROM CATEGORY 1 END */

#if defined(C_ENABLE_MULTI_ECU_CONFIG)
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanPhysToLogChannel[kVNumberOfIdentities][kCanNumberOfPhysChannels] = 
{
  
  {
    0, 
    1
  }
};
/* ROM CATEGORY 1 END */

#endif

#if defined(C_ENABLE_MULTI_ECU_CONFIG)
/* ROM CATEGORY 2 START */

V_MEMROM0 V_MEMROM1 tVIdentityMsk V_MEMROM2 CanChannelIdentityAssignment[kCanNumberOfChannels] = 
{
  0x01u, 
  0x01u
};

/* ROM CATEGORY 2 END */

#endif

#if defined(C_ENABLE_MULTI_ECU_PHYS)
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tVIdentityMsk V_MEMROM2 CanRxIdentityAssignment[kCanNumberOfRxObjects] = 
{
  0x01u /* ID: 0x000007cb, Handle: 0, T1_HostToTarget [FC] */, 
  0x01u /* ID: 0x00000500, Handle: 1, Wheel_Pulses_HS [FC] */, 
  0x01u /* ID: 0x000004c1, Handle: 2, PPEI_Engine_General_Status_4 [FC] */, 
  0x01u /* ID: 0x000003f1, Handle: 3, PPEI_Platform_Eng_Cntrl_Requests [FC] */, 
  0x01u /* ID: 0x000003e9, Handle: 4, PPEI_Vehicle_Speed_and_Distance [FC] */, 
  0x01u /* ID: 0x0000034a, Handle: 5, NonDriven_Wheel_Grnd_Velocity_HS [FC] */, 
  0x01u /* ID: 0x00000348, Handle: 6, Driven_Wheel_Grnd_Velocity_HS [FC] */, 
  0x01u /* ID: 0x00000232, Handle: 7, Driving_Mode_Control_HS [FC] */, 
  0x01u /* ID: 0x00000214, Handle: 8, Brake_Pedal_Driver_Status_HS [FC] */, 
  0x01u /* ID: 0x000001f5, Handle: 9, PPEI_Trans_General_Status_2 [FC] */, 
  0x01u /* ID: 0x000001f1, Handle: 10, PPEI_Platform_General_Status [FC] */, 
  0x01u /* ID: 0x000001e9, Handle: 11, PPEI_Chassis_General_Status_1 [FC] */, 
  0x01u /* ID: 0x00000180, Handle: 12, LKA_Steering_Torque_Cmd_HS [FC] */, 
  0x01u /* ID: 0x0000017d, Handle: 13, Antilock_Brake_and_TC_Status_HS [FC] */, 
  0x01u /* ID: 0x000000d3, Handle: 14, PPEI_Hybrid_General_Status_3_HS [FC] */, 
  0x01u /* ID: 0x000000c9, Handle: 15, PPEI_Engine_General_Status_1 [FC] */, 
  0x01u /* ID: 0x000000c1, Handle: 16, PPEI_Driven_Whl_Rotational_Stat [FC] */, 
  0x01u /* ID: 0x0000034a, Handle: 17, NonDriven_Wheel_Grnd_Velocity_CE [FC] */, 
  0x01u /* ID: 0x00000348, Handle: 18, Driven_Wheel_Grnd_Velocity_CE [FC] */, 
  0x01u /* ID: 0x00000337, Handle: 19, Park_Assist_Parallel_CE [FC] */, 
  0x01u /* ID: 0x00000182, Handle: 20, Vehicle_Dynamics_ESC_Hyb_CE [FC] */, 
  0x01u /* ID: 0x00000180, Handle: 21, Steering_Torque_Command_CE [FC] */, 
  0x01u /* ID: 0x00000708, Handle: 22, Xcp_Master_Msg [FC] */, 
  0x01u /* ID: 0x00000242, Handle: 23, USDT_Req_to_EHPS_EPS_HS [FC] */, 
  0x01u /* ID: 0x00000101, Handle: 24, USDT_Req_to_All_HS_ECUs [FC] */, 
  0x01u /* ID: 0x00000242, Handle: 25, USDT_Req_to_EPS_EPS_JR_CE [FC] */, 
  0x01u /* ID: 0x00000101, Handle: 26, USDT_Req_to_All_CE_ECUs [FC] */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 tVIdentityMsk V_MEMROM2 CanTxIdentityAssignment[kCanNumberOfTxObjects] = 
{
  0x01u /* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */, 
  0x01u /* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */, 
  0x01u /* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */, 
  0x01u /* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */, 
  0x01u /* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */, 
  0x01u /* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */, 
  0x01u /* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */, 
  0x01u /* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  0x01u /* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  0x01u /* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */, 
  0x01u /* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */, 
  0x01u /* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
};
/* ROM CATEGORY 4 END */

#endif


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxQueuePadBits[kCanNumberOfChannels] = 
{
  0, 
  25
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanSignedTxHandle V_MEMROM2 CanTxQueueStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  1, 
  2
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanChannelHandle V_MEMROM2 CanTxMsgHandleToChannel[kCanNumberOfTxObjects] = 
{
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  1, 
  1, 
  1, 
  1, 
  1
};
/* ROM CATEGORY 2 END */


/* ROM CATEGORY 1 START */

V_MEMROM0 V_MEMROM1 CanTransmitHandle V_MEMROM2 CanTxStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  7, 
  12
};

/* ROM CATEGORY 1 END */


/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanReceiveHandle V_MEMROM2 CanRxStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  20, 
  27
};
/* ROM CATEGORY 2 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanReceiveHandle V_MEMROM2 CanRxBasicStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  20, 
  27
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanReceiveHandle V_MEMROM2 CanRxFullStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  20, 
  27
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanLogHwTxStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  9, 
  16
};
/* ROM CATEGORY 2 END */


/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwTxStartIndex[kCanNumberOfChannels] = 
{
  0, 
  0
};
/* ROM CATEGORY 2 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwRxFullStartIndex[kCanNumberOfChannels] = 
{
  42, 
  55
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwRxBasicStartIndex[kCanNumberOfChannels] = 
{
  62, 
  62
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 4 START */

V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwUnusedStartIndex[kCanNumberOfChannels] = 
{
  9, 
  7
};

/* ROM CATEGORY 4 END */


/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwTxStopIndex[kCanNumberOfChannels] = 
{
  9, 
  7
};
/* ROM CATEGORY 2 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwRxFullStopIndex[kCanNumberOfChannels] = 
{
  62, 
  62
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwRxBasicStopIndex[kCanNumberOfChannels] = 
{
  64, 
  64
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 4 START */

V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwUnusedStopIndex[kCanNumberOfChannels] = 
{
  42, 
  55
};

/* ROM CATEGORY 4 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwMsgTransmitIndex[kCanNumberOfChannels] = 
{
  8, 
  6
};
/* ROM CATEGORY 1 END */


#ifdef C_ENABLE_TX_FULLCAN_OBJECTS
/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxHwObj[kCanNumberOfTxObjects] = 
{
  0x06u /* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */, 
  0x05u /* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */, 
  0x04u /* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */, 
  0x03u /* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */, 
  0x02u /* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */, 
  0x01u /* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */, 
  0x00u /* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */, 
  0x04u /* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  0x03u /* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */, 
  0x02u /* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */, 
  0x01u /* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */, 
  0x00u /* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
};
/* ROM CATEGORY 2 END */

#endif



/* ROM CATEGORY 1 START */

V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwTxNormalIndex[kCanNumberOfChannels] = 
{
  7, 
  5
};

/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */

V_MEMROM0 V_MEMROM1 vsintx V_MEMROM2 CanTxOffsetHwToLog[kCanNumberOfChannels] = 
{
  0, 
  9
};

/* ROM CATEGORY 1 END */



/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanHwObjIndivPolling[kCanNumberOfHwChannels][kCanNumberOfHwObjIndivPolling] = 
{
  
  {
    0 /* Channel0, Power_Steering_Information_HS */, 
    0 /* Channel0, LKA_Steering_Trq_Overlay_Stat_HS */, 
    0 /* Channel0, PPEI_Steering_Wheel_Angle */, 
    0 /* Channel0, UUDT_Resp_From_EHPS_EPS_HS */, 
    0 /* Channel0, USDT_Resp_From_EHPS_EPS_HS */, 
    0 /* Channel0, Xcp_Slave_Msg */, 
    0 /* Channel0, DTC_Triggered_778 */, 
    0 /* Channel0, Normal Tx Polling */, 
    0 /* Channel0, LowLevel Tx Polling */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    1 /* Channel0, T1_HostToTarget */, 
    0 /* Channel0, Xcp_Master_Msg */, 
    1 /* Channel0, Wheel_Pulses_HS */, 
    1 /* Channel0, PPEI_Engine_General_Status_4 */, 
    1 /* Channel0, PPEI_Platform_Eng_Cntrl_Requests */, 
    1 /* Channel0, PPEI_Vehicle_Speed_and_Distance */, 
    1 /* Channel0, NonDriven_Wheel_Grnd_Velocity_HS */, 
    1 /* Channel0, Driven_Wheel_Grnd_Velocity_HS */, 
    0 /* Channel0, USDT_Req_to_EHPS_EPS_HS */, 
    1 /* Channel0, Driving_Mode_Control_HS */, 
    1 /* Channel0, Brake_Pedal_Driver_Status_HS */, 
    1 /* Channel0, PPEI_Trans_General_Status_2 */, 
    1 /* Channel0, PPEI_Platform_General_Status */, 
    1 /* Channel0, PPEI_Chassis_General_Status_1 */, 
    1 /* Channel0, LKA_Steering_Torque_Cmd_HS */, 
    1 /* Channel0, Antilock_Brake_and_TC_Status_HS */, 
    0 /* Channel0, USDT_Req_to_All_HS_ECUs */, 
    0 /* Channel0, PPEI_Hybrid_General_Status_3_HS */, 
    1 /* Channel0, PPEI_Engine_General_Status_1 */, 
    0 /* Channel0, PPEI_Driven_Whl_Rotational_Stat */, 
    0 /* Channel0, BasicCAN0 Rx Polling */, 
    0 /* Channel0, BasicCAN0 Rx Polling */
  }, 
  
  {
    0 /* Channel1, Steering_Torque_Overlay_Stat_CE */, 
    0 /* Channel1, PPEI_Steering_Wheel_Angle_CE */, 
    0 /* Channel1, Electric_Power_Steering_CE */, 
    0 /* Channel1, UUDT_Resp_From_EPS_EPS_JR_CE */, 
    0 /* Channel1, USDT_Resp_From_EPS_EPS_JR_CE */, 
    0 /* Channel1, Normal Tx Polling */, 
    0 /* Channel1, LowLevel Tx Polling */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    0 /* Unused */, 
    1 /* Channel1, NonDriven_Wheel_Grnd_Velocity_CE */, 
    1 /* Channel1, Driven_Wheel_Grnd_Velocity_CE */, 
    1 /* Channel1, Park_Assist_Parallel_CE */, 
    0 /* Channel1, USDT_Req_to_EPS_EPS_JR_CE */, 
    1 /* Channel1, Vehicle_Dynamics_ESC_Hyb_CE */, 
    0 /* Channel1, Steering_Torque_Command_CE */, 
    0 /* Channel1, USDT_Req_to_All_CE_ECUs */, 
    0 /* Channel1, BasicCAN0 Rx Polling */, 
    0 /* Channel1, BasicCAN0 Rx Polling */
  }
};
/* ROM CATEGORY 1 END */

V_MEMROM0 V_MEMROM1 vuint32 V_MEMROM2 CanBasisAdr[kCanNumberOfChannels] = 
{
  0xFFF7DC00u, 
  0xFFF7DE00u
};
V_MEMROM0 V_MEMROM1 vuint32 V_MEMROM2 interruptSrc[kCanNumberOfChannels] = 
{
  0x00010000u, 
  0x00000008u
};
V_MEMROM0 V_MEMROM1 vuint32 V_MEMROM2 vimClrReg[kCanNumberOfChannels] = 
{
  0xFFFFFE40u, 
  0xFFFFFE44u
};
V_MEMROM0 V_MEMROM1 vuint32 V_MEMROM2 vimSetReg[kCanNumberOfChannels] = 
{
  0xFFFFFE30u, 
  0xFFFFFE34u
};
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanNumberOfMsgObj[kCanNumberOfChannels] = 
{
  64, 
  64
};


/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 133574485
      #error "The magic number of the generated file <C:\Synergy\GM_C1XX_EPS_TMS570-dzxvzg\GM_C1XX_EPS_TMS570\SwProject\Source\_GenData\can_par.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <C:\Synergy\GM_C1XX_EPS_TMS570-dzxvzg\GM_C1XX_EPS_TMS570\SwProject\Source\_GenData\can_par.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

