/* -----------------------------------------------------------------------------
  Filename:    can_par.h
  Description: Toolversion: 08.31.00.01.01.01.23.01.00.00
                
                Serial Number: CBD1010123
                Customer Info: Nxtr
                               Package: GM GMLAN_30_Indx 
                               Micro: TI TMS570 TMS570X5LS20216
                               Compiler: Code Composer Studio 4.6.4
                
                
                Generator Fwk   : GENy 
                Generator Module: DrvCan__base
                
                Configuration   : C:\_synergy\9BXX_CZ8L9T\GM_9BXX_EPS_TMS570\Tools\AsrProject\GENy\RT_2.0_Mod.gny
                
                ECU: 
                        TargetSystem: Hw_Tms470/570Cpu (Dcan)
                        Compiler:     TexasInstruments
                        Derivates:    TMS570PSFC66
                
                Channel "Channel0":
                        Databasefile: C:\_synergy\9BXX_CZ8L9T\GM_9BXX_EPS_TMS570\Tools\AsrProject\GENy\GlobalA_HS.dbc
                        Bussystem:    CAN
                        Manufacturer: General Motors
                        Node:         EPS_HS
                Channel "Channel1":
                        Databasefile: C:\Synergy\GM_C1XX_EPS_TMS570-zz4r1x1\GM_C1XX_EPS_TMS570\Tools\AsrProject\GENy\GlobalA_CE.dbc
                        Bussystem:    CAN
                        Manufacturer: General Motors
                        Node:         EPS_CE

  Generated by , 2016-04-28  10:27:04
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2008 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__CAN_PAR_H__)
#define __CAN_PAR_H__

#include "can_cfg.h"
#include "v_inc.h"
#include "drv_par.h"

/* -----------------------------------------------------------------------------
    &&&~ Extern declarations of callback functions
 ----------------------------------------------------------------------------- */

/* CODE CATEGORY 4 START */

extern void NmCanError(CanChannelHandle channel);

/* CODE CATEGORY 4 END */


/* CODE CATEGORY 4 START */

extern void NmCanWakeUp(CanChannelHandle channel);

/* CODE CATEGORY 4 END */


#if defined(C_MULTIPLE_RECEIVE_CHANNEL) || defined(C_SINGLE_RECEIVE_CHANNEL)
#endif

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgWheel_Pulses_HSPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgPPEI_Engine_General_Status_4PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgPPEI_Platform_Eng_Cntrl_RequestsPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgPPEI_Vehicle_Speed_and_DistancePreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgNonDriven_Wheel_Grnd_Velocity_HSPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgDriven_Wheel_Grnd_Velocity_HSPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgDriving_Mode_Control_HSPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgBrake_Pedal_Driver_Status_HSPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgPPEI_Trans_General_Status_2PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgPPEI_Platform_General_StatusPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgPPEI_Chassis_General_Status_1PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgLKA_Steering_Torque_Cmd_HSPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgAntilock_Brake_and_TC_Status_HSPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgPPEI_Hybrid_General_Status_3_HSPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgPPEI_Engine_General_Status_1PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgNonDriven_Wheel_Grnd_Velocity_CEPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgDriven_Wheel_Grnd_Velocity_CEPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgPark_Assist_Parallel_CEPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgVehicle_Dynamics_ESC_Hyb_CEPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 XcpPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 TpPrecopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 TpFuncPrecopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 GgdaFuncPrecopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */


/* -----------------------------------------------------------------------------
    &&&~ Extern declarations of confirmation functions
 ----------------------------------------------------------------------------- */

/* CODE CATEGORY 1 START */
extern void XcpConfirmation(CanTransmitHandle txObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void TpDrvConfirmation(CanTransmitHandle txObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void DescUudtConfirmation(CanTransmitHandle txObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Appl_1E5MsgTxAck_HS(CanTransmitHandle txObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void GgdaUudtConfirmation(CanTransmitHandle txObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Appl_1E5MsgTxAck_CE(CanTransmitHandle txObject);
/* CODE CATEGORY 1 END */



/* -----------------------------------------------------------------------------
    &&&~ Extern declarations of indication functions
 ----------------------------------------------------------------------------- */

/* CODE CATEGORY 1 START */
extern void GliwaT1_MsgProcess_RxT1HostToTarget(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxWheelPulsesHS_x500(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void CanRxWheel_Pulses_HSIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */
/* CODE CATEGORY 1 START */
extern void IlMsgWheel_Pulses_HSIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxEngineGeneralStatus4_x4C1(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxPPEI_Engine_General_Status_4IndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgPPEI_Engine_General_Status_4Indication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxPlatformEngCntrlRequests_x3F1(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxPPEI_Platform_Eng_Cntrl_RequestsIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgPPEI_Platform_Eng_Cntrl_RequestsIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxVehicleSpeedAndDistance_x3E9(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxPPEI_Vehicle_Speed_and_DistanceIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgPPEI_Vehicle_Speed_and_DistanceIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxNonDrivenWheelGrndVelocityHS_x34A(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxNonDriven_Wheel_Grnd_Velocity_HSIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgNonDriven_Wheel_Grnd_Velocity_HSIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxDrivenWheelGrndVelocityHS_x348(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxDriven_Wheel_Grnd_Velocity_HSIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgDriven_Wheel_Grnd_Velocity_HSIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxDrivingModeControlHS_x232(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxDriving_Mode_Control_HSIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgDriving_Mode_Control_HSIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxBrakePedalDriverStatusHS_x214(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxBrake_Pedal_Driver_Status_HSIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgBrake_Pedal_Driver_Status_HSIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxTransGeneralStatus2_x1F5(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxPPEI_Trans_General_Status_2IndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgPPEI_Trans_General_Status_2Indication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxPlatformGeneralStatus_x1F1(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxPPEI_Platform_General_StatusIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgPPEI_Platform_General_StatusIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxChassisGeneralStatus1_x1E9(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxPPEI_Chassis_General_Status_1IndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgPPEI_Chassis_General_Status_1Indication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxLKASteeringTorqueCmdHS_x180(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxLKA_Steering_Torque_Cmd_HSIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgLKA_Steering_Torque_Cmd_HSIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxAntilockBrakeandTCStatusHS_x17D(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxAntilock_Brake_and_TC_Status_HSIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgAntilock_Brake_and_TC_Status_HSIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxHybridGeneralStatus3_x0D3(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxPPEI_Hybrid_General_Status_3_HSIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgPPEI_Hybrid_General_Status_3_HSIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxEngineGeneralStatus1_x0C9(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxPPEI_Engine_General_Status_1IndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgPPEI_Engine_General_Status_1Indication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxNonDrivnWhlRotationlStat_x0C1(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxNonDrivenWheelGrndVelocityCE_x34A(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxNonDriven_Wheel_Grnd_Velocity_CEIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgNonDriven_Wheel_Grnd_Velocity_CEIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxDrivenWheelGrndVelocityCE_x348(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxDriven_Wheel_Grnd_Velocity_CEIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgDriven_Wheel_Grnd_Velocity_CEIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxParkAssistParallelCE_x337(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxPark_Assist_Parallel_CEIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgPark_Assist_Parallel_CEIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxVehicleDynamicsESCHybCE_x182(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxVehicle_Dynamics_ESC_Hyb_CEIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgVehicle_Dynamics_ESC_Hyb_CEIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void SrlComInput_MsgProcess_RxSteeringTorqueCmdCE_x180(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */



/* -----------------------------------------------------------------------------
    &&&~ Multiple Callback Functions
 ----------------------------------------------------------------------------- */

/* CODE CATEGORY 3 START */
extern C_CALLBACK_1 void C_CALLBACK_2 IlCanCancelNotification(CanTransmitHandle txHandle);
/* CODE CATEGORY 3 END */




/* -----------------------------------------------------------------------------
    &&&~ Handles of send objects
 ----------------------------------------------------------------------------- */

#define CanTxDTC_Triggered_778               0
#define CanTxXcp_Slave_Msg                   1
#define CanTxUSDT_Resp_From_EHPS_EPS_HS      2
#define CanTxUUDT_Resp_From_EHPS_EPS_HS      3
#define CanTxPPEI_Steering_Wheel_Angle       4
#define CanTxLKA_Steering_Trq_Overlay_Stat_HS 5
#define CanTxPower_Steering_Information_HS   6
#define CanTxUSDT_Resp_From_EPS_EPS_JR_CE    7
#define CanTxUUDT_Resp_From_EPS_EPS_JR_CE    8
#define CanTxElectric_Power_Steering_CE      9
#define CanTxPPEI_Steering_Wheel_Angle_CE    10
#define CanTxSteering_Torque_Overlay_Stat_CE 11


/* -----------------------------------------------------------------------------
    &&&~ Access to confirmation flags
 ----------------------------------------------------------------------------- */

#define DTC_Triggered_778_conf_b             (CanConfirmationFlags.w[0].b0)
#define CanWriteSyncDTC_Triggered_778_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  DTC_Triggered_778_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define PPEI_Steering_Wheel_Angle_conf_b     (CanConfirmationFlags.w[0].b1)
#define CanWriteSyncPPEI_Steering_Wheel_Angle_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  PPEI_Steering_Wheel_Angle_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define LKA_Steering_Trq_Overlay_Stat_HS_conf_b (CanConfirmationFlags.w[0].b2)
#define CanWriteSyncLKA_Steering_Trq_Overlay_Stat_HS_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  LKA_Steering_Trq_Overlay_Stat_HS_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define Power_Steering_Information_HS_conf_b (CanConfirmationFlags.w[0].b3)
#define CanWriteSyncPower_Steering_Information_HS_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  Power_Steering_Information_HS_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define Electric_Power_Steering_CE_conf_b    (CanConfirmationFlags.w[0].b4)
#define CanWriteSyncElectric_Power_Steering_CE_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  Electric_Power_Steering_CE_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define PPEI_Steering_Wheel_Angle_CE_conf_b  (CanConfirmationFlags.w[0].b5)
#define CanWriteSyncPPEI_Steering_Wheel_Angle_CE_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  PPEI_Steering_Wheel_Angle_CE_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define Steering_Torque_Overlay_Stat_CE_conf_b (CanConfirmationFlags.w[0].b6)
#define CanWriteSyncSteering_Torque_Overlay_Stat_CE_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  Steering_Torque_Overlay_Stat_CE_conf_b = (x); \
  CanEndFlagWriteSync(); \
}


/* -----------------------------------------------------------------------------
    &&&~ Handles of receive objects
 ----------------------------------------------------------------------------- */

#define CanRxT1_HostToTarget                 0
#define CanRxWheel_Pulses_HS                 1
#define CanRxPPEI_Engine_General_Status_4    2
#define CanRxPPEI_Platform_Eng_Cntrl_Requests 3
#define CanRxPPEI_Vehicle_Speed_and_Distance 4
#define CanRxNonDriven_Wheel_Grnd_Velocity_HS 5
#define CanRxDriven_Wheel_Grnd_Velocity_HS   6
#define CanRxDriving_Mode_Control_HS         7
#define CanRxBrake_Pedal_Driver_Status_HS    8
#define CanRxPPEI_Trans_General_Status_2     9
#define CanRxPPEI_Platform_General_Status    10
#define CanRxPPEI_Chassis_General_Status_1   11
#define CanRxLKA_Steering_Torque_Cmd_HS      12
#define CanRxAntilock_Brake_and_TC_Status_HS 13
#define CanRxPPEI_Hybrid_General_Status_3_HS 14
#define CanRxPPEI_Engine_General_Status_1    15
#define CanRxPPEI_Driven_Whl_Rotational_Stat 16
#define CanRxNonDriven_Wheel_Grnd_Velocity_CE 17
#define CanRxDriven_Wheel_Grnd_Velocity_CE   18
#define CanRxPark_Assist_Parallel_CE         19
#define CanRxVehicle_Dynamics_ESC_Hyb_CE     20
#define CanRxSteering_Torque_Command_CE      21
#define CanRxXcp_Master_Msg                  22
#define CanRxUSDT_Req_to_EHPS_EPS_HS         23
#define CanRxUSDT_Req_to_All_HS_ECUs         24
#define CanRxUSDT_Req_to_EPS_EPS_JR_CE       25
#define CanRxUSDT_Req_to_All_CE_ECUs         26


/* -----------------------------------------------------------------------------
    &&&~ Access to indication flags
 ----------------------------------------------------------------------------- */

#define Xcp_Master_Msg_ind_b                 (CanIndicationFlags.w[0].b0)
#define CanWriteSyncXcp_Master_Msg_ind_b(x) \
{ \
  CanStartFlagWriteSync(); \
  Xcp_Master_Msg_ind_b = (x); \
  CanEndFlagWriteSync(); \
}


/* -----------------------------------------------------------------------------
    &&&~ Access to data bytes of Rx messages
 ----------------------------------------------------------------------------- */

/* ID: 0x000007cb, Handle: 0, T1_HostToTarget [FC] */
#define c1_T1_HostToTarget_c                 (T1_HostToTarget._c[0])
#define c2_T1_HostToTarget_c                 (T1_HostToTarget._c[1])
#define c3_T1_HostToTarget_c                 (T1_HostToTarget._c[2])
#define c4_T1_HostToTarget_c                 (T1_HostToTarget._c[3])
#define c5_T1_HostToTarget_c                 (T1_HostToTarget._c[4])
#define c6_T1_HostToTarget_c                 (T1_HostToTarget._c[5])
#define c7_T1_HostToTarget_c                 (T1_HostToTarget._c[6])
#define c8_T1_HostToTarget_c                 (T1_HostToTarget._c[7])

/* ID: 0x00000500, Handle: 1, Wheel_Pulses_HS [FC] */
#define c1_Wheel_Pulses_HS_c                 (Wheel_Pulses_HS._c[0])
#define c2_Wheel_Pulses_HS_c                 (Wheel_Pulses_HS._c[1])
#define c3_Wheel_Pulses_HS_c                 (Wheel_Pulses_HS._c[2])
#define c4_Wheel_Pulses_HS_c                 (Wheel_Pulses_HS._c[3])

/* ID: 0x000004c1, Handle: 2, PPEI_Engine_General_Status_4 [FC] */
#define c1_PPEI_Engine_General_Status_4_c    (PPEI_Engine_General_Status_4._c[0])
#define c2_PPEI_Engine_General_Status_4_c    (PPEI_Engine_General_Status_4._c[1])
#define c3_PPEI_Engine_General_Status_4_c    (PPEI_Engine_General_Status_4._c[2])

/* ID: 0x000003f1, Handle: 3, PPEI_Platform_Eng_Cntrl_Requests [FC] */
#define c1_PPEI_Platform_Eng_Cntrl_Requests_c (PPEI_Platform_Eng_Cntrl_Requests._c[0])
#define c2_PPEI_Platform_Eng_Cntrl_Requests_c (PPEI_Platform_Eng_Cntrl_Requests._c[1])
#define c3_PPEI_Platform_Eng_Cntrl_Requests_c (PPEI_Platform_Eng_Cntrl_Requests._c[2])
#define c4_PPEI_Platform_Eng_Cntrl_Requests_c (PPEI_Platform_Eng_Cntrl_Requests._c[3])
#define c5_PPEI_Platform_Eng_Cntrl_Requests_c (PPEI_Platform_Eng_Cntrl_Requests._c[4])
#define c6_PPEI_Platform_Eng_Cntrl_Requests_c (PPEI_Platform_Eng_Cntrl_Requests._c[5])
#define c7_PPEI_Platform_Eng_Cntrl_Requests_c (PPEI_Platform_Eng_Cntrl_Requests._c[6])
#define c8_PPEI_Platform_Eng_Cntrl_Requests_c (PPEI_Platform_Eng_Cntrl_Requests._c[7])

/* ID: 0x000003e9, Handle: 4, PPEI_Vehicle_Speed_and_Distance [FC] */
#define c1_PPEI_Vehicle_Speed_and_Distance_c (PPEI_Vehicle_Speed_and_Distance._c[0])
#define c2_PPEI_Vehicle_Speed_and_Distance_c (PPEI_Vehicle_Speed_and_Distance._c[1])
#define c3_PPEI_Vehicle_Speed_and_Distance_c (PPEI_Vehicle_Speed_and_Distance._c[2])
#define c4_PPEI_Vehicle_Speed_and_Distance_c (PPEI_Vehicle_Speed_and_Distance._c[3])
#define c5_PPEI_Vehicle_Speed_and_Distance_c (PPEI_Vehicle_Speed_and_Distance._c[4])
#define c6_PPEI_Vehicle_Speed_and_Distance_c (PPEI_Vehicle_Speed_and_Distance._c[5])
#define c7_PPEI_Vehicle_Speed_and_Distance_c (PPEI_Vehicle_Speed_and_Distance._c[6])
#define c8_PPEI_Vehicle_Speed_and_Distance_c (PPEI_Vehicle_Speed_and_Distance._c[7])

/* ID: 0x0000034a, Handle: 5, NonDriven_Wheel_Grnd_Velocity_HS [FC] */
#define c1_NonDriven_Wheel_Grnd_Velocity_HS_c (NonDriven_Wheel_Grnd_Velocity_HS._c[0])
#define c2_NonDriven_Wheel_Grnd_Velocity_HS_c (NonDriven_Wheel_Grnd_Velocity_HS._c[1])
#define c3_NonDriven_Wheel_Grnd_Velocity_HS_c (NonDriven_Wheel_Grnd_Velocity_HS._c[2])
#define c4_NonDriven_Wheel_Grnd_Velocity_HS_c (NonDriven_Wheel_Grnd_Velocity_HS._c[3])
#define c5_NonDriven_Wheel_Grnd_Velocity_HS_c (NonDriven_Wheel_Grnd_Velocity_HS._c[4])

/* ID: 0x00000348, Handle: 6, Driven_Wheel_Grnd_Velocity_HS [FC] */
#define c1_Driven_Wheel_Grnd_Velocity_HS_c   (Driven_Wheel_Grnd_Velocity_HS._c[0])
#define c2_Driven_Wheel_Grnd_Velocity_HS_c   (Driven_Wheel_Grnd_Velocity_HS._c[1])
#define c3_Driven_Wheel_Grnd_Velocity_HS_c   (Driven_Wheel_Grnd_Velocity_HS._c[2])
#define c4_Driven_Wheel_Grnd_Velocity_HS_c   (Driven_Wheel_Grnd_Velocity_HS._c[3])
#define c5_Driven_Wheel_Grnd_Velocity_HS_c   (Driven_Wheel_Grnd_Velocity_HS._c[4])

/* ID: 0x00000232, Handle: 7, Driving_Mode_Control_HS [FC] */
#define c1_Driving_Mode_Control_HS_c         (Driving_Mode_Control_HS._c[0])
#define c2_Driving_Mode_Control_HS_c         (Driving_Mode_Control_HS._c[1])
#define c3_Driving_Mode_Control_HS_c         (Driving_Mode_Control_HS._c[2])
#define c4_Driving_Mode_Control_HS_c         (Driving_Mode_Control_HS._c[3])
#define c5_Driving_Mode_Control_HS_c         (Driving_Mode_Control_HS._c[4])

/* ID: 0x00000214, Handle: 8, Brake_Pedal_Driver_Status_HS [FC] */
#define c1_Brake_Pedal_Driver_Status_HS_c    (Brake_Pedal_Driver_Status_HS._c[0])
#define c2_Brake_Pedal_Driver_Status_HS_c    (Brake_Pedal_Driver_Status_HS._c[1])
#define c3_Brake_Pedal_Driver_Status_HS_c    (Brake_Pedal_Driver_Status_HS._c[2])
#define c4_Brake_Pedal_Driver_Status_HS_c    (Brake_Pedal_Driver_Status_HS._c[3])
#define c5_Brake_Pedal_Driver_Status_HS_c    (Brake_Pedal_Driver_Status_HS._c[4])
#define c6_Brake_Pedal_Driver_Status_HS_c    (Brake_Pedal_Driver_Status_HS._c[5])

/* ID: 0x000001f5, Handle: 9, PPEI_Trans_General_Status_2 [FC] */
#define c1_PPEI_Trans_General_Status_2_c     (PPEI_Trans_General_Status_2._c[0])
#define c2_PPEI_Trans_General_Status_2_c     (PPEI_Trans_General_Status_2._c[1])
#define c3_PPEI_Trans_General_Status_2_c     (PPEI_Trans_General_Status_2._c[2])
#define c4_PPEI_Trans_General_Status_2_c     (PPEI_Trans_General_Status_2._c[3])
#define c5_PPEI_Trans_General_Status_2_c     (PPEI_Trans_General_Status_2._c[4])
#define c6_PPEI_Trans_General_Status_2_c     (PPEI_Trans_General_Status_2._c[5])

/* ID: 0x000001f1, Handle: 10, PPEI_Platform_General_Status [FC] */
#define c1_PPEI_Platform_General_Status_c    (PPEI_Platform_General_Status._c[0])
#define c2_PPEI_Platform_General_Status_c    (PPEI_Platform_General_Status._c[1])
#define c3_PPEI_Platform_General_Status_c    (PPEI_Platform_General_Status._c[2])
#define c4_PPEI_Platform_General_Status_c    (PPEI_Platform_General_Status._c[3])
#define c5_PPEI_Platform_General_Status_c    (PPEI_Platform_General_Status._c[4])
#define c6_PPEI_Platform_General_Status_c    (PPEI_Platform_General_Status._c[5])
#define c7_PPEI_Platform_General_Status_c    (PPEI_Platform_General_Status._c[6])
#define c8_PPEI_Platform_General_Status_c    (PPEI_Platform_General_Status._c[7])

/* ID: 0x000001e9, Handle: 11, PPEI_Chassis_General_Status_1 [FC] */
#define c1_PPEI_Chassis_General_Status_1_c   (PPEI_Chassis_General_Status_1._c[0])
#define c2_PPEI_Chassis_General_Status_1_c   (PPEI_Chassis_General_Status_1._c[1])
#define c3_PPEI_Chassis_General_Status_1_c   (PPEI_Chassis_General_Status_1._c[2])
#define c4_PPEI_Chassis_General_Status_1_c   (PPEI_Chassis_General_Status_1._c[3])
#define c5_PPEI_Chassis_General_Status_1_c   (PPEI_Chassis_General_Status_1._c[4])
#define c6_PPEI_Chassis_General_Status_1_c   (PPEI_Chassis_General_Status_1._c[5])
#define c7_PPEI_Chassis_General_Status_1_c   (PPEI_Chassis_General_Status_1._c[6])
#define c8_PPEI_Chassis_General_Status_1_c   (PPEI_Chassis_General_Status_1._c[7])

/* ID: 0x00000180, Handle: 12, LKA_Steering_Torque_Cmd_HS [FC] */
#define c1_LKA_Steering_Torque_Cmd_HS_c      (LKA_Steering_Torque_Cmd_HS._c[0])
#define c2_LKA_Steering_Torque_Cmd_HS_c      (LKA_Steering_Torque_Cmd_HS._c[1])
#define c3_LKA_Steering_Torque_Cmd_HS_c      (LKA_Steering_Torque_Cmd_HS._c[2])
#define c4_LKA_Steering_Torque_Cmd_HS_c      (LKA_Steering_Torque_Cmd_HS._c[3])

/* ID: 0x0000017d, Handle: 13, Antilock_Brake_and_TC_Status_HS [FC] */
#define c1_Antilock_Brake_and_TC_Status_HS_c (Antilock_Brake_and_TC_Status_HS._c[0])

/* ID: 0x000000d3, Handle: 14, PPEI_Hybrid_General_Status_3_HS [FC] */
#define c1_PPEI_Hybrid_General_Status_3_HS_c (PPEI_Hybrid_General_Status_3_HS._c[0])
#define c2_PPEI_Hybrid_General_Status_3_HS_c (PPEI_Hybrid_General_Status_3_HS._c[1])

/* ID: 0x000000c9, Handle: 15, PPEI_Engine_General_Status_1 [FC] */
#define c1_PPEI_Engine_General_Status_1_c    (PPEI_Engine_General_Status_1._c[0])
#define c2_PPEI_Engine_General_Status_1_c    (PPEI_Engine_General_Status_1._c[1])
#define c3_PPEI_Engine_General_Status_1_c    (PPEI_Engine_General_Status_1._c[2])
#define c4_PPEI_Engine_General_Status_1_c    (PPEI_Engine_General_Status_1._c[3])
#define c5_PPEI_Engine_General_Status_1_c    (PPEI_Engine_General_Status_1._c[4])
#define c6_PPEI_Engine_General_Status_1_c    (PPEI_Engine_General_Status_1._c[5])
#define c7_PPEI_Engine_General_Status_1_c    (PPEI_Engine_General_Status_1._c[6])

/* ID: 0x000000c1, Handle: 16, PPEI_Driven_Whl_Rotational_Stat [FC] */
#define c1_PPEI_Driven_Whl_Rotational_Stat_c (PPEI_Driven_Whl_Rotational_Stat._c[0])
#define c2_PPEI_Driven_Whl_Rotational_Stat_c (PPEI_Driven_Whl_Rotational_Stat._c[1])
#define c3_PPEI_Driven_Whl_Rotational_Stat_c (PPEI_Driven_Whl_Rotational_Stat._c[2])
#define c4_PPEI_Driven_Whl_Rotational_Stat_c (PPEI_Driven_Whl_Rotational_Stat._c[3])
#define c5_PPEI_Driven_Whl_Rotational_Stat_c (PPEI_Driven_Whl_Rotational_Stat._c[4])
#define c6_PPEI_Driven_Whl_Rotational_Stat_c (PPEI_Driven_Whl_Rotational_Stat._c[5])
#define c7_PPEI_Driven_Whl_Rotational_Stat_c (PPEI_Driven_Whl_Rotational_Stat._c[6])
#define c8_PPEI_Driven_Whl_Rotational_Stat_c (PPEI_Driven_Whl_Rotational_Stat._c[7])

/* ID: 0x0000034a, Handle: 17, NonDriven_Wheel_Grnd_Velocity_CE [FC] */
#define c1_NonDriven_Wheel_Grnd_Velocity_CE_c (NonDriven_Wheel_Grnd_Velocity_CE._c[0])
#define c2_NonDriven_Wheel_Grnd_Velocity_CE_c (NonDriven_Wheel_Grnd_Velocity_CE._c[1])
#define c3_NonDriven_Wheel_Grnd_Velocity_CE_c (NonDriven_Wheel_Grnd_Velocity_CE._c[2])
#define c4_NonDriven_Wheel_Grnd_Velocity_CE_c (NonDriven_Wheel_Grnd_Velocity_CE._c[3])
#define c5_NonDriven_Wheel_Grnd_Velocity_CE_c (NonDriven_Wheel_Grnd_Velocity_CE._c[4])

/* ID: 0x00000348, Handle: 18, Driven_Wheel_Grnd_Velocity_CE [FC] */
#define c1_Driven_Wheel_Grnd_Velocity_CE_c   (Driven_Wheel_Grnd_Velocity_CE._c[0])
#define c2_Driven_Wheel_Grnd_Velocity_CE_c   (Driven_Wheel_Grnd_Velocity_CE._c[1])
#define c3_Driven_Wheel_Grnd_Velocity_CE_c   (Driven_Wheel_Grnd_Velocity_CE._c[2])
#define c4_Driven_Wheel_Grnd_Velocity_CE_c   (Driven_Wheel_Grnd_Velocity_CE._c[3])
#define c5_Driven_Wheel_Grnd_Velocity_CE_c   (Driven_Wheel_Grnd_Velocity_CE._c[4])

/* ID: 0x00000337, Handle: 19, Park_Assist_Parallel_CE [FC] */
#define c1_Park_Assist_Parallel_CE_c         (Park_Assist_Parallel_CE._c[0])
#define c2_Park_Assist_Parallel_CE_c         (Park_Assist_Parallel_CE._c[1])
#define c3_Park_Assist_Parallel_CE_c         (Park_Assist_Parallel_CE._c[2])
#define c4_Park_Assist_Parallel_CE_c         (Park_Assist_Parallel_CE._c[3])
#define c5_Park_Assist_Parallel_CE_c         (Park_Assist_Parallel_CE._c[4])
#define c6_Park_Assist_Parallel_CE_c         (Park_Assist_Parallel_CE._c[5])
#define c7_Park_Assist_Parallel_CE_c         (Park_Assist_Parallel_CE._c[6])

/* ID: 0x00000182, Handle: 20, Vehicle_Dynamics_ESC_Hyb_CE [FC] */
#define c1_Vehicle_Dynamics_ESC_Hyb_CE_c     (Vehicle_Dynamics_ESC_Hyb_CE._c[0])
#define c2_Vehicle_Dynamics_ESC_Hyb_CE_c     (Vehicle_Dynamics_ESC_Hyb_CE._c[1])
#define c3_Vehicle_Dynamics_ESC_Hyb_CE_c     (Vehicle_Dynamics_ESC_Hyb_CE._c[2])
#define c4_Vehicle_Dynamics_ESC_Hyb_CE_c     (Vehicle_Dynamics_ESC_Hyb_CE._c[3])
#define c5_Vehicle_Dynamics_ESC_Hyb_CE_c     (Vehicle_Dynamics_ESC_Hyb_CE._c[4])

/* ID: 0x00000180, Handle: 21, Steering_Torque_Command_CE [FC] */
#define c1_Steering_Torque_Command_CE_c      (Steering_Torque_Command_CE._c[0])
#define c2_Steering_Torque_Command_CE_c      (Steering_Torque_Command_CE._c[1])
#define c3_Steering_Torque_Command_CE_c      (Steering_Torque_Command_CE._c[2])
#define c4_Steering_Torque_Command_CE_c      (Steering_Torque_Command_CE._c[3])
#define c5_Steering_Torque_Command_CE_c      (Steering_Torque_Command_CE._c[4])
#define c6_Steering_Torque_Command_CE_c      (Steering_Torque_Command_CE._c[5])
#define c7_Steering_Torque_Command_CE_c      (Steering_Torque_Command_CE._c[6])
#define c8_Steering_Torque_Command_CE_c      (Steering_Torque_Command_CE._c[7])

/* ID: 0x00000708, Handle: 22, Xcp_Master_Msg [FC] */
#define c1_Xcp_Master_Msg_c                  (Xcp_Master_Msg._c[0])
#define c2_Xcp_Master_Msg_c                  (Xcp_Master_Msg._c[1])
#define c3_Xcp_Master_Msg_c                  (Xcp_Master_Msg._c[2])
#define c4_Xcp_Master_Msg_c                  (Xcp_Master_Msg._c[3])
#define c5_Xcp_Master_Msg_c                  (Xcp_Master_Msg._c[4])
#define c6_Xcp_Master_Msg_c                  (Xcp_Master_Msg._c[5])
#define c7_Xcp_Master_Msg_c                  (Xcp_Master_Msg._c[6])
#define c8_Xcp_Master_Msg_c                  (Xcp_Master_Msg._c[7])



/* -----------------------------------------------------------------------------
    &&&~ Access to data bytes of Tx messages
 ----------------------------------------------------------------------------- */

/* ID: 0x00000778, Handle: 0, DTC_Triggered_778 [FC] */
#define c1_DTC_Triggered_778_c               (DTC_Triggered_778._c[0])
#define c2_DTC_Triggered_778_c               (DTC_Triggered_778._c[1])
#define c3_DTC_Triggered_778_c               (DTC_Triggered_778._c[2])
#define c4_DTC_Triggered_778_c               (DTC_Triggered_778._c[3])
#define c5_DTC_Triggered_778_c               (DTC_Triggered_778._c[4])
#define c6_DTC_Triggered_778_c               (DTC_Triggered_778._c[5])
#define c7_DTC_Triggered_778_c               (DTC_Triggered_778._c[6])

/* ID: 0x00000706, Handle: 1, Xcp_Slave_Msg [FC] */
#define c1_Xcp_Slave_Msg_c                   (Xcp_Slave_Msg._c[0])
#define c2_Xcp_Slave_Msg_c                   (Xcp_Slave_Msg._c[1])
#define c3_Xcp_Slave_Msg_c                   (Xcp_Slave_Msg._c[2])
#define c4_Xcp_Slave_Msg_c                   (Xcp_Slave_Msg._c[3])
#define c5_Xcp_Slave_Msg_c                   (Xcp_Slave_Msg._c[4])
#define c6_Xcp_Slave_Msg_c                   (Xcp_Slave_Msg._c[5])
#define c7_Xcp_Slave_Msg_c                   (Xcp_Slave_Msg._c[6])
#define c8_Xcp_Slave_Msg_c                   (Xcp_Slave_Msg._c[7])

/* ID: 0x00000642, Handle: 2, USDT_Resp_From_EHPS_EPS_HS [FC] */
#define c1_USDT_Resp_From_EHPS_EPS_HS_c      (USDT_Resp_From_EHPS_EPS_HS._c[0])
#define c2_USDT_Resp_From_EHPS_EPS_HS_c      (USDT_Resp_From_EHPS_EPS_HS._c[1])
#define c3_USDT_Resp_From_EHPS_EPS_HS_c      (USDT_Resp_From_EHPS_EPS_HS._c[2])
#define c4_USDT_Resp_From_EHPS_EPS_HS_c      (USDT_Resp_From_EHPS_EPS_HS._c[3])
#define c5_USDT_Resp_From_EHPS_EPS_HS_c      (USDT_Resp_From_EHPS_EPS_HS._c[4])
#define c6_USDT_Resp_From_EHPS_EPS_HS_c      (USDT_Resp_From_EHPS_EPS_HS._c[5])
#define c7_USDT_Resp_From_EHPS_EPS_HS_c      (USDT_Resp_From_EHPS_EPS_HS._c[6])
#define c8_USDT_Resp_From_EHPS_EPS_HS_c      (USDT_Resp_From_EHPS_EPS_HS._c[7])

/* ID: 0x00000542, Handle: 3, UUDT_Resp_From_EHPS_EPS_HS [FC] */
#define c1_UUDT_Resp_From_EHPS_EPS_HS_c      (UUDT_Resp_From_EHPS_EPS_HS._c[0])
#define c2_UUDT_Resp_From_EHPS_EPS_HS_c      (UUDT_Resp_From_EHPS_EPS_HS._c[1])
#define c3_UUDT_Resp_From_EHPS_EPS_HS_c      (UUDT_Resp_From_EHPS_EPS_HS._c[2])
#define c4_UUDT_Resp_From_EHPS_EPS_HS_c      (UUDT_Resp_From_EHPS_EPS_HS._c[3])
#define c5_UUDT_Resp_From_EHPS_EPS_HS_c      (UUDT_Resp_From_EHPS_EPS_HS._c[4])
#define c6_UUDT_Resp_From_EHPS_EPS_HS_c      (UUDT_Resp_From_EHPS_EPS_HS._c[5])
#define c7_UUDT_Resp_From_EHPS_EPS_HS_c      (UUDT_Resp_From_EHPS_EPS_HS._c[6])
#define c8_UUDT_Resp_From_EHPS_EPS_HS_c      (UUDT_Resp_From_EHPS_EPS_HS._c[7])

/* ID: 0x000001e5, Handle: 4, PPEI_Steering_Wheel_Angle [BC] */
#define c1_PPEI_Steering_Wheel_Angle_c       (PPEI_Steering_Wheel_Angle._c[0])
#define c2_PPEI_Steering_Wheel_Angle_c       (PPEI_Steering_Wheel_Angle._c[1])
#define c3_PPEI_Steering_Wheel_Angle_c       (PPEI_Steering_Wheel_Angle._c[2])
#define c4_PPEI_Steering_Wheel_Angle_c       (PPEI_Steering_Wheel_Angle._c[3])
#define c5_PPEI_Steering_Wheel_Angle_c       (PPEI_Steering_Wheel_Angle._c[4])
#define c6_PPEI_Steering_Wheel_Angle_c       (PPEI_Steering_Wheel_Angle._c[5])
#define c7_PPEI_Steering_Wheel_Angle_c       (PPEI_Steering_Wheel_Angle._c[6])
#define c8_PPEI_Steering_Wheel_Angle_c       (PPEI_Steering_Wheel_Angle._c[7])

/* ID: 0x00000184, Handle: 5, LKA_Steering_Trq_Overlay_Stat_HS [FC] */
#define c1_LKA_Steering_Trq_Overlay_Stat_HS_c (LKA_Steering_Trq_Overlay_Stat_HS._c[0])
#define c2_LKA_Steering_Trq_Overlay_Stat_HS_c (LKA_Steering_Trq_Overlay_Stat_HS._c[1])
#define c3_LKA_Steering_Trq_Overlay_Stat_HS_c (LKA_Steering_Trq_Overlay_Stat_HS._c[2])
#define c4_LKA_Steering_Trq_Overlay_Stat_HS_c (LKA_Steering_Trq_Overlay_Stat_HS._c[3])
#define c5_LKA_Steering_Trq_Overlay_Stat_HS_c (LKA_Steering_Trq_Overlay_Stat_HS._c[4])
#define c6_LKA_Steering_Trq_Overlay_Stat_HS_c (LKA_Steering_Trq_Overlay_Stat_HS._c[5])
#define c7_LKA_Steering_Trq_Overlay_Stat_HS_c (LKA_Steering_Trq_Overlay_Stat_HS._c[6])
#define c8_LKA_Steering_Trq_Overlay_Stat_HS_c (LKA_Steering_Trq_Overlay_Stat_HS._c[7])

/* ID: 0x00000148, Handle: 6, Power_Steering_Information_HS [FC] */
#define c1_Power_Steering_Information_HS_c   (Power_Steering_Information_HS._c[0])

/* ID: 0x00000642, Handle: 7, USDT_Resp_From_EPS_EPS_JR_CE [FC] */
#define c1_USDT_Resp_From_EPS_EPS_JR_CE_c    (USDT_Resp_From_EPS_EPS_JR_CE._c[0])
#define c2_USDT_Resp_From_EPS_EPS_JR_CE_c    (USDT_Resp_From_EPS_EPS_JR_CE._c[1])
#define c3_USDT_Resp_From_EPS_EPS_JR_CE_c    (USDT_Resp_From_EPS_EPS_JR_CE._c[2])
#define c4_USDT_Resp_From_EPS_EPS_JR_CE_c    (USDT_Resp_From_EPS_EPS_JR_CE._c[3])
#define c5_USDT_Resp_From_EPS_EPS_JR_CE_c    (USDT_Resp_From_EPS_EPS_JR_CE._c[4])
#define c6_USDT_Resp_From_EPS_EPS_JR_CE_c    (USDT_Resp_From_EPS_EPS_JR_CE._c[5])
#define c7_USDT_Resp_From_EPS_EPS_JR_CE_c    (USDT_Resp_From_EPS_EPS_JR_CE._c[6])
#define c8_USDT_Resp_From_EPS_EPS_JR_CE_c    (USDT_Resp_From_EPS_EPS_JR_CE._c[7])

/* ID: 0x00000542, Handle: 8, UUDT_Resp_From_EPS_EPS_JR_CE [FC] */
#define c1_UUDT_Resp_From_EPS_EPS_JR_CE_c    (UUDT_Resp_From_EPS_EPS_JR_CE._c[0])
#define c2_UUDT_Resp_From_EPS_EPS_JR_CE_c    (UUDT_Resp_From_EPS_EPS_JR_CE._c[1])
#define c3_UUDT_Resp_From_EPS_EPS_JR_CE_c    (UUDT_Resp_From_EPS_EPS_JR_CE._c[2])
#define c4_UUDT_Resp_From_EPS_EPS_JR_CE_c    (UUDT_Resp_From_EPS_EPS_JR_CE._c[3])
#define c5_UUDT_Resp_From_EPS_EPS_JR_CE_c    (UUDT_Resp_From_EPS_EPS_JR_CE._c[4])
#define c6_UUDT_Resp_From_EPS_EPS_JR_CE_c    (UUDT_Resp_From_EPS_EPS_JR_CE._c[5])
#define c7_UUDT_Resp_From_EPS_EPS_JR_CE_c    (UUDT_Resp_From_EPS_EPS_JR_CE._c[6])
#define c8_UUDT_Resp_From_EPS_EPS_JR_CE_c    (UUDT_Resp_From_EPS_EPS_JR_CE._c[7])

/* ID: 0x00000335, Handle: 9, Electric_Power_Steering_CE [FC] */
#define c1_Electric_Power_Steering_CE_c      (Electric_Power_Steering_CE._c[0])
#define c2_Electric_Power_Steering_CE_c      (Electric_Power_Steering_CE._c[1])
#define c3_Electric_Power_Steering_CE_c      (Electric_Power_Steering_CE._c[2])
#define c4_Electric_Power_Steering_CE_c      (Electric_Power_Steering_CE._c[3])

/* ID: 0x000001e5, Handle: 10, PPEI_Steering_Wheel_Angle_CE [BC] */
#define c1_PPEI_Steering_Wheel_Angle_CE_c    (PPEI_Steering_Wheel_Angle_CE._c[0])
#define c2_PPEI_Steering_Wheel_Angle_CE_c    (PPEI_Steering_Wheel_Angle_CE._c[1])
#define c3_PPEI_Steering_Wheel_Angle_CE_c    (PPEI_Steering_Wheel_Angle_CE._c[2])
#define c4_PPEI_Steering_Wheel_Angle_CE_c    (PPEI_Steering_Wheel_Angle_CE._c[3])
#define c5_PPEI_Steering_Wheel_Angle_CE_c    (PPEI_Steering_Wheel_Angle_CE._c[4])
#define c6_PPEI_Steering_Wheel_Angle_CE_c    (PPEI_Steering_Wheel_Angle_CE._c[5])
#define c7_PPEI_Steering_Wheel_Angle_CE_c    (PPEI_Steering_Wheel_Angle_CE._c[6])
#define c8_PPEI_Steering_Wheel_Angle_CE_c    (PPEI_Steering_Wheel_Angle_CE._c[7])

/* ID: 0x000001ca, Handle: 11, Steering_Torque_Overlay_Stat_CE [FC] */
#define c1_Steering_Torque_Overlay_Stat_CE_c (Steering_Torque_Overlay_Stat_CE._c[0])
#define c2_Steering_Torque_Overlay_Stat_CE_c (Steering_Torque_Overlay_Stat_CE._c[1])
#define c3_Steering_Torque_Overlay_Stat_CE_c (Steering_Torque_Overlay_Stat_CE._c[2])
#define c4_Steering_Torque_Overlay_Stat_CE_c (Steering_Torque_Overlay_Stat_CE._c[3])
#define c5_Steering_Torque_Overlay_Stat_CE_c (Steering_Torque_Overlay_Stat_CE._c[4])
#define c6_Steering_Torque_Overlay_Stat_CE_c (Steering_Torque_Overlay_Stat_CE._c[5])
#define c7_Steering_Torque_Overlay_Stat_CE_c (Steering_Torque_Overlay_Stat_CE._c[6])
#define c8_Steering_Torque_Overlay_Stat_CE_c (Steering_Torque_Overlay_Stat_CE._c[7])



/* -----------------------------------------------------------------------------
    &&&~ RDS Access
 ----------------------------------------------------------------------------- */

typedef struct _c_Power_Steering_Information_HS_RDS_msgTypeTag
{
  vbittype unused0 : 4;
  vbittype StrAsstRdcdLvl3IO : 1;
  vbittype StrAsstRdcdLvl2IO : 1;
  vbittype StrngAsstRdcdIO : 1;
  vbittype PwrStrIO : 1;
} _c_Power_Steering_Information_HS_RDS_msgType;

typedef struct _c_LKA_Steering_Trq_Overlay_Stat_HS_RDS_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype LKATrqOvrlTrqDStat : 3;
  vbittype LKAElPwrStTtlTqDlvd_1 : 3;
  vbittype LKAElPwrStTtlTqDlvd_0 : 8;
  vbittype unused1 : 1;
  vbittype HndsOffStrWhlDtStV : 1;
  vbittype HndsOffStrWhlDtSt : 1;
  vbittype HndsOffStrWhlDtMd : 2;
  vbittype LKATrqOvrlDltTrqDlvd_1 : 3;
  vbittype LKATrqOvrlDltTrqDlvd_0 : 8;
  vbittype unused2 : 1;
  vbittype LKATrqOvrlDlvdRC : 4;
  vbittype LKATrqOvrlStatChksm_1 : 3;
  vbittype LKATrqOvrlStatChksm_0 : 8;
  vbittype unused3 : 4;
  vbittype LKADrvAppldTrqV : 1;
  vbittype LKADrvAppldTrq_1 : 3;
  vbittype LKADrvAppldTrq_0 : 8;
} _c_LKA_Steering_Trq_Overlay_Stat_HS_RDS_msgType;

typedef struct _c_PPEI_Steering_Wheel_Angle_RDS_msgTypeTag
{
  vbittype StrWhAngV_0 : 1;
  vbittype StrWhlAngSenCalStat_0 : 2;
  vbittype StrWhlAngSenTyp_0 : 2;
  vbittype StrWhAngMsk_0 : 1;
  vbittype unused0 : 2;
  vbittype StrWhAng_0_1 : 8;
  vbittype StrWhAng_0_0 : 8;
  vbittype StrWhAngGrdV_0 : 1;
  vbittype StWhlAngAliveRollCnt_0 : 2;
  vbittype StrWhAngGrdMsk_0 : 1;
  vbittype StrWhAngGrd_0_1 : 4;
  vbittype StrWhAngGrd_0_0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 5;
  vbittype StrAngSnsChksm_0_1 : 3;
  vbittype StrAngSnsChksm_0_0 : 8;
} _c_PPEI_Steering_Wheel_Angle_RDS_msgType;

typedef struct _c_UUDT_Resp_From_EHPS_EPS_HS_RDS_msgTypeTag
{
  vbittype DgnInf_HS542_7 : 8;
  vbittype DgnInf_HS542_6 : 8;
  vbittype DgnInf_HS542_5 : 8;
  vbittype DgnInf_HS542_4 : 8;
  vbittype DgnInf_HS542_3 : 8;
  vbittype DgnInf_HS542_2 : 8;
  vbittype DgnInf_HS542_1 : 8;
  vbittype DgnInf_HS542_0 : 8;
} _c_UUDT_Resp_From_EHPS_EPS_HS_RDS_msgType;

typedef struct _c_USDT_Resp_From_EHPS_EPS_HS_RDS_msgTypeTag
{
  vbittype DgnInf_0_7 : 8;
  vbittype DgnInf_0_6 : 8;
  vbittype DgnInf_0_5 : 8;
  vbittype DgnInf_0_4 : 8;
  vbittype DgnInf_0_3 : 8;
  vbittype DgnInf_0_2 : 8;
  vbittype DgnInf_0_1 : 8;
  vbittype DgnInf_0_0 : 8;
} _c_USDT_Resp_From_EHPS_EPS_HS_RDS_msgType;

typedef struct _c_Xcp_Slave_Msg_RDS_msgTypeTag
{
  vbittype Xcp_Slave_Byte0 : 8;
  vbittype Xcp_Slave_Byte1 : 8;
  vbittype Xcp_Slave_Byte2 : 8;
  vbittype Xcp_Slave_Byte3 : 8;
  vbittype Xcp_Slave_Byte4 : 8;
  vbittype Xcp_Slave_Byte5 : 8;
  vbittype Xcp_Slave_Byte6 : 8;
  vbittype Xcp_Slave_Byte7 : 8;
} _c_Xcp_Slave_Msg_RDS_msgType;

typedef struct _c_DTC_Triggered_778_RDS_msgTypeTag
{
  vbittype DTCIUnused1_778 : 1;
  vbittype DTCIUnused2_778 : 1;
  vbittype DTCIUnused3_778 : 1;
  vbittype DTCIUnused4_778 : 1;
  vbittype DTCIUnused5_778 : 1;
  vbittype DTCIUnused6_778 : 1;
  vbittype DTCIUnused7_778 : 1;
  vbittype DTCI_DTCTriggered_778 : 1;
  vbittype DTCI_DTCSource_778 : 8;
  vbittype DTCI_DTCNumber_778_1 : 8;
  vbittype DTCI_DTCNumber_778_0 : 8;
  vbittype DTCI_DTCFailType_778 : 8;
  vbittype DTCI_WrnIndRqdSt_778 : 1;
  vbittype DTCI_TstFldPwrUpSt_778 : 1;
  vbittype DTCI_TstNPsdPwrUpSt_778 : 1;
  vbittype DTCI_HistStat_778 : 1;
  vbittype DTCI_TstFldCdClrdStat_778 : 1;
  vbittype DTCI_TstNPsdCdClrdSt_778 : 1;
  vbittype DTCI_CurrentStatus_778 : 1;
  vbittype DTCI_CodeSupported_778 : 1;
  vbittype DTCI_DTCFaultType_778 : 8;
} _c_DTC_Triggered_778_RDS_msgType;

typedef struct _c_T1_HostToTarget_RDS_msgTypeTag
{
  vbittype T1_HostToTarget_0 : 8;
  vbittype T1_HostToTarget_1 : 8;
  vbittype T1_HostToTarget_2 : 8;
  vbittype T1_HostToTarget_3 : 8;
  vbittype T1_HostToTarget_4 : 8;
  vbittype T1_HostToTarget_5 : 8;
  vbittype T1_HostToTarget_6 : 8;
  vbittype T1_HostToTarget_7 : 8;
} _c_T1_HostToTarget_RDS_msgType;

typedef struct _c_Xcp_Master_Msg_RDS_msgTypeTag
{
  vbittype Xcp_Master_Byte0 : 8;
  vbittype Xcp_Master_Byte1 : 8;
  vbittype Xcp_Master_Byte2 : 8;
  vbittype Xcp_Master_Byte3 : 8;
  vbittype Xcp_Master_Byte4 : 8;
  vbittype Xcp_Master_Byte5 : 8;
  vbittype Xcp_Master_Byte6 : 8;
  vbittype Xcp_Master_Byte7 : 8;
} _c_Xcp_Master_Msg_RDS_msgType;

typedef struct _c_Wheel_Pulses_HS_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlPlsPerRevDrvn_0 : 7;
  vbittype unused1 : 1;
  vbittype WhlPlsPerRevNonDrvn_0 : 7;
  vbittype unused2 : 5;
  vbittype WhlRotStatTmstmpRes_1 : 3;
  vbittype WhlRotStatTmstmpRes_0 : 8;
} _c_Wheel_Pulses_HS_RDS_msgType;

typedef struct _c_PPEI_Engine_General_Status_4_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype EngCltTmpV : 1;
  vbittype unused1 : 6;
  vbittype unused2 : 8;
  vbittype EngCltTmp : 8;
} _c_PPEI_Engine_General_Status_4_RDS_msgType;

typedef struct _c_PPEI_Platform_Eng_Cntrl_Requests_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 4;
  vbittype EngOffTmVDA : 1;
  vbittype EngOffTmExtRngV : 1;
  vbittype unused4 : 2;
  vbittype EngOffTmExtRng : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 4;
  vbittype OtsAirTmpCrValMsk : 1;
  vbittype unused7 : 2;
  vbittype OtsAirTmpCrValV : 1;
  vbittype OtsAirTmpCrVal : 8;
} _c_PPEI_Platform_Eng_Cntrl_Requests_RDS_msgType;

typedef struct _c_PPEI_Vehicle_Speed_and_Distance_RDS_msgTypeTag
{
  vbittype VehSpdAvgDrvnV_0 : 1;
  vbittype VehSpdAvgDrvn_0_1 : 7;
  vbittype VehSpdAvgDrvn_0_0 : 8;
  vbittype VehSpdAvgDrvnSrc_0 : 1;
  vbittype DistRollCntAvgDrvnV : 1;
  vbittype DstRolCntAvgDrnRstOc : 1;
  vbittype DistRollCntAvgDrvn_1 : 5;
  vbittype DistRollCntAvgDrvn_0 : 8;
  vbittype VehSpdAvgNDrvnV : 1;
  vbittype VehSpdAvgNDrvn_1 : 7;
  vbittype VehSpdAvgNDrvn_0 : 8;
  vbittype DistRollCntAvgDrvnSrc : 1;
  vbittype DstRolCntAvgNonDrvnV : 1;
  vbittype DstRolCntAvNDrRstOc : 1;
  vbittype DstRolCntAvgNonDrvn_1 : 5;
  vbittype DstRolCntAvgNonDrvn_0 : 8;
} _c_PPEI_Vehicle_Speed_and_Distance_RDS_msgType;

typedef struct _c_NonDriven_Wheel_Grnd_Velocity_HS_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftNnDrvnV_0 : 1;
  vbittype WhlGrndVlctyLftNnDrvn_0_1 : 6;
  vbittype WhlGrndVlctyLftNnDrvn_0_0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtNnDrvnV_0 : 1;
  vbittype WhlGrndVlctyRtNnDrvn_0_1 : 6;
  vbittype WhlGrndVlctyRtNnDrvn_0_0 : 8;
  vbittype unused2 : 2;
  vbittype WhlRotDrctnlStLfNDrvn : 3;
  vbittype WhlRotDrctnlSRtNDrvn : 3;
} _c_NonDriven_Wheel_Grnd_Velocity_HS_RDS_msgType;

typedef struct _c_Driven_Wheel_Grnd_Velocity_HS_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftDrvnV_0 : 1;
  vbittype WhlGrndVlctyLftDrvn_0_1 : 6;
  vbittype WhlGrndVlctyLftDrvn_0_0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtDrvnV_0 : 1;
  vbittype WhlGrndVlctyRtDrvn_0_1 : 6;
  vbittype WhlGrndVlctyRtDrvn_0_0 : 8;
  vbittype unused2 : 2;
  vbittype WhlRotDrctnlStLftDrvn : 3;
  vbittype WhlRotDrctnlStRtDrvn : 3;
} _c_Driven_Wheel_Grnd_Velocity_HS_RDS_msgType;

typedef struct _c_USDT_Req_to_EHPS_EPS_HS_RDS_msgTypeTag
{
  vbittype DgnInf_0_7 : 8;
  vbittype DgnInf_0_6 : 8;
  vbittype DgnInf_0_5 : 8;
  vbittype DgnInf_0_4 : 8;
  vbittype DgnInf_0_3 : 8;
  vbittype DgnInf_0_2 : 8;
  vbittype DgnInf_0_1 : 8;
  vbittype DgnInf_0_0 : 8;
} _c_USDT_Req_to_EHPS_EPS_HS_RDS_msgType;

typedef struct _c_Driving_Mode_Control_HS_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 2;
  vbittype StgSysPerfMdRq : 3;
  vbittype unused4 : 3;
  vbittype DrvMdCntrlState : 8;
} _c_Driving_Mode_Control_HS_RDS_msgType;

typedef struct _c_Brake_Pedal_Driver_Status_HS_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 6;
  vbittype AutoBrkngAvlbl : 1;
  vbittype unused3 : 1;
  vbittype unused4 : 8;
  vbittype RedntVSEAct : 1;
  vbittype RedntVSEActARC : 2;
  vbittype unused5 : 5;
  vbittype unused6 : 1;
  vbittype ABSActvProt : 1;
  vbittype ABSActvProtARC : 2;
  vbittype ABSActvProtPVal : 2;
  vbittype unused7 : 2;
} _c_Brake_Pedal_Driver_Status_HS_RDS_msgType;

typedef struct _c_PPEI_Trans_General_Status_2_RDS_msgTypeTag
{
  vbittype unused0 : 3;
  vbittype TransEstGearV : 1;
  vbittype TransEstGear : 4;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 3;
  vbittype TrnsShftLvrPosV : 1;
  vbittype TrnsShftLvrPos : 4;
  vbittype unused4 : 8;
  vbittype unused5 : 3;
  vbittype TrnShftPtrnActStat : 3;
  vbittype unused6 : 2;
} _c_PPEI_Trans_General_Status_2_RDS_msgType;

typedef struct _c_PPEI_Platform_General_Status_RDS_msgTypeTag
{
  vbittype BkupPwrModeMstrVDA : 1;
  vbittype SysBkupPwrMdEn : 1;
  vbittype SysBkUpPwrMd : 2;
  vbittype unused0 : 2;
  vbittype SysPwrMd : 2;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 5;
  vbittype TrStLgMdAtv : 1;
  vbittype unused5 : 2;
} _c_PPEI_Platform_General_Status_RDS_msgType;

typedef struct _c_PPEI_Chassis_General_Status_1_RDS_msgTypeTag
{
  vbittype BrkPdlDrvAppPrsDetcdV : 1;
  vbittype BrkPdlDrvAppPrsDetcd : 1;
  vbittype unused0 : 1;
  vbittype VSELatAccV : 1;
  vbittype VSELatAcc_1 : 4;
  vbittype VSELatAcc_0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 1;
  vbittype ABSAtv_0 : 1;
  vbittype ABSFld : 1;
  vbittype TCSysAtv : 1;
  vbittype TCSysEnbld : 1;
  vbittype TracCntrlSysDrIntnt : 1;
  vbittype unused3 : 1;
  vbittype VSEAct_0 : 1;
  vbittype VhDynCntlSysSt : 3;
  vbittype VehDynYawRateV : 1;
  vbittype VehDynYawRate_1 : 4;
  vbittype VehDynYawRate_0 : 8;
  vbittype unused4 : 5;
  vbittype VehDynOvrUndrStrV_0 : 1;
  vbittype VehDynOvrUndrStr_0_1 : 2;
  vbittype VehDynOvrUndrStr_0_0 : 8;
} _c_PPEI_Chassis_General_Status_1_RDS_msgType;

typedef struct _c_LKA_Steering_Torque_Cmd_HS_RDS_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype LKATqOvrDltCmdRC : 2;
  vbittype LKATODC_TrqRqAct : 1;
  vbittype LKATODC_TrqVl_1 : 3;
  vbittype LKATODC_TrqVl_0 : 8;
  vbittype unused1 : 4;
  vbittype LKATqOvrDltCmdPrtVl_1 : 4;
  vbittype LKATqOvrDltCmdPrtVl_0 : 8;
} _c_LKA_Steering_Torque_Cmd_HS_RDS_msgType;

typedef struct _c_Antilock_Brake_and_TC_Status_HS_RDS_msgTypeTag
{
  vbittype TCSysOpMd : 3;
  vbittype VehStabEnhmntStat_0 : 3;
  vbittype unused0 : 2;
} _c_Antilock_Brake_and_TC_Status_HS_RDS_msgType;

typedef struct _c_USDT_Req_to_All_HS_ECUs_RDS_msgTypeTag
{
  vbittype DgnInf_0_7 : 8;
  vbittype DgnInf_0_6 : 8;
  vbittype DgnInf_0_5 : 8;
  vbittype DgnInf_0_4 : 8;
  vbittype DgnInf_0_3 : 8;
  vbittype DgnInf_0_2 : 8;
  vbittype DgnInf_0_1 : 8;
  vbittype DgnInf_0_0 : 8;
} _c_USDT_Req_to_All_HS_ECUs_RDS_msgType;

typedef struct _c_PPEI_Hybrid_General_Status_3_HS_RDS_msgTypeTag
{
  vbittype ActAxleTrqV : 1;
  vbittype ActAxleTrq_1 : 7;
  vbittype ActAxleTrq_0 : 8;
} _c_PPEI_Hybrid_General_Status_3_HS_RDS_msgType;

typedef struct _c_PPEI_Engine_General_Status_1_RDS_msgTypeTag
{
  vbittype EngRunAtv : 1;
  vbittype PT_CrnkAct : 1;
  vbittype unused0 : 4;
  vbittype EngSpdStat : 2;
  vbittype EngSpd_1 : 8;
  vbittype EngSpd_0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 2;
  vbittype Eng12vStrtrMtrCmmdOn : 1;
  vbittype unused5 : 5;
} _c_PPEI_Engine_General_Status_1_RDS_msgType;

typedef struct _c_PPEI_Driven_Whl_Rotational_Stat_RDS_msgTypeTag
{
  vbittype WRSLDWhlDisTpRC : 2;
  vbittype WRSLDSeqNum : 2;
  vbittype WRSLDWhlRotStatRst : 1;
  vbittype WRSLDWhlDistVal : 1;
  vbittype WRSLDWhlDistPlsCntr_1 : 2;
  vbittype WRSLDWhlDistPlsCntr_0 : 8;
  vbittype WRSLDWhlDistTmstm_1 : 8;
  vbittype WRSLDWhlDistTmstm_0 : 8;
  vbittype WRSRDWhlDisTpRC : 2;
  vbittype WRSRDSeqNum : 2;
  vbittype WRSRDWhlRotStatRst : 1;
  vbittype WRSRDWhlDistVal : 1;
  vbittype WRSRDWhlDistPlsCntr_1 : 2;
  vbittype WRSRDWhlDistPlsCntr_0 : 8;
  vbittype WRSRDWhlDistTmstm_1 : 8;
  vbittype WRSRDWhlDistTmstm_0 : 8;
} _c_PPEI_Driven_Whl_Rotational_Stat_RDS_msgType;

typedef union _c_RDS0_buf_0Tag
{
  vuint8 _c[8];
  _c_Power_Steering_Information_HS_RDS_msgType Power_Steering_Information_HS;
} _c_RDS0_buf_0;
typedef union _c_RDS1_buf_0Tag
{
  vuint8 _c[8];
  _c_LKA_Steering_Trq_Overlay_Stat_HS_RDS_msgType LKA_Steering_Trq_Overlay_Stat_HS;
} _c_RDS1_buf_0;
typedef union _c_RDS2_buf_0Tag
{
  vuint8 _c[8];
  _c_PPEI_Steering_Wheel_Angle_RDS_msgType PPEI_Steering_Wheel_Angle;
} _c_RDS2_buf_0;
typedef union _c_RDS3_buf_0Tag
{
  vuint8 _c[8];
  _c_UUDT_Resp_From_EHPS_EPS_HS_RDS_msgType UUDT_Resp_From_EHPS_EPS_HS;
} _c_RDS3_buf_0;
typedef union _c_RDS4_buf_0Tag
{
  vuint8 _c[8];
  _c_USDT_Resp_From_EHPS_EPS_HS_RDS_msgType USDT_Resp_From_EHPS_EPS_HS;
} _c_RDS4_buf_0;
typedef union _c_RDS5_buf_0Tag
{
  vuint8 _c[8];
  _c_Xcp_Slave_Msg_RDS_msgType Xcp_Slave_Msg;
} _c_RDS5_buf_0;
typedef union _c_RDS6_buf_0Tag
{
  vuint8 _c[8];
  _c_DTC_Triggered_778_RDS_msgType DTC_Triggered_778;
} _c_RDS6_buf_0;
typedef union _c_RDS42_buf_0Tag
{
  vuint8 _c[8];
  _c_T1_HostToTarget_RDS_msgType T1_HostToTarget;
} _c_RDS42_buf_0;
typedef union _c_RDS43_buf_0Tag
{
  vuint8 _c[8];
  _c_Xcp_Master_Msg_RDS_msgType Xcp_Master_Msg;
} _c_RDS43_buf_0;
typedef union _c_RDS44_buf_0Tag
{
  vuint8 _c[8];
  _c_Wheel_Pulses_HS_RDS_msgType Wheel_Pulses_HS;
} _c_RDS44_buf_0;
typedef union _c_RDS45_buf_0Tag
{
  vuint8 _c[8];
  _c_PPEI_Engine_General_Status_4_RDS_msgType PPEI_Engine_General_Status_4;
} _c_RDS45_buf_0;
typedef union _c_RDS46_buf_0Tag
{
  vuint8 _c[8];
  _c_PPEI_Platform_Eng_Cntrl_Requests_RDS_msgType PPEI_Platform_Eng_Cntrl_Requests;
} _c_RDS46_buf_0;
typedef union _c_RDS47_buf_0Tag
{
  vuint8 _c[8];
  _c_PPEI_Vehicle_Speed_and_Distance_RDS_msgType PPEI_Vehicle_Speed_and_Distance;
} _c_RDS47_buf_0;
typedef union _c_RDS48_buf_0Tag
{
  vuint8 _c[8];
  _c_NonDriven_Wheel_Grnd_Velocity_HS_RDS_msgType NonDriven_Wheel_Grnd_Velocity_HS;
} _c_RDS48_buf_0;
typedef union _c_RDS49_buf_0Tag
{
  vuint8 _c[8];
  _c_Driven_Wheel_Grnd_Velocity_HS_RDS_msgType Driven_Wheel_Grnd_Velocity_HS;
} _c_RDS49_buf_0;
typedef union _c_RDS50_buf_0Tag
{
  vuint8 _c[8];
  _c_USDT_Req_to_EHPS_EPS_HS_RDS_msgType USDT_Req_to_EHPS_EPS_HS;
} _c_RDS50_buf_0;
typedef union _c_RDS51_buf_0Tag
{
  vuint8 _c[8];
  _c_Driving_Mode_Control_HS_RDS_msgType Driving_Mode_Control_HS;
} _c_RDS51_buf_0;
typedef union _c_RDS52_buf_0Tag
{
  vuint8 _c[8];
  _c_Brake_Pedal_Driver_Status_HS_RDS_msgType Brake_Pedal_Driver_Status_HS;
} _c_RDS52_buf_0;
typedef union _c_RDS53_buf_0Tag
{
  vuint8 _c[8];
  _c_PPEI_Trans_General_Status_2_RDS_msgType PPEI_Trans_General_Status_2;
} _c_RDS53_buf_0;
typedef union _c_RDS54_buf_0Tag
{
  vuint8 _c[8];
  _c_PPEI_Platform_General_Status_RDS_msgType PPEI_Platform_General_Status;
} _c_RDS54_buf_0;
typedef union _c_RDS55_buf_0Tag
{
  vuint8 _c[8];
  _c_PPEI_Chassis_General_Status_1_RDS_msgType PPEI_Chassis_General_Status_1;
} _c_RDS55_buf_0;
typedef union _c_RDS56_buf_0Tag
{
  vuint8 _c[8];
  _c_LKA_Steering_Torque_Cmd_HS_RDS_msgType LKA_Steering_Torque_Cmd_HS;
} _c_RDS56_buf_0;
typedef union _c_RDS57_buf_0Tag
{
  vuint8 _c[8];
  _c_Antilock_Brake_and_TC_Status_HS_RDS_msgType Antilock_Brake_and_TC_Status_HS;
} _c_RDS57_buf_0;
typedef union _c_RDS58_buf_0Tag
{
  vuint8 _c[8];
  _c_USDT_Req_to_All_HS_ECUs_RDS_msgType USDT_Req_to_All_HS_ECUs;
} _c_RDS58_buf_0;
typedef union _c_RDS59_buf_0Tag
{
  vuint8 _c[8];
  _c_PPEI_Hybrid_General_Status_3_HS_RDS_msgType PPEI_Hybrid_General_Status_3_HS;
} _c_RDS59_buf_0;
typedef union _c_RDS60_buf_0Tag
{
  vuint8 _c[8];
  _c_PPEI_Engine_General_Status_1_RDS_msgType PPEI_Engine_General_Status_1;
} _c_RDS60_buf_0;
typedef union _c_RDS61_buf_0Tag
{
  vuint8 _c[8];
  _c_PPEI_Driven_Whl_Rotational_Stat_RDS_msgType PPEI_Driven_Whl_Rotational_Stat;
} _c_RDS61_buf_0;


#define RDS0_0                               ((* ((_c_RDS0_buf_0 MEMORY_NORMAL *)(canRDSTxPtr[0]))))
#define RDS1_0                               ((* ((_c_RDS1_buf_0 MEMORY_NORMAL *)(canRDSTxPtr[1]))))
#define RDS2_0                               ((* ((_c_RDS2_buf_0 MEMORY_NORMAL *)(canRDSTxPtr[2]))))
#define RDS3_0                               ((* ((_c_RDS3_buf_0 MEMORY_NORMAL *)(canRDSTxPtr[3]))))
#define RDS4_0                               ((* ((_c_RDS4_buf_0 MEMORY_NORMAL *)(canRDSTxPtr[4]))))
#define RDS5_0                               ((* ((_c_RDS5_buf_0 MEMORY_NORMAL *)(canRDSTxPtr[5]))))
#define RDS6_0                               ((* ((_c_RDS6_buf_0 MEMORY_NORMAL *)(canRDSTxPtr[6]))))
#define RDS42_0                              ((* ((_c_RDS42_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS43_0                              ((* ((_c_RDS43_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS44_0                              ((* ((_c_RDS44_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS45_0                              ((* ((_c_RDS45_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS46_0                              ((* ((_c_RDS46_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS47_0                              ((* ((_c_RDS47_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS48_0                              ((* ((_c_RDS48_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS49_0                              ((* ((_c_RDS49_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS50_0                              ((* ((_c_RDS50_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS51_0                              ((* ((_c_RDS51_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS52_0                              ((* ((_c_RDS52_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS53_0                              ((* ((_c_RDS53_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS54_0                              ((* ((_c_RDS54_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS55_0                              ((* ((_c_RDS55_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS56_0                              ((* ((_c_RDS56_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS57_0                              ((* ((_c_RDS57_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS58_0                              ((* ((_c_RDS58_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS59_0                              ((* ((_c_RDS59_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS60_0                              ((* ((_c_RDS60_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))
#define RDS61_0                              ((* ((_c_RDS61_buf_0 MEMORY_NORMAL *)(canRDSRxPtr[0]))))

typedef struct _c_Steering_Torque_Overlay_Stat_CE_RDS_msgTypeTag
{
  vbittype unused0 : 3;
  vbittype TrqOvrlTrqDStat : 2;
  vbittype ElPwrStTtlTqDlrd_1 : 3;
  vbittype ElPwrStTtlTqDlrd_0 : 8;
  vbittype unused1 : 1;
  vbittype TrqOvrlDvrdARC : 4;
  vbittype unused2 : 3;
  vbittype unused3 : 8;
  vbittype unused4 : 5;
  vbittype TrqOvrlDltTrqDlrd_1 : 3;
  vbittype TrqOvrlDltTrqDlrd_0 : 8;
  vbittype unused5 : 5;
  vbittype TrqOvrlDChksm_1 : 3;
  vbittype TrqOvrlDChksm_0 : 8;
} _c_Steering_Torque_Overlay_Stat_CE_RDS_msgType;

typedef struct _c_PPEI_Steering_Wheel_Angle_CE_RDS_msgTypeTag
{
  vbittype StrWhAngV_1 : 1;
  vbittype StrWhlAngSenCalStat_1 : 2;
  vbittype StrWhlAngSenTyp_1 : 2;
  vbittype StrWhAngMsk_1 : 1;
  vbittype unused0 : 2;
  vbittype StrWhAng_1_1 : 8;
  vbittype StrWhAng_1_0 : 8;
  vbittype StrWhAngGrdV_1 : 1;
  vbittype StWhlAngAliveRollCnt_1 : 2;
  vbittype StrWhAngGrdMsk_1 : 1;
  vbittype StrWhAngGrd_1_1 : 4;
  vbittype StrWhAngGrd_1_0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 5;
  vbittype StrAngSnsChksm_1_1 : 3;
  vbittype StrAngSnsChksm_1_0 : 8;
} _c_PPEI_Steering_Wheel_Angle_CE_RDS_msgType;

typedef struct _c_Electric_Power_Steering_CE_RDS_msgTypeTag
{
  vbittype DrvStrIntfrDetPrtVal : 2;
  vbittype DrvStrIntfrDetARC : 2;
  vbittype DrvStrIntfrDtcd : 1;
  vbittype DrvStrIntfrDtcdV : 1;
  vbittype ElecPwrStrAvalStat : 2;
  vbittype unused0 : 4;
  vbittype ElcPwrStrAvalStatPVal : 2;
  vbittype ElcPwrStrAvalStatARC : 2;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
} _c_Electric_Power_Steering_CE_RDS_msgType;

typedef struct _c_UUDT_Resp_From_EPS_EPS_JR_CE_RDS_msgTypeTag
{
  vbittype DgnInf_CE542_7 : 8;
  vbittype DgnInf_CE542_6 : 8;
  vbittype DgnInf_CE542_5 : 8;
  vbittype DgnInf_CE542_4 : 8;
  vbittype DgnInf_CE542_3 : 8;
  vbittype DgnInf_CE542_2 : 8;
  vbittype DgnInf_CE542_1 : 8;
  vbittype DgnInf_CE542_0 : 8;
} _c_UUDT_Resp_From_EPS_EPS_JR_CE_RDS_msgType;

typedef struct _c_USDT_Resp_From_EPS_EPS_JR_CE_RDS_msgTypeTag
{
  vbittype DgnInf_1_7 : 8;
  vbittype DgnInf_1_6 : 8;
  vbittype DgnInf_1_5 : 8;
  vbittype DgnInf_1_4 : 8;
  vbittype DgnInf_1_3 : 8;
  vbittype DgnInf_1_2 : 8;
  vbittype DgnInf_1_1 : 8;
  vbittype DgnInf_1_0 : 8;
} _c_USDT_Resp_From_EPS_EPS_JR_CE_RDS_msgType;

typedef struct _c_NonDriven_Wheel_Grnd_Velocity_CE_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftNnDrvnV_1 : 1;
  vbittype WhlGrndVlctyLftNnDrvn_1_1 : 6;
  vbittype WhlGrndVlctyLftNnDrvn_1_0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtNnDrvnV_1 : 1;
  vbittype WhlGrndVlctyRtNnDrvn_1_1 : 6;
  vbittype WhlGrndVlctyRtNnDrvn_1_0 : 8;
  vbittype unused2 : 1;
  vbittype WhlPlsPerRevNonDrvn_1 : 7;
} _c_NonDriven_Wheel_Grnd_Velocity_CE_RDS_msgType;

typedef struct _c_Driven_Wheel_Grnd_Velocity_CE_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftDrvnV_1 : 1;
  vbittype WhlGrndVlctyLftDrvn_1_1 : 6;
  vbittype WhlGrndVlctyLftDrvn_1_0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtDrvnV_1 : 1;
  vbittype WhlGrndVlctyRtDrvn_1_1 : 6;
  vbittype WhlGrndVlctyRtDrvn_1_0 : 8;
  vbittype unused2 : 1;
  vbittype WhlPlsPerRevDrvn_1 : 7;
} _c_Driven_Wheel_Grnd_Velocity_CE_RDS_msgType;

typedef struct _c_Park_Assist_Parallel_CE_RDS_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype StrWhlTctlFdbkReqActProtVal : 2;
  vbittype StrWhlTctlFdbkReqAct : 1;
  vbittype unused1 : 1;
  vbittype StrWhlTctlFdbkReqActRC : 2;
  vbittype unused2 : 6;
  vbittype SWAR_ReqAct : 1;
  vbittype SWAR_ReqActV : 1;
  vbittype SWAR_TrgtAng_1 : 8;
  vbittype SWAR_TrgtAng_0 : 8;
  vbittype unused3 : 4;
  vbittype StrWhlAngReqARC : 2;
  vbittype StrWhlAngReqPrtVal_2 : 2;
  vbittype StrWhlAngReqPrtVal_1 : 8;
  vbittype StrWhlAngReqPrtVal_0 : 8;
} _c_Park_Assist_Parallel_CE_RDS_msgType;

typedef struct _c_USDT_Req_to_EPS_EPS_JR_CE_RDS_msgTypeTag
{
  vbittype DgnInf_1_7 : 8;
  vbittype DgnInf_1_6 : 8;
  vbittype DgnInf_1_5 : 8;
  vbittype DgnInf_1_4 : 8;
  vbittype DgnInf_1_3 : 8;
  vbittype DgnInf_1_2 : 8;
  vbittype DgnInf_1_1 : 8;
  vbittype DgnInf_1_0 : 8;
} _c_USDT_Req_to_EPS_EPS_JR_CE_RDS_msgType;

typedef struct _c_Vehicle_Dynamics_ESC_Hyb_CE_RDS_msgTypeTag
{
  vbittype unused0 : 4;
  vbittype VSELongAccLoResV : 1;
  vbittype unused1 : 2;
  vbittype VSEAct_1 : 1;
  vbittype unused2 : 3;
  vbittype VehStabEnhmntStat_1 : 3;
  vbittype VSELongAccLoRes_1 : 2;
  vbittype VSELongAccLoRes_0 : 8;
  vbittype unused3 : 5;
  vbittype VehDynOvrUndrStrV_1 : 1;
  vbittype VehDynOvrUndrStr_1_1 : 2;
  vbittype VehDynOvrUndrStr_1_0 : 8;
} _c_Vehicle_Dynamics_ESC_Hyb_CE_RDS_msgType;

typedef struct _c_Steering_Torque_Command_CE_RDS_msgTypeTag
{
  vbittype TrqOvrlARC : 4;
  vbittype TqOvrDltTqCmdAct : 1;
  vbittype TqOvrDltTqCmdVl_1 : 3;
  vbittype TqOvrDltTqCmdVl_0 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 5;
  vbittype TrqOvrlCmdChksm_1 : 3;
  vbittype TrqOvrlCmdChksm_0 : 8;
} _c_Steering_Torque_Command_CE_RDS_msgType;

typedef struct _c_USDT_Req_to_All_CE_ECUs_RDS_msgTypeTag
{
  vbittype DgnInf_1_7 : 8;
  vbittype DgnInf_1_6 : 8;
  vbittype DgnInf_1_5 : 8;
  vbittype DgnInf_1_4 : 8;
  vbittype DgnInf_1_3 : 8;
  vbittype DgnInf_1_2 : 8;
  vbittype DgnInf_1_1 : 8;
  vbittype DgnInf_1_0 : 8;
} _c_USDT_Req_to_All_CE_ECUs_RDS_msgType;

typedef union _c_RDS0_buf_1Tag
{
  vuint8 _c[8];
  _c_Steering_Torque_Overlay_Stat_CE_RDS_msgType Steering_Torque_Overlay_Stat_CE;
} _c_RDS0_buf_1;
typedef union _c_RDS1_buf_1Tag
{
  vuint8 _c[8];
  _c_PPEI_Steering_Wheel_Angle_CE_RDS_msgType PPEI_Steering_Wheel_Angle_CE;
} _c_RDS1_buf_1;
typedef union _c_RDS2_buf_1Tag
{
  vuint8 _c[8];
  _c_Electric_Power_Steering_CE_RDS_msgType Electric_Power_Steering_CE;
} _c_RDS2_buf_1;
typedef union _c_RDS3_buf_1Tag
{
  vuint8 _c[8];
  _c_UUDT_Resp_From_EPS_EPS_JR_CE_RDS_msgType UUDT_Resp_From_EPS_EPS_JR_CE;
} _c_RDS3_buf_1;
typedef union _c_RDS4_buf_1Tag
{
  vuint8 _c[8];
  _c_USDT_Resp_From_EPS_EPS_JR_CE_RDS_msgType USDT_Resp_From_EPS_EPS_JR_CE;
} _c_RDS4_buf_1;
typedef union _c_RDS55_buf_1Tag
{
  vuint8 _c[8];
  _c_NonDriven_Wheel_Grnd_Velocity_CE_RDS_msgType NonDriven_Wheel_Grnd_Velocity_CE;
} _c_RDS55_buf_1;
typedef union _c_RDS56_buf_1Tag
{
  vuint8 _c[8];
  _c_Driven_Wheel_Grnd_Velocity_CE_RDS_msgType Driven_Wheel_Grnd_Velocity_CE;
} _c_RDS56_buf_1;
typedef union _c_RDS57_buf_1Tag
{
  vuint8 _c[8];
  _c_Park_Assist_Parallel_CE_RDS_msgType Park_Assist_Parallel_CE;
} _c_RDS57_buf_1;
typedef union _c_RDS58_buf_1Tag
{
  vuint8 _c[8];
  _c_USDT_Req_to_EPS_EPS_JR_CE_RDS_msgType USDT_Req_to_EPS_EPS_JR_CE;
} _c_RDS58_buf_1;
typedef union _c_RDS59_buf_1Tag
{
  vuint8 _c[8];
  _c_Vehicle_Dynamics_ESC_Hyb_CE_RDS_msgType Vehicle_Dynamics_ESC_Hyb_CE;
} _c_RDS59_buf_1;
typedef union _c_RDS60_buf_1Tag
{
  vuint8 _c[8];
  _c_Steering_Torque_Command_CE_RDS_msgType Steering_Torque_Command_CE;
} _c_RDS60_buf_1;
typedef union _c_RDS61_buf_1Tag
{
  vuint8 _c[8];
  _c_USDT_Req_to_All_CE_ECUs_RDS_msgType USDT_Req_to_All_CE_ECUs;
} _c_RDS61_buf_1;


#define RDS0_1                               ((* ((_c_RDS0_buf_1 MEMORY_NORMAL *)(canRDSTxPtr[9]))))
#define RDS1_1                               ((* ((_c_RDS1_buf_1 MEMORY_NORMAL *)(canRDSTxPtr[10]))))
#define RDS2_1                               ((* ((_c_RDS2_buf_1 MEMORY_NORMAL *)(canRDSTxPtr[11]))))
#define RDS3_1                               ((* ((_c_RDS3_buf_1 MEMORY_NORMAL *)(canRDSTxPtr[12]))))
#define RDS4_1                               ((* ((_c_RDS4_buf_1 MEMORY_NORMAL *)(canRDSTxPtr[13]))))
#define RDS55_1                              ((* ((_c_RDS55_buf_1 MEMORY_NORMAL *)(canRDSRxPtr[1]))))
#define RDS56_1                              ((* ((_c_RDS56_buf_1 MEMORY_NORMAL *)(canRDSRxPtr[1]))))
#define RDS57_1                              ((* ((_c_RDS57_buf_1 MEMORY_NORMAL *)(canRDSRxPtr[1]))))
#define RDS58_1                              ((* ((_c_RDS58_buf_1 MEMORY_NORMAL *)(canRDSRxPtr[1]))))
#define RDS59_1                              ((* ((_c_RDS59_buf_1 MEMORY_NORMAL *)(canRDSRxPtr[1]))))
#define RDS60_1                              ((* ((_c_RDS60_buf_1 MEMORY_NORMAL *)(canRDSRxPtr[1]))))
#define RDS61_1                              ((* ((_c_RDS61_buf_1 MEMORY_NORMAL *)(canRDSRxPtr[1]))))



/* -----------------------------------------------------------------------------
    &&&~ Message Hardware Objects
 ----------------------------------------------------------------------------- */

#define CanTxPower_Steering_Information_HS_HW_OBJ 0
#define CanTxPower_Steering_Information_HS_HW_CHANNEL 0
#define CanTxLKA_Steering_Trq_Overlay_Stat_HS_HW_OBJ 1
#define CanTxLKA_Steering_Trq_Overlay_Stat_HS_HW_CHANNEL 0
#define CanTxPPEI_Steering_Wheel_Angle_HW_OBJ 2
#define CanTxPPEI_Steering_Wheel_Angle_HW_CHANNEL 0
#define CanTxUUDT_Resp_From_EHPS_EPS_HS_HW_OBJ 3
#define CanTxUUDT_Resp_From_EHPS_EPS_HS_HW_CHANNEL 0
#define CanTxUSDT_Resp_From_EHPS_EPS_HS_HW_OBJ 4
#define CanTxUSDT_Resp_From_EHPS_EPS_HS_HW_CHANNEL 0
#define CanTxXcp_Slave_Msg_HW_OBJ            5
#define CanTxXcp_Slave_Msg_HW_CHANNEL        0
#define CanTxDTC_Triggered_778_HW_OBJ        6
#define CanTxDTC_Triggered_778_HW_CHANNEL    0
#define C_TX_NORMAL_0_HW_OBJ                 7
#define C_TX_NORMAL_0_HW_CHANNEL             0
#define C_TX_LL_0_HW_OBJ                     8
#define C_TX_LL_0_HW_CHANNEL                 0
#define CanRxT1_HostToTarget_HW_OBJ          42
#define CanRxT1_HostToTarget_HW_CHANNEL      0
#define CanRxXcp_Master_Msg_HW_OBJ           43
#define CanRxXcp_Master_Msg_HW_CHANNEL       0
#define CanRxWheel_Pulses_HS_HW_OBJ          44
#define CanRxWheel_Pulses_HS_HW_CHANNEL      0
#define CanRxPPEI_Engine_General_Status_4_HW_OBJ 45
#define CanRxPPEI_Engine_General_Status_4_HW_CHANNEL 0
#define CanRxPPEI_Platform_Eng_Cntrl_Requests_HW_OBJ 46
#define CanRxPPEI_Platform_Eng_Cntrl_Requests_HW_CHANNEL 0
#define CanRxPPEI_Vehicle_Speed_and_Distance_HW_OBJ 47
#define CanRxPPEI_Vehicle_Speed_and_Distance_HW_CHANNEL 0
#define CanRxNonDriven_Wheel_Grnd_Velocity_HS_HW_OBJ 48
#define CanRxNonDriven_Wheel_Grnd_Velocity_HS_HW_CHANNEL 0
#define CanRxDriven_Wheel_Grnd_Velocity_HS_HW_OBJ 49
#define CanRxDriven_Wheel_Grnd_Velocity_HS_HW_CHANNEL 0
#define CanRxUSDT_Req_to_EHPS_EPS_HS_HW_OBJ  50
#define CanRxUSDT_Req_to_EHPS_EPS_HS_HW_CHANNEL 0
#define CanRxDriving_Mode_Control_HS_HW_OBJ  51
#define CanRxDriving_Mode_Control_HS_HW_CHANNEL 0
#define CanRxBrake_Pedal_Driver_Status_HS_HW_OBJ 52
#define CanRxBrake_Pedal_Driver_Status_HS_HW_CHANNEL 0
#define CanRxPPEI_Trans_General_Status_2_HW_OBJ 53
#define CanRxPPEI_Trans_General_Status_2_HW_CHANNEL 0
#define CanRxPPEI_Platform_General_Status_HW_OBJ 54
#define CanRxPPEI_Platform_General_Status_HW_CHANNEL 0
#define CanRxPPEI_Chassis_General_Status_1_HW_OBJ 55
#define CanRxPPEI_Chassis_General_Status_1_HW_CHANNEL 0
#define CanRxLKA_Steering_Torque_Cmd_HS_HW_OBJ 56
#define CanRxLKA_Steering_Torque_Cmd_HS_HW_CHANNEL 0
#define CanRxAntilock_Brake_and_TC_Status_HS_HW_OBJ 57
#define CanRxAntilock_Brake_and_TC_Status_HS_HW_CHANNEL 0
#define CanRxUSDT_Req_to_All_HS_ECUs_HW_OBJ  58
#define CanRxUSDT_Req_to_All_HS_ECUs_HW_CHANNEL 0
#define CanRxPPEI_Hybrid_General_Status_3_HS_HW_OBJ 59
#define CanRxPPEI_Hybrid_General_Status_3_HS_HW_CHANNEL 0
#define CanRxPPEI_Engine_General_Status_1_HW_OBJ 60
#define CanRxPPEI_Engine_General_Status_1_HW_CHANNEL 0
#define CanRxPPEI_Driven_Whl_Rotational_Stat_HW_OBJ 61
#define CanRxPPEI_Driven_Whl_Rotational_Stat_HW_CHANNEL 0
#define C_BASIC0_0_HW_OBJ                    62
#define C_BASIC0_0_HW_CHANNEL                0

#define CanTxSteering_Torque_Overlay_Stat_CE_HW_OBJ 0
#define CanTxSteering_Torque_Overlay_Stat_CE_HW_CHANNEL 1
#define CanTxPPEI_Steering_Wheel_Angle_CE_HW_OBJ 1
#define CanTxPPEI_Steering_Wheel_Angle_CE_HW_CHANNEL 1
#define CanTxElectric_Power_Steering_CE_HW_OBJ 2
#define CanTxElectric_Power_Steering_CE_HW_CHANNEL 1
#define CanTxUUDT_Resp_From_EPS_EPS_JR_CE_HW_OBJ 3
#define CanTxUUDT_Resp_From_EPS_EPS_JR_CE_HW_CHANNEL 1
#define CanTxUSDT_Resp_From_EPS_EPS_JR_CE_HW_OBJ 4
#define CanTxUSDT_Resp_From_EPS_EPS_JR_CE_HW_CHANNEL 1
#define C_TX_NORMAL_1_HW_OBJ                 5
#define C_TX_NORMAL_1_HW_CHANNEL             1
#define C_TX_LL_1_HW_OBJ                     6
#define C_TX_LL_1_HW_CHANNEL                 1
#define CanRxNonDriven_Wheel_Grnd_Velocity_CE_HW_OBJ 55
#define CanRxNonDriven_Wheel_Grnd_Velocity_CE_HW_CHANNEL 1
#define CanRxDriven_Wheel_Grnd_Velocity_CE_HW_OBJ 56
#define CanRxDriven_Wheel_Grnd_Velocity_CE_HW_CHANNEL 1
#define CanRxPark_Assist_Parallel_CE_HW_OBJ  57
#define CanRxPark_Assist_Parallel_CE_HW_CHANNEL 1
#define CanRxUSDT_Req_to_EPS_EPS_JR_CE_HW_OBJ 58
#define CanRxUSDT_Req_to_EPS_EPS_JR_CE_HW_CHANNEL 1
#define CanRxVehicle_Dynamics_ESC_Hyb_CE_HW_OBJ 59
#define CanRxVehicle_Dynamics_ESC_Hyb_CE_HW_CHANNEL 1
#define CanRxSteering_Torque_Command_CE_HW_OBJ 60
#define CanRxSteering_Torque_Command_CE_HW_CHANNEL 1
#define CanRxUSDT_Req_to_All_CE_ECUs_HW_OBJ  61
#define CanRxUSDT_Req_to_All_CE_ECUs_HW_CHANNEL 1
#define C_BASIC0_1_HW_OBJ                    62
#define C_BASIC0_1_HW_CHANNEL                1





/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 133574485
      #error "The magic number of the generated file <C:\Synergy\GM_C1XX_EPS_TMS570-dzxvzg\GM_C1XX_EPS_TMS570\SwProject\Source\_GenData\can_par.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 133574485
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __CAN_PAR_H__ */
