/* -----------------------------------------------------------------------------
  Filename:    Dem_Lcfg.c
  Description: Toolversion: 12.00.01.01.11.00.60.01.00.00
               
               Serial Number: CBD1110060
               Customer Info: Nxtr GM MSR_SLP3_BSW_RTE_wGMLAN TexasInstruments TMS570 Texas Instruments tbd
               
               
               Generator Fwk   : GENy 
               Generator Module: Dem
               
               Configuration   : C:\02_EA3Int\9Bxx\Wip_fz9hxm\GM_9BXX_EPS_TMS570\Tools\AsrProject\Config\DEM\gmHS_AFS_HS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2017-03-21  00:24:07
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Diag_AsrDemLinktimeCRC */
/* configuration, interrupt handling implementations differ from the 
 * source identification define used here. The naming 
 * schemes for those files can be taken from this list: 
 * 
 * Dem.c:         DEM_SOURCE
 * Dem_Lcfg.c:    DEM_LCFG_SOURCE
 * Dem_PBcfg.c:   DEM_PBCFG_SOURCE */
#define DEM_LCFG_SOURCE
#include "Dem.h"
#include "Dem_Lcfg.h"
#include "Dem_PBcfg.h"
#include "NvM.h"
/* DEM used without RTE */
#include "Dem_Cbk.h"
/* END of Checksum exclude for
  - Diag_AsrDemLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Version Check
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Diag_AsrDemLinktimeCRC */
#if (DIAG_ASRDEM_GENTOOL_GENY_MAJOR_VERSION != 0x03)
#error "Dem_Lcfg.c : Incompatible DIAG_ASRDEM_GENTOOL_GENY_MAJOR_VERSION in generated File!"
#endif

#if (DIAG_ASRDEM_GENTOOL_GENY_MINOR_VERSION != 0x10)
#error "Dem_Lcfg.c : Incompatible DIAG_ASRDEM_GENTOOL_GENY_MINOR_VERSION in generated File!"
#endif

#if (DIAG_ASRDEM_GENTOOL_GENY_PATCH_VERSION != 0x00)
#error "Dem_Lcfg.c : Incompatible DIAG_ASRDEM_GENTOOL_GENY_PATCH_VERSION in generated File!"
#endif

#define DEM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONSTP2CONST(uint8, DEM_APPL_CONST, DEM_CONST) Dem_LCfg_GeneratedVersion_SW_02_16_02 =  & Dem_NeedDemLibVersion_SW_02_16_xx; /* PRQA S 0850, 3408 */ /* MD_MSR_19.8, MD_DEM_8.8_3408 */
CONSTP2CONST(uint8, DEM_APPL_CONST, DEM_CONST) Dem_LCfg_GeneratedOem_DEM_Vector =  & Dem_NeedDemLibOem_DEM_Vector; /* PRQA S 0850, 3408 */ /* MD_MSR_19.8, MD_DEM_8.8_3408 */

#define DEM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


/* END of Checksum exclude for
  - Diag_AsrDemLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Dem data buffers
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Diag_AsrDemLinktimeCRC */
#define DEM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

VAR(Dem_NonVolatileDataType, DEM_APPL_DATA) Dem_NvData; /* PRQA S 0850 */ /* MD_MSR_19.8 */
VAR(uint8, DEM_APPL_DATA) Dem_PreFFBuffer[DEM_PRESTORE_FF_BUFFER_SIZE]; /* PRQA S 0850 */ /* MD_MSR_19.8 */

#define DEM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define DEM_START_SEC_VAR_FAST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

VAR(Dem_DtcInternalStatusType, DEM_VAR_NOINIT_FAST) Dem_DtcInternalStatus[DEM_NUMBER_OF_EVENTS+1]; /* PRQA S 0850 */ /* MD_MSR_19.8 */

#define DEM_STOP_SEC_VAR_FAST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define DEM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

VAR(Dem_OperationCycleStateType, DEM_VAR_NOINIT) Dem_OperationCycleState[DEM_NUMBER_OF_OPERATION_CYCLES]; /* PRQA S 0850 */ /* MD_MSR_19.8 */
#define DEM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



#define DEM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

VAR(Dem_EventIdType, DEM_VAR_NOINIT) Dem_IndicatorCounter[DEM_NUMBER_OF_INDICATORS][2]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
#define DEM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



#define DEM_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

VAR(uint32, DEM_VAR_NOINIT) Dem_EnableConditionState; /* PRQA S 0850 */ /* MD_MSR_19.8 */
VAR(Dem_AQElementType, DEM_VAR_NOINIT) Dem_ActionQueue[DEM_BSW_ERROR_BUFFER_SIZE + DEM_ADD_ERROR_BUFFER_SIZE]; /* PRQA S 0850 */ /* MD_MSR_19.8 */

#define DEM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


/* END of Checksum include for
  - Diag_AsrDemLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Linktime specific config data tables
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Diag_AsrDemLinktimeCRC */
#define DEM_START_SEC_CONST_LCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(Dem_DemConfigurationType, DEM_CONST) Dem_DemConfiguration = 
{
  1
}; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint8, DEM_CONST) Dem_LinkTimeProperty[] = 
{
  0, 4, 4, 4, 4, 4, 3, 4, 3, 4, 4, 4, 3, 4, 3, 3, 
  3, 6, 2, 2, 1, 2, 2, 2, 5, 5, 5, 1, 5, 2, 2, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
CONST(uint8, DEM_CONST) Dem_InitMonitorIndexTable[] = 
{
  0, 0, 0, 0, 0, 0, 0
};
CONST(Dem_InitMonitorFPtrType, DEM_CONST) Dem_InitMonitorFPtrTable[] = 
{
  NULL_PTR
};
CONST(Dem_TriggerDTCFunctionType, DEM_CONST) Dem_TriggerDTCFunctionTable[] = 
{
  NULL_PTR
};
CONST(Dem_TriggerFunctionType, DEM_CONST) Dem_TriggerFunctionTable[] = 
{
  NULL_PTR
};
CONST(uint8, DEM_CONST) Dem_IndicatorCountTable[] = 
{
  0, 1, 1, 1, 0, 0, 1
};
CONST(uint8, DEM_CONST) Dem_IndicatorIndexTable[] = 
{
  0, 0, 1, 1, 0, 0, 2
};
CONST(Dem_IndicatorIdType, DEM_CONST) Dem_IndicatorIdTable[] = 
{
  Dem_Steering_Reduced_Assist, Dem_Warning_Indicator, Dem_Steering_Reduced_Assist_Level2
};
CONST(Dem_IndicatorStatusType, DEM_CONST) Dem_IndicatorStatusTable[] = 
{
  DEM_INDICATOR_CONTINUOUS, DEM_INDICATOR_CONTINUOUS, DEM_INDICATOR_CONTINUOUS
};
CONST(Dem_DTCGroupKindType, DEM_CONST) Dem_EventGroupTable[] = 
{
  0, 4, 4, 16, 16, 4, 4
};
CONST(Dem_DIDLookupTableType, DEM_CONST) Dem_DIDLookupTable[] = 
{
  
  {
    0x4016u, Appl_Dem_CBValByDID_4016
  }, 
  {
    0x401Bu, Appl_Dem_CBValByDID_401B
  }, 
  {
    0x4074u, Appl_Dem_CBValByDID_4074
  }, 
  {
    0x40ACu, Appl_Dem_CBValByDID_40AC
  }, 
  {
    0x40ADu, Appl_Dem_CBValByDID_40AD
  }, 
  {
    0x40BCu, Appl_Dem_CBValByDID_40BC
  }, 
  {
    0x40BDu, Appl_Dem_CBValByDID_40BD
  }, 
  {
    0x41D3u, Appl_Dem_CBValByDID_41D3
  }, 
  {
    0x41D4u, Appl_Dem_CBValByDID_41D4
  }, 
  {
    0x41D5u, Appl_Dem_CBValByDID_41D5
  }, 
  {
    0x41D6u, Appl_Dem_CBValByDID_41D6
  }, 
  {
    0x41D7u, Appl_Dem_CBValByDID_41D7
  }, 
  {
    0x41D9u, Appl_Dem_CBValByDID_41D9
  }, 
  {
    0x43D0u, Appl_Dem_CBValByDID_43D0
  }, 
  {
    0x446Fu, Appl_Dem_CBValByDID_446F
  }, 
  {
    0x8002u, Appl_Dem_CBValByDID_8002
  }, 
  
  {
    0x8078u, Appl_Dem_CBValByDID_8078
  }, 
  {
    0xC000u, Appl_Dem_CBValByDID_C000
  }, 
  {
    0xC050u, Appl_Dem_CBValByDID_C050
  }, 
  {
    0xFFFFu, NULL_PTR
  }
};
CONST(Dem_GetExtDataRecordFPtrType, DEM_CONST) Dem_GetExtDataRecordListTable[] = 
{
  NULL_PTR
};
CONST(Dem_NvMBlockIdType, DEM_CONST) Dem_NvramBlockIdTable[] = 
{
  NvM_NVM_BLOCK_DEM
};
CONST(Dem_DTCGroupMappingType, DEM_CONST) Dem_DTCGroupTable[] = 
{
  
  {
    DEM_DTC_GROUPKIND_POWERTRAIN, DEM_DTC_GROUP_POWERTRAIN_DTCS
  }, 
  
  {
    DEM_DTC_GROUPKIND_CHASSIS, DEM_DTC_GROUP_CHASSIS_DTCS
  }, 
  
  {
    DEM_DTC_GROUPKIND_BODY, DEM_DTC_GROUP_BODY_DTCS
  }, 
  
  {
    DEM_DTC_GROUPKIND_NETWORK_COM, DEM_DTC_GROUP_NETWORK_COM_DTCS
  }, 
  
  {
    DEM_DTC_GROUPKIND_ALL_DTCS, DEM_DTC_GROUP_ALL_DTCS
  }
};

#define DEM_STOP_SEC_CONST_LCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


/* END of Checksum include for
  - Diag_AsrDemLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Linktime specific config data values
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Diag_AsrDemLinktimeCRC */
#define DEM_START_SEC_CONST_LCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(uint8, DEM_CONST) Dem_StatusAvailabilityMask = DEM_STATUS_AVAILABILITY_MASK; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint16, DEM_CONST) Dem_MaxSizeOfSnapshotRecord = DEM_MAX_SNAPSHOT_RECORD_SIZE; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint16, DEM_CONST) Dem_MaxSizeOfExtdataRecord = DEM_MAX_EXTDATA_RECORD_SIZE; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint16, DEM_CONST) Dem_NumberOfOperationCycles = DEM_NUMBER_OF_OPERATION_CYCLES; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint16, DEM_CONST) Dem_NumberOfIndicators = DEM_NUMBER_OF_INDICATORS; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint8, DEM_CONST) Dem_NvramBlockIdCount = sizeof(Dem_NvramBlockIdTable)/sizeof(Dem_NvMBlockIdType); /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(Dem_EventIdType, DEM_CONST) Dem_MaxCountOfEventId = DEM_NUMBER_OF_EVENTS; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint16, DEM_CONST) Dem_PriMemElementSize = sizeof(Dem_NvData.primaryStack[0]); /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(Dem_DtcChronoRefType, DEM_CONST) Dem_MaxPriMemElementCount = DEM_MAX_NUMBER_EVENT_ENTRY; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint16, DEM_CONST) Dem_SizeofPreFFBuffer = DEM_PRESTORE_FF_BUFFER_SIZE; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint8, DEM_CONST) Dem_SnapshotsPerDTC = DEM_SNAPSHOTS_PER_DTC; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint8, DEM_CONST) Dem_FirstOverwritableSnapshot = DEM_FIRST_SNAPSHOT_TO_OVERWRITE; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint8, DEM_CONST) Dem_ReportErrorBufferSize = DEM_BSW_ERROR_BUFFER_SIZE; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint16, DEM_CONST) Dem_ActionQueueCount = sizeof(Dem_ActionQueue)/sizeof(Dem_AQElementType); /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint8, DEM_CONST) Dem_DTCGroupMappingCount = sizeof(Dem_DTCGroupTable)/sizeof(Dem_DTCGroupMappingType); /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONST(uint8, DEM_CONST) Dem_SizeofEventIdType = sizeof(Dem_EventIdType); /* PRQA S 0850 */ /* MD_MSR_19.8 */

CONSTP2VAR(Dem_NonVolatileDataType, DEM_CONST, DEM_APPL_DATA) Dem_NvDataPtr = &Dem_NvData; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(uint8, DEM_CONST, DEM_APPL_DATA) Dem_ConsistencyPatternPtr = &Dem_NvData.consistencyPattern[0]; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(uint8, DEM_CONST, DEM_APPL_DATA) Dem_PrimaryStackPtr = &Dem_NvData.primaryStack[0][0]; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(Dem_ChronoPriMemType, DEM_CONST, DEM_APPL_DATA) Dem_ChronoPriMemPtr = Dem_NvData.chronoPriMem; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(Dem_DtcStatusByteType, DEM_CONST, DEM_APPL_DATA) Dem_DtcStatusBytePtr = Dem_NvData.dtcStatusByte; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(Dem_DtcChronoRefType, DEM_CONST, DEM_APPL_DATA) Dem_ChronoPriMemUsedPtr =  & Dem_NvData.chronoPriMemUsed; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(sint8, DEM_CONST, DEM_APPL_DATA) Dem_FaultDetectionCounterPtr = &Dem_NvData.dtcFaultDetectionCounter[0]; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(uint8, DEM_CONST, DEM_APPL_DATA) Dem_DtcAgingCounterPtr = &Dem_NvData.dtcAgingCounter[0]; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(Dem_EventIdType, DEM_CONST, DEM_APPL_DATA) Dem_FirstFailedEventIdPtr =  & Dem_NvData.firstFailedEvent; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(Dem_EventIdType, DEM_CONST, DEM_APPL_DATA) Dem_FirstConfirmedEventIdPtr =  & Dem_NvData.firstConfirmedEvent; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(Dem_EventIdType, DEM_CONST, DEM_APPL_DATA) Dem_MostRecentFailedEventIdPtr =  & Dem_NvData.mostRecentFailedEvent; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(Dem_EventIdType, DEM_CONST, DEM_APPL_DATA) Dem_MostRecentConfmdEventIdPtr =  & Dem_NvData.mostRecentConfirmedEvent; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(uint8, DEM_CONST, DEM_VAR_NOINIT) Dem_OperationCycleStatePtr = &Dem_OperationCycleState[0]; /* PRQA S 0850 */ /* MD_MSR_19.8 */
CONSTP2VAR(uint8, DEM_CONST, DEM_APPL_DATA) Dem_TerminatingPatternPtr = &Dem_NvData.terminatingPattern[0]; /* PRQA S 0850 */ /* MD_MSR_19.8 */

#define DEM_STOP_SEC_CONST_LCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


/* END of Checksum include for
  - Diag_AsrDemLinktimeCRC */


#define DEM_START_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Access Functions to the configurable data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Diag_AsrDemLinktimeCRC */
#define DEM_FLAGTOBOOLEAN(flag)              ((boolean)(((flag) != 0) ? TRUE : FALSE)   /* PRQA S 3453 */ /* MD_DEM_19.7 */)
/* Maximum number of supported events, excluding EventId 0. Basically defines the size of Dem_EventIdType. */
FUNC(Dem_EventIdType, DEM_CODE) DemCfg_GetMaxCountOfEventId(void) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_MaxCountOfEventId;
}


/* Translation format (bitcoded): 0x01 ==  ISO15031_6, 0x02 == ISO14229_1 */
FUNC(uint8, DEM_CODE) DemCfg_GetDTCTranslationFormat(void) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_DemConfiguration.DTCTranslationFormat;
}


/* Get number of configured operation cycles */
FUNC(uint16, DEM_CODE) DemCfg_GetMaxCountOfOperationCycle(void) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_NumberOfOperationCycles;
}


/* Number of snapshots ("FirstConfirmed" + one or more "MostRecent") for each event */
FUNC(uint8, DEM_CODE) DemCfg_GetCountOfSnapshotsPerDTC(void) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_SnapshotsPerDTC;
}


/* Number of first confirmed snapshot */
FUNC(uint8, DEM_CODE) DemCfg_GetFirstOccurredRecordNr(void) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return 0x00u;
}


/* Max. required buffer for storing all snapshots of the 'largest' event */
FUNC(uint16, DEM_CODE) DemCfg_GetMaxSnapshotRecordSize(void) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_MaxSizeOfSnapshotRecord;
}


/* Count of FirstConfirmed snapshots */
FUNC(uint8, DEM_CODE) DemCfg_Get1stOverwrtSnapshotIndex(void) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_FirstOverwritableSnapshot;
}


/* Max. required buffer for storing all extended data of the 'largest' event */
FUNC(uint16, DEM_CODE) DemCfg_GetMaxExtdataRecordSize(void) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_MaxSizeOfExtdataRecord;
}


/* Number of events, that can simultanously be stored in the PrimaryMemory */
FUNC(Dem_DtcChronoRefType, DEM_CODE) DemCfg_GetMaxCountOfPriMemStack(void) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_MaxPriMemElementCount;
}


/* Find bitcoded group number (Dem_DTCGroupKindType). Result == 0 means the group number was not found. */
FUNC(Dem_DTCGroupKindType, DEM_CODE) Dem_MapGroupNumberToGroupKind(Dem_DTCType DTCGroupNumber) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  VAR(Dem_DTCGroupKindType, AUTOMATIC) returnValue = 0; /* PRQA S 0850 */ /* MD_MSR_19.8 */
  VAR(uint8, AUTOMATIC) i; /* PRQA S 0850 */ /* MD_MSR_19.8 */
  for (i=0; i < Dem_DTCGroupMappingCount; ++i)
  {
    if (DTCGroupNumber == Dem_DTCGroupTable[i].DTCnumber)
    {
      returnValue = Dem_DTCGroupTable[i].GroupKind;
      break;
    }
  }
  return returnValue;
}


/* Map EventId to DTC number (Dem_DTCType). Success iff 0 < Result 0 <= 0x00FFFFFFuL . Result == 0xFFFFFFFFuL: no DTC number available (internal event). */
FUNC(Dem_DTCType, DEM_CODE) DemCfg_GetDTCnumber(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  VAR(Dem_DTCType, AUTOMATIC) returnValue; /* PRQA S 0850 */ /* MD_MSR_19.8 */
  returnValue = (((Dem_DTCType) Dem_DTCNumberTable[EventId] << 8) | Dem_DTC_FTB_Table[EventId]);
  if ( returnValue == 0x00FFFFFFuL )
  {
    returnValue = 0xFFFFFFFFuL;
  }
  return returnValue;
}


/* Initialization value for enable conditions. Bit position corresponds to enable condition index. (Bit0 is init value for EC0) */
FUNC(uint32, DEM_CODE) DemCfg_GetEnableConditionInitValue(void) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return 0xFFFFFFFFu;
}



/* Map EventId to a InitMonitorForEvent callback function pointer. */
FUNC(Dem_InitMonitorFPtrType, DEM_CODE) DemCfg_GetInitMonitorFPtr(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_InitMonitorFPtrTable[Dem_InitMonitorIndexTable[Dem_LinkTimeProperty[EventId]]];
}


/* Map EventId to the first Index into the list of TriggerOnDTCStatusChanged callbacks. */
FUNC(Dem_TriggerOnDTCIndexType, DEM_CODE) DemCfg_GetFirstTriggerOnDTC(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to the number of corresponding TriggerOnDTCStatusChanged callbacks. */
FUNC(uint8, DEM_CODE) DemCfg_GetCountOfTriggerOnDTC(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to the first Index into the list of TriggerOnEventStatusChanged callbacks. */
FUNC(Dem_TriggerOnEventIndexType, DEM_CODE) DemCfg_GetFirstTriggerOnEvent(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to number of TriggerOnEventStatusChanged callbacks. */
FUNC(uint8, DEM_CODE) DemCfg_GetCountOfTriggerOnEvent(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to priority. */
FUNC(Dem_EventPriorityType, DEM_CODE) DemCfg_GetEventPriority(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to severity. */
FUNC(Dem_DTCSeverityType, DEM_CODE) DemCfg_GetDTCSeverity(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to its healing cycle. See Dem_Types.h for operation cycle IDs. */
FUNC(uint8, DEM_CODE) DemCfg_GetAgingCycleId(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to its operation cycle. See Dem_Types.h for healing cycle IDs. */
FUNC(uint8, DEM_CODE) DemCfg_GetOperationCycleId(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Maps EventId to <Number of Healing Cycles> - 1 */
FUNC(uint8, DEM_CODE) DemCfg_GetNumberOfAgingCycles(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_AgingCountTable[Dem_PostBuildProperty[EventId]];
}


/* Map EventId to relevant enable conditions. Set bit means enable condition must be active for the Event. */
FUNC(uint8, DEM_CODE) DemCfg_GetEnableConditionMask(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to the number of relevant indicators. */
FUNC(uint8, DEM_CODE) DemCfg_GetCountOfIndicatorIds(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_IndicatorCountTable[Dem_LinkTimeProperty[EventId]];
}


/* Map EventId to index in Dem_IndicatorIdTable and Dem_IndicatorStatusTable. */
FUNC(uint16, DEM_CODE) DemCfg_GetIndicatorIndex(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_IndicatorIndexTable[Dem_LinkTimeProperty[EventId]];
}


/* Map IndIdIdx to IndicatorId. */
FUNC(Dem_IndicatorIdType, DEM_CODE) DemCfg_GetIndicatorId(uint16 IndIdIdx) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_IndicatorIdTable[IndIdIdx];
}


/* Map IndIdIdx to indicator status. */
FUNC(Dem_IndicatorStatusType, DEM_CODE) DemCfg_GetIndicatorStatusType(uint16 IndIdIdx) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_IndicatorStatusTable[IndIdIdx];
}


/* Map IndicatorId and IndicatorBehavior to indicator counter. Only the states DEM_INDICATOR_BLINKING and DEM_INDICATOR_CONTINUOUS have their own indicator counter. */
FUNC(Dem_EventIdPtrType, DEM_CODE) DemCfg_GetIndicatorCounterPtr(Dem_IndicatorIdType IndicatorId, Dem_IndicatorStatusType IndicatorBehavior) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return (& Dem_IndicatorCounter[IndicatorId][(DEM_INDICATOR_BLINKING == IndicatorBehavior) ? 0 : 1]);
}


/* Map EventId to a ViewID. */
FUNC(Dem_ViewIdType, DEM_CODE) DemCfg_GetViewId(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 255;
}


/* Map EventId to functional unit. */
FUNC(uint8, DEM_CODE) DemCfg_GetFunctionalUnit(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to flag value. */
FUNC(boolean, DEM_CODE) DemCfg_GetDtcSupportWarningIndicator(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return DEM_FLAGTOBOOLEAN(Dem_EventFlagsTable[Dem_PostBuildProperty[EventId]] & 1);
}


/* Map EventId to flag value. */
FUNC(boolean, DEM_CODE) DemCfg_GetDtcSuppressFlag(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return FALSE;
}


/* Map EventId to flag value. */
FUNC(boolean, DEM_CODE) DemCfg_GetIsAgingAllowed(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return DEM_FLAGTOBOOLEAN(Dem_EventFlagsTable[Dem_PostBuildProperty[EventId]] & 4);
}


/* Test if EventId uses Jump-Up-to-Zero, used for counter based debouncing. */
FUNC(uint8, DEM_CODE) DemCfg_GetIsPredebJumpPreFailed(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 1;
}


/* Test if EventId uses Jump-Down-to-Zero, used for counter based debouncing. */
FUNC(uint8, DEM_CODE) DemCfg_GetIsPredebJumpPrePassed(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to CountUp step size, used for counter based debouncing. */
FUNC(uint8, DEM_CODE) DemCfg_GetPredebStepsizePreFailed(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 1;
}


/* Map EventId to CountDown step size, used for counter based debouncing. */
FUNC(uint8, DEM_CODE) DemCfg_GetPredebStepsizePrePassed(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 1;
}


/* Map EventId to DTC kind. Dem_DTCKindType is defined in dem_types.h */
FUNC(Dem_DTCKindType, DEM_CODE) DemCfg_GetDTCKind(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_DtcKindTable[Dem_PostBuildProperty[EventId]];
}


/* Map EventId to supported origin (bitcoded). Primary == 0x02, Mirror == 0x04, Permanent == 0x08, Secondary == 0x10. */
FUNC(uint8, DEM_CODE) DemCfg_GetDTCOrigin(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_EventDestinationTable[Dem_PostBuildProperty[EventId]];
}


/* Map EventId to DTC group index. Internal event == 0x00, OBD == 0x01, P == 0x02, C == 0x04, B == 0x08, U == 0x10, ALL == 0xFF */
FUNC(Dem_DTCGroupKindType, DEM_CODE) DemCfg_GetDTCGroupKind(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_EventGroupTable[Dem_LinkTimeProperty[EventId]];
}


/* Map EventId to the Index of the first DID of its snapshot records. */
FUNC(uint16, DEM_CODE) DemCfg_GetFirstSnapshot(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_EventDidIndexTable[Dem_PostBuildProperty[EventId]];
}


/* Map EventId to the total number of DIDs across all of its snapshot records. */
FUNC(uint8, DEM_CODE) DemCfg_GetCountOfSnapshotDIDs(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_EventDidCountTable[Dem_PostBuildProperty[EventId]];
}


/* Map SsRecIdx to the DID number. Get first SsRecIdx either per Event using DemCfg_GetFirstSnapshot(EventId) or per Snapshot by DemCfg_GetSnapshotRecordDIDIndex(ssRecordIndex) */
FUNC(uint16, DEM_CODE) DemCfg_GetSnapshotDID(uint16 SsRecIdx) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_DidNumberTable[SsRecIdx];
}


/* Map SsRecIdx to a list of DID numbers. Get first SsRecIdx either per Event using DemCfg_GetFirstSnapshot(EventId) or per Snapshot by DemCfg_GetSnapshotRecordDIDIndex(ssRecordIndex) */
FUNC(Dem_RecordDIDAddrType, DEM_CODE) DemCfg_GetSnapshotDIDAddr(uint16 SsRecIdx) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return  & Dem_DidNumberTable[SsRecIdx];
}


/* Map SsRecIdx to the size of the DID (in byte). Get first SsRecIdx either per Event using DemCfg_GetFirstSnapshot(EventId) or per Snapshot by DemCfg_GetSnapshotRecordDIDIndex(ssRecordIndex) */
FUNC(Dem_DataRecordSizeType, DEM_CODE) DemCfg_GetSnapshotDIDDataSize(uint16 SsRecIdx) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_DidSizeTable[SsRecIdx];
}


/* Map EventId to first Index into snapshot table. */
FUNC(uint16, DEM_CODE) DemCfg_GetFirstSnapshotRecNumber(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_SnapshotIndexTable[Dem_PostBuildProperty[EventId]];
}


/* Map EventId to number of snapshot records. */
FUNC(uint8, DEM_CODE) DemCfg_GetCountOfSnapshotRecNumbers(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_SnapshotCountTable[Dem_PostBuildProperty[EventId]];
}


/* Map ssRecordIndex to number of the snapshot record. The first valid ssRecordIndex is DemCfg_GetFirstSnapshotRecNumber(EvenId). */
FUNC(uint8, DEM_CODE) DemCfg_GetSnapshotRecordNumber(uint16 ssRecordIndex) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_SnapshotNumberTable[ssRecordIndex];
}


/* Map ssRecordIndex to the size of the snapshot record (in byte). The first valid ssRecordIndex is DemCfg_GetFirstSnapshotRecNumber(EvenId). */
FUNC(uint16, DEM_CODE) DemCfg_GetSnapshotRecordDIDsSize(uint16 ssRecordIndex) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_SnapshotSizeTable[ssRecordIndex];
}


/* Map ssRecordIndex to the number of DIDs in the snapshot record. The first valid ssRecordIndex is DemCfg_GetFirstSnapshotRecNumber(EvenId). */
FUNC(uint8, DEM_CODE) DemCfg_GetSnapshotRecordNumberOfDIDs(uint16 ssRecordIndex) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_SnapshotDidCountTable[ssRecordIndex];
}


/* Map ssRecordIndex to first Index into DID table. The first valid ssRecordIndex is DemCfg_GetFirstSnapshotRecNumber(EvenId). */
FUNC(uint16, DEM_CODE) DemCfg_GetSnapshotRecordDIDIndex(uint16 ssRecordIndex) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  return Dem_SnapshotDidIndexTable[ssRecordIndex];
}


/* Map EventId to the offset into the prestored snapshot buffer. */
FUNC(uint16, DEM_CODE) DemCfg_PrestoreFFBufStartOffset(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to size of its prestored snapshot data. */
FUNC(uint16, DEM_CODE) DemCfg_PrestoreFFBufSize(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to the end offset into the prestored snapshot buffer. */
FUNC(uint16, DEM_CODE) DemCfg_PrestoreFFBufEndOffset(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to Index of first Extended Data Record. Index is valid in Dem_Record* tables. */
FUNC(uint16, DEM_CODE) DemCfg_GetFirstExtendedRecord(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to number of Extended Data Records. */
FUNC(uint16, DEM_CODE) DemCfg_GetCountOfCurrentExtendedRecord(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map ExtRecIdx to RecordId of an Extended Data Record. (First) valid ExtRecIdx per EventId is returned by DemCfg_GetFirstExtendedRecord. */
FUNC(uint8, DEM_CODE) DemCfg_GetExtendedRecordNumber(uint16 ExtRecIdx) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(ExtRecIdx) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map ExtRecIdx to size [byte] of an Extended Data Record. (First) valid ExtRecIdx per EventId is returned by DemCfg_GetFirstExtendedRecord. */
FUNC(uint16, DEM_CODE) DemCfg_GetExtendedRecordNumberDataSize(uint16 ExtRecIdx) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(ExtRecIdx) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map ExtRecIdx to size [byte] of an Extended Data Record, in MirrorMemory. (First) valid ExtRecIdx per EventId is returned by DemCfg_GetFirstExtendedRecord. */
FUNC(uint16, DEM_CODE) DemCfg_GetMirExtendedRecordNumberDataSize(uint16 ExtRecIdx) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(ExtRecIdx) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map ExtRecIdx to function pointer used to get the data. (First) valid ExtRecIdx per EventId is returned by DemCfg_GetFirstExtendedRecord. */
FUNC(uint16, DEM_CODE) DemCfg_GetExtendedRecordFuncRef(uint16 ExtRecIdx) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(ExtRecIdx) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 0;
}


/* Map EventId to valid identity mask. Can be multiple identity (only one bit set) or VSG mode (multiple bits set). */
FUNC(uint32, DEM_CODE) DemCfg_GetEventIdentityVariant(Dem_EventIdType EventId) /* PRQA S 0850 */ /* MD_MSR_19.8 */
{
  DEM_IGNORE_UNUSED_ARG(EventId) /* PRQA S 3112 *//* MD_DEM_14.2 */;
  return 1;
}



/* END of Checksum include for
  - Diag_AsrDemLinktimeCRC */


#define DEM_STOP_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 133575247
      #error "The magic number of the generated file <C:\CMSynergy_Projects\Chrysler_C1xx\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\Dem_Lcfg.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <C:\CMSynergy_Projects\Chrysler_C1xx\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\Dem_Lcfg.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

