/* -----------------------------------------------------------------------------
  Filename:    Dem_PBcfg.h
  Description: Toolversion: 12.00.01.01.11.00.60.01.00.00
               
               Serial Number: CBD1110060
               Customer Info: Nxtr GM MSR_SLP3_BSW_RTE_wGMLAN TexasInstruments TMS570 Texas Instruments tbd
               
               
               Generator Fwk   : GENy 
               Generator Module: Dem
               
               Configuration   : C:\CMSynergy_Projects\Chrysler_C1xx\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\Config\DEM\gmHS_AFS_HS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2013-07-16  15:38:55
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(DEM_PBCFG_H)
#define DEM_PBCFG_H

/* -----------------------------------------------------------------------------
    &&&~ Dem configuration type definitions for postbuild
 ----------------------------------------------------------------------------- */

typedef struct Dem_PBConfigTypeTag
{
  uint32 Dem_PBCfgLeader;
  uint32 Dem_EnableConditionInitialState;
  uint32 Dem_PBCfgTrailer;
} Dem_PBConfigType;



/* -----------------------------------------------------------------------------
    &&&~ Global Data Prototypes
 ----------------------------------------------------------------------------- */

#define DEM_START_SEC_PBCONST_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

extern CONST(Dem_PBConfigType, DEM_PBCFG) Dem_PBConfig; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
#define DEM_STOP_SEC_PBCONST_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define DEM_START_SEC_PBCONST
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

extern CONST(uint8, DEM_PBCFG) Dem_PostBuildProperty[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint16, DEM_PBCFG) Dem_DTCNumberTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_DTC_FTB_Table[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_AgingCountTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_EventFlagsTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_DTCKindType, DEM_PBCFG) Dem_DtcKindTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_EventDestinationTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_EventDidIndexTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_EventDidCountTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint16, DEM_PBCFG) Dem_DidNumberTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_DidSizeTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotIndexTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotCountTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotNumberTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotSizeTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotDidIndexTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotDidCountTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
#define DEM_STOP_SEC_PBCONST
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"





/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 133575247
      #error "The magic number of the generated file <C:\CMSynergy_Projects\Chrysler_C1xx\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\Dem_PBcfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 133575247
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* DEM_PBCFG_H */
