/* -----------------------------------------------------------------------------
  Filename:    desc.h
  Description: Interface of CANdesc visible to any application.
                
                Manufacturer: General Motors
                EcuDocFile:   C:\02_EA3Int\9Bxx\Wip_fz9hxm\GM_9BXX_EPS_TMS570\Tools\AsrProject\GENy\EPS_5.0.3_HS_60.cdd
                Variant:      CommonDiagnostics

  Generated by CANdelaGen, Sun Jan 15 18:01:43 2017
 
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__DESC_H__)
#define __DESC_H__

/* -----------------------------------------------------------------------------
    &&&~ History
 ----------------------------------------------------------------------------- */

/* 
------------------------------------------------------------------------------------------------------------------------
                                             A U T H O R   I D E N T I T Y                                              
------------------------------------------------------------------------------------------------------------------------
Initials   Name                  Company                                                                                
---------- --------------------- ---------------------------------------------------------------------------------------
Ktw        Katrin Thurow         Vctr Informatik GmbH                                                                 
Mhe        Matthias Heil         Vctr Informatik GmbH                                                                 
Sa         Mishel Shishmanyan    Vctr Informatik GmbH                                                                 
------------------------------------------------------------------------------------------------------------------------
                                            R E V I S I O N   H I S T O R Y                                             
------------------------------------------------------------------------------------------------------------------------
Date       Version  Author Modification type Issue Id      Affects                        Description                    
---------- -------- ------ ----------------- ------------- ------------------------------ -------------------------------
2006-10-20 05.00.00
                    Sa     Added             ESCAN00017897 General Motors(KWP2000)        Add support for Gateway target address $FD.
                    Sa     Added             ESCAN00018584 General Motors(KWP2000)        Allow support of DIDs with dynamic data length for service $22.
                    Sa     Modified          ESCAN00018098 All                            Unified security access management and API.
                    Sa     Added             ESCAN00017752 All                            OBD II compliance with regard to the NRC usage and response behavior.
                    Sa     Added             ESCAN00018099 All                            Add support for CANdela format 5.0.
2007-02-16 05.01.00
                    Sa     Fixed             ESCAN00018234 General Motors(KWP2000)        Scheduler initialization overwrites memory.
                    Sa     Fixed             ESCAN00018229 General Motors(KWP2000)        CANdesc does not support far CAN controller memory pointer.
                    Sa     Fixed             ESCAN00018287 General Motors(KWP2000)        UUDT responses are sent on wrong physical CAN channel if CANdesc runs on more than one CAN channel.
                    Sa     Fixed             ESCAN00019154 General Motors(KWP2000)        Wrong processing of service $22 with active permanent multi-service-call option.
                    Sa     Fixed             ESCAN00018730 General Motors(KWP2000)        CANdesc accepts diagnostic requests which are functionally addressed to the 'Diagnostic address'
                    Sa     Fixed             ESCAN00019274 General Motors(KWP2000)        Service $A9 $81 sends only one UUDT response.
                    Sa     Fixed             ESCAN00019168 General Motors(KWP2000)        Generator: Crashes on invalid $2C-$22 configuration.
                    Sa     Modified          ESCAN00018290 General Motors(KWP2000)        Compiler warnings for only declared static functions: DescIterInitDynDefinePid and DescProcessDynamicallyDefineDid
                    Sa     Modified          ESCAN00018334 General Motors(KWP2000)        Use for the UUDT transmitter instead of vuint8* TxDataPtr data type.
                    Sa     Modified          ESCAN00018917 General Motors(KWP2000)        Removed warning for unreferenced API declaration of DescUudtNetCANCancelAllResponses.
                    Sa     Modified          ESCAN00019161 General Motors(KWP2000)        Set the maximum number of references for a DynDPID to be 7.
                    Sa     Fixed             ESCAN00018294 KWP2000                        Compiler error if no state-machine is defined in CDD file.
                    Sa     Fixed             ESCAN00018210 KWP2000                        Wrong negative response code associated with the use-case "SequenceError".
                    Sa     Fixed             ESCAN00018576 All                            Service instance linear look-up routine fails finding a requested service.
                    Sa     Fixed             ESCAN00019220 All                            Compile error for wrong syntax after preprocesing defines: DescUsdtNetStateTask and DescUsdtNetTimerTask.
                    Sa     Fixed             ESCAN00019334 All                            Generator: Unable to generate CANdesc with multi channel TP and CANgen newer than 4.30.03.
                    Sa     Modified          ESCAN00018872 All                            Wrong main-handler comment for constants names kDescReqTypePhys (-Func).
                    Sa     Modified          ESCAN00019321 All                            Remove file-path from the #include "node.h"
                    Sa     Modified          ESCAN00019735 All                            Use CPU type optimized data definition types (uintx_least).
                    Sa     Added             ESCAN00018320 All                            Generate P2 and P2* task-call constants with a justification of one task call less.
                    Sa     Added             ESCAN00018592 All                            DescRingBufferCancel API added.
2007-04-13 05.02.00
                    Sa     Fixed             ESCAN00020257 General Motors(KWP2000)        Stop and re-schedule for ReadDataByPacketIdentifier does not work as specified.
                    Sa     Modified          ESCAN00019817 General Motors(KWP2000)        Remove the unnecessary declaration of "g_applDescEcuNumber".
                    Sa     Modified          ESCAN00020229 General Motors(KWP2000)        Maximum scheduler limitation of 15 items changed to 256 items.
                    Sa     Modified          ESCAN00019984 General Motors(KWP2000)        Optimize the DPID look-up table by using bottom offset.
2007-05-30 05.03.00
                    Sa     Modified          ESCAN00019918 General Motors(KWP2000)        Compiler Error Due To Comment  
                    Sa     Modified          ESCAN00020840 All                            Compiler error message on local variable pointer to ROM using V_MEMROM0 define
                    Sa     Modified          ESCAN00019437 All                            Compiler error in desc.c with mem-model huge
2007-07-23 05.04.00
                    Sa     Fixed             ESCAN00021520 General Motors(KWP2000)        An UUDT response is sent after positive response $60 on long-time DPID processing
                    Sa     Fixed             ESCAN00021521 General Motors(KWP2000)        No RCR-RP response is sent after scheduler update
                    Sa     Fixed             ESCAN00021522 General Motors(KWP2000)        No UUDT transmission for serivces $A9 $82 and $AA on failed positive response for SId $20
                    Sa     Fixed             ESCAN00021336 All                            use lower case characters for names of generated files (AppDesc.h => appdesc.h)
                    Sa     Modified          ESCAN00021523 All                            Removed the first frame length dependency on Vector TP for for ring-buffer usage
                    Sa     Added             ESCAN00021528 All                            Stopping RepeatedServiceCall in RingBufferCancel
                    Sa     Added             ESCAN00021567 All                            Use case catch on RingBuffer usage with SPRMIB=1
2007-09-07 05.05.00
                    Sa     Fixed             ESCAN00021748 General Motors(KWP2000)        Compile error on PID list mode on Sid $22 when none of the services $2C, $2A or $2D exist
                    Sa     Fixed             ESCAN00021491 General Motors(KWP2000)        MIM only: CANdesc sends UUDT responses with CAN IDs from other identities
                    Sa     Modified          ESCAN00022072 General Motors(KWP2000)        Service $A5 can be deactivated 
                    Sa     Fixed             ESCAN00022068 All                            Include appDesc.h changed to appdesc.h
                    Sa     Modified          ESCAN00021654 All                            Explicit suppression of NRC $11 on functional request
                    Sa     Modified          ESCAN00021252 All                            Compiler warnings for unreferenced variable and function declaration
                    Sa     Modified          ESCAN00022254 All                            Adaptions for the interrupt support of the latest VStdLib version
                    Sa     Added             ESCAN00021847 All                            Access to the current communication parameters
2007-10-22 05.05.01
                    -      -                 -             -                              No relevant changes available in this version.
2007-10-26 05.05.02
                    -      -                 -             -                              No relevant changes available in this version.
2007-11-15 05.05.03
                    Sa     Added             ESCAN00023231 All                            Support multiple ECU numbers   
2007-12-17 05.05.04
                    Sa     Fixed             ESCAN00023510 General Motors(KWP2000)        Negative responses to physically addressed OBD requests shall not be suppressed
                    Sa     Fixed             ESCAN00023486 General Motors(KWP2000)        ECU transmits "non-diagnostic messages" after positive response to service $28
                    Sa     Fixed             ESCAN00023719 General Motors(KWP2000)        Compile (linker) error on undefined identifier TP_RX_ECU_NR
                    Sa     Fixed             ESCAN00023682 KWP2000                        Compile warning on usage of kTpSuccess instead of enum value kDescUsdtNetworkOk
2007-12-20 05.06.00
                    Sa     Fixed             ESCAN00023510 General Motors(KWP2000)        Negative responses to physically addressed OBD requests shall not be suppressed
                    Sa     Fixed             ESCAN00023486 General Motors(KWP2000)        ECU transmits "non-diagnostic messages" after positive response to service $28
                    Sa     Fixed             ESCAN00023719 General Motors(KWP2000)        Compile (linker) error on undefined identifier TP_RX_ECU_NR
                    Sa     Fixed             ESCAN00023682 KWP2000                        Compile warning on usage of kTpSuccess instead of enum value kDescUsdtNetworkOk
                    Sa     Fixed             ESCAN00023835 KWP2000                        Wrong assertion activation on call of DescRingBufferStart
                    Sa     Modified          ESCAN00022868 KWP2000                        Consider CDD files having only SID based information (CANdescBasic like)
                    Sa     Added             ESCAN00023231 All                            Support multiple ECU numbers   
2008-01-22 05.06.01
                    Sa     Fixed             ESCAN00023944 General Motors(KWP2000)        Invalid data responded with service $22 (ReadDataByIdentifier)
                    Sa     Added             ESCAN00024151 General Motors(KWP2000)        Add GENy and CANgen generated NM configuration compatibility
                    Sa     Fixed             ESCAN00026046 All                            CANdesc responds on wrong CAN Id
                    Mhe    Added             ESCAN00024011 All                            Support dynamic normal addressing
                    Mhe    Added             ESCAN00024019 All                            Support far RAM Tp API         
2008-02-04 05.06.02
                    Sa     Fixed             ESCAN00024053 General Motors(KWP2000)        Functional OBD requests are ignored unless preceded by a valid functional diagnostic request
2008-01-11 05.06.03
                    Sa     Fixed             ESCAN00024523 General Motors(KWP2000)        Compile error when service $2C is enabled
2008-03-14 05.06.04
                    Sa     Fixed             ESCAN00024888 General Motors(KWP2000)        Compile error if DID processing services are handled in CANdesc and no state group is available in the CDD file
2008-04-03 05.06.05
                    -      -                 -             -                              No relevant changes available in this version.
2008-04-21 05.06.06
                    Ktw    Fixed             ESCAN00026350 KWP2000                        TMS320 support for KWP2000 functional requests with response
                    Sa     Fixed             ESCAN00026335 All                            Compile error with DynamicTP   
2008-05-23 05.06.07
                    Sa     Fixed             ESCAN00026907 All                            On TMS320 wrong vstdlib memcopy API used
                    Sa     Fixed             ESCAN00027059 All                            Array out of boundary access error on generated main-handler with ring-buffer access
                    Sa     Modified          ESCAN00027061 All                            Minor DescICN driver optimization
                    Sa     Modified          ESCAN00027063 All                            MainHandler req-/resDataLen has misleading description for CANdescBasic
                    Ktw    Modified          ESCAN00027057 All                            Compile error on missing semicolon for DescSetNpmOnCanChannelActive macro expansion
                    Mhe    Added             ESCAN00026452 All                            Posthandler support for generated $23
2008-05-26 05.06.08
                    Sa     Fixed             ESCAN00027085 General Motors(KWP2000)        Compile error on configurations without service $2A or $2C
                    Sa     Fixed             ESCAN00027084 All                            Compile error on non TMS320 platforms
2008-06-05 05.06.09
                    Sa     Fixed             ESCAN00027196 General Motors(KWP2000)        Service 0xAA accepts unsupported DPIDs
                    Sa     Fixed             ESCAN00027180 General Motors(KWP2000)        Compile error if multiple DIDs supported with service 0x22
2008-06-16 05.06.10
                    -      -                 -             -                              No relevant changes available in this version.
2008-06-27 05.07.00
                    Sa     Fixed             ESCAN00023944 General Motors(KWP2000)        Invalid data responded with service $22 (ReadDataByIdentifier)
                    Sa     Fixed             ESCAN00024053 General Motors(KWP2000)        Functional OBD requests are ignored unless preceded by a valid functional diagnostic request
                    Sa     Fixed             ESCAN00024888 General Motors(KWP2000)        Compile error if DID processing services are handled in CANdesc and no state group is available in the CDD file
                    Sa     Fixed             ESCAN00027196 General Motors(KWP2000)        Service 0xAA accepts unsupported DPIDs
                    Sa     Added             ESCAN00024151 General Motors(KWP2000)        Add GENy and CANgen generated NM configuration compatibility
                    Ktw    Fixed             ESCAN00026350 KWP2000                        TMS320 support for KWP2000 functional requests with response
                    Mhe    Fixed             ESCAN00027950 KWP2000                        Functional requests respond on wrong CAN ID
                    Sa     Fixed             ESCAN00026046 All                            CANdesc responds on wrong CAN Id
                    Sa     Fixed             ESCAN00026907 All                            On TMS320 wrong vstdlib memcopy API used
                    Sa     Fixed             ESCAN00027059 All                            Array out of boundary access error on generated main-handler with ring-buffer access
                    Sa     Modified          ESCAN00027061 All                            Minor DescICN driver optimization
                    Sa     Modified          ESCAN00027063 All                            MainHandler req-/resDataLen has misleading description for CANdescBasic
                    Sa     Modified          ESCAN00027057 All                            Compile error on missing semicolon for DescSetNpmOnCanChannelActive macro expansion
                    Mhe    Added             ESCAN00024011 All                            Support dynamic normal addressing
                    Mhe    Added             ESCAN00024019 All                            Support far RAM Tp API         
                    Mhe    Added             ESCAN00026452 All                            Posthandler support for generated $23
2008-07-11 05.07.01
                    -      -                 -             -                              No relevant changes available in this version.
2008-08-08 05.07.02
                    Sa     Fixed             ESCAN00022820 General Motors(KWP2000)        Compile error in desc.c function DescSetCommState
                    Sa     Fixed             ESCAN00028409 All                            No response on request         
2008-10-02 05.07.03
                    Sa     Modified          ESCAN00029770 All                            Compiler warning for enumeration item with value 0xFF on enum-type = char
                    Sa     Added             ESCAN00030116 All                            Provide IsoTp-Callback prototypes in desc.h/danisisotp.h
                    Sa     Added             ESCAN00030087 All                            Support of internal diagnostic requests over IsoTP
2008-10-30 05.07.04
                    Sa     Fixed             ESCAN00030759 All                            Generator stops with internal error during processing 'MainHandlerOnProtocolService' that contains muxed component
                    Sa     Fixed             ESCAN00030981 All                            Switch to surpress multitiple addressing check
                    Sa     Fixed             ESCAN00029915 All                            CANdesc files can not be written
                    Sa     Modified          ESCAN00031158 All                            Ring-buffer feature enabled for non-ISO-TP DANIS drivers
                    Sa     Added             ESCAN00031156 All                            Added DANIS abstraction for testerId and comChannel
2008-11-26 05.07.05
                    -      -                 -             -                              No relevant changes available in this version.
2008-12-15 05.07.06
                    Ktw    Fixed             ESCAN00031533 All                            Compiler Warning: Unused variable tpTxChannel
2009-02-02 05.07.07
                    Sa     Fixed             ESCAN00027182 All                            Compiler Warning: variable "svcInstFailedBytePosMask" is possibly uninitialized
2009-02-17 05.07.08
                    -      -                 -             -                              No relevant changes available in this version.
2009-03-09 05.07.09
                    -      -                 -             -                              No relevant changes available in this version.
2009-03-12 05.07.10
                    -      -                 -             -                              No relevant changes available in this version.
2009-03-16 05.07.11
                    -      -                 -             -                              No relevant changes available in this version.
2009-03-16 05.07.12
                    -      -                 -             -                              No relevant changes available in this version.
2009-04-15 05.07.13
                    -      -                 -             -                              No relevant changes available in this version.
2009-05-06 05.07.14
                    Sa     Fixed             ESCAN00034934 All                            Wrong null-terminated and leading size byte string data object total length calculation
2009-06-19 05.07.15
                    Ktw    Fixed             ESCAN00035554 All                            Null pointer access in DanisBoschTp
2009-07-01 05.07.16
                    -      -                 -             -                              No relevant changes available in this version.
2009-07-13 05.07.17
                    Ktw    Fixed             ESCAN00036465 General Motors(KWP2000)        CANdesc should not send a diagnostic response if VN is not active
2009-08-11 05.07.18
                    Sa     Fixed             ESCAN00037297 General Motors(KWP2000)        Periodic DPID scheduler overwritten if the new request
                    Sa     Fixed             ESCAN00036995 All                            Compile warning on redeclaration of function DescGetBuffer
                    Sa     Fixed             ESCAN00036138 All                            Compiler warning on redundant declaration of DescGetBuffer
                    Sa     Modified          ESCAN00036996 All                            Switching between ANSI C and hardware optimized bit-type
                    Sa     Modified          ESCAN00037096 All                            Undo ESCAN00036465             
2009-08-31 05.07.19
                    -      -                 -             -                              No relevant changes available in this version.
2009-10-14 05.07.20
                    Sa     Fixed             ESCAN00038468 General Motors(KWP2000)        UUDT data improperly copied for TMS320
                    Sa     Fixed             ESCAN00037724 KWP2000                        Compiler warning for assignment of type array of vuint8* to vuint8*
                    Sa     Fixed             ESCAN00038397 KWP2000                        Compiler error in desc.c due to illegal type(s): DescUsdtNetMsg '=' ptr-to-array[1]-of-vuint8
2009-11-17 05.07.21
                    Sa     Modified          ESCAN00039608 General Motors(KWP2000)        Remove duplicate generated macro kDescUudtConfirmTimeoutTicks
                    Sa     Fixed             ESCAN00038825 KWP2000                        Compiler warning/error for wrong parameter passed
                    Sa     Fixed             ESCAN00039237 All                            Compiler Warning: possible redundant expression / useless assignment
                    Sa     Modified          ESCAN00040135 All                            CanChannelIdentityAssignment is generated in RAM section
2010-02-02 05.07.22
                    -      -                 -             -                              No relevant changes available in this version.
2010-02-12 05.07.23
                    -      -                 -             -                              No relevant changes available in this version.
2010-05-12 05.07.24
                    Sa     Fixed             ESCAN00042963 All                            DescCopyToCan API does not support CAN message buffers located in the gpage
2010-05-31 05.07.25
                    Sa     Fixed             ESCAN00041576 All                            Compiler warning for constant expression in DescDispatcher
                    Sa     Fixed             ESCAN00043240 All                            Compiler error for missing data types DescDynDidMemBlockAddress and DescDynDidMemBlockSize
2010-07-16 05.07.26
                    Sa     Fixed             ESCAN00044050 All                            Compiler warning: condition is always false
                    Sa     Fixed             ESCAN00044197 All                            Not all buffers used in DANIS can be located in far RAM
                    Sa     Added             ESCAN00044127 All                            Support for DANIS adapter specific available buffer size information to the application
2010-08-10 05.07.27
                    Sa     Fixed             ESCAN00044281 General Motors(KWP2000)        Compile error for missing constant kDescOemNrcParamIdNotSupportedInSession
                    Sa     Fixed             ESCAN00044371 All                            v_inc.h is not included in the generated DANIS adapter template
                    Sa     Fixed             ESCAN00044528 All                            Compile errors in DanisIsoTp communication adapter
2010-10-14 05.07.28
                    Ktw    Fixed             ESCAN00045731 General Motors(KWP2000)        Service 0xA9 0x80/0x81 can not be executed immediately after the EndOfDtcReport UUDT message
                    Ktw    Fixed             ESCAN00045711 General Motors(KWP2000)        CANdesc overwrites memory after redefining a dynamic DPID
                    Ktw    Fixed             ESCAN00045902 General Motors(KWP2000)        Service 0x22 will be rejected with NRC 0x31 on one found secured PID
                    Ktw    Fixed             ESCAN00045932 All                            Compile error on each usage of DescInterruptDisable/-Restore internal API
2010-10-08 05.07.29
                    Mhe    Fixed             ESCAN00046410 All                            After ECU reset the diagnostic response is not transmitted after the function DescSendPosRespFBL has been called
2010-12-18 05.07.30
                    Ktw    Fixed             ESCAN00047431 General Motors(KWP2000)        Compiler warning: " static symbol `DescOemPostStartDisableAllDTCs' unused "
                    Sa     Fixed             ESCAN00037827 General Motors(KWP2000)        kDescEcuAddress in desc.h is always getting generated to 0x00 instead of populating the ECU address value from CDD file
                    Sa     Fixed             ESCAN00047355 All                            Memory mapping of FAR buffer support use incomplete description for paged memory µC
                    Ktw    Added             ESCAN00047741 All                            Adapt CANdesc TMS320 support for GENy enabled CANdriver
2011-01-04 05.07.31
                    Ktw    Fixed             ESCAN00047884 All                            ROM data used as function parameter
------------------------------------------------------------------------------------------------------------------------
 */


/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

/* include of TP interface */
#include "tpmc.h"



/* -----------------------------------------------------------------------------
    &&&~ Configuration switches
 ----------------------------------------------------------------------------- */

/* Gentool GENy will be supported. */
#define DESC_ENABLE_GENTOOL_GENY
/* Flashable ECU will not be supported. */
#define DESC_DISABLE_FLASHABLE_ECU
/* Vectors FBL will not be supported. */
#define DESC_DISABLE_VECTOR_FBL_USAGE
/* Far addressing of diagnostic buffer will not be supported. */
#define DESC_DISABLE_FAR_BUFFER
/* KWP2000 diagnostic protocol will be supported. */
#define DESC_ENABLE_PROTOCOL_KWP
/* UDS diagnostic protocol will not be supported. */
#define DESC_DISABLE_PROTOCOL_UDS
/* Application debug monitoring will not be supported. */
#define DESC_DISABLE_DEBUG_USER
/* Internal processes' debug monitoring will not be supported. */
#define DESC_DISABLE_DEBUG_INTERNAL
#if (TP_USE_EXTENDED_ADDRESSING == kTpOn) || \
    defined (TP_ENABLE_NORMAL_FIXED_ADDRESSING) || \
    defined (TP_ENABLE_MIXED_29_ADDRESSING)
# define DESC_ENABLE_ACCESS_TESTER_ADDRESS_API
#endif

/* Transport layer type */
#if defined (TP_ENABLE_SINGLE_CHANNEL_TP)
# define DESC_USDTNET_DISABLE_MULTI_TP
# define DESC_USDTNET_ENABLE_SINGLE_TP_OPTIMIZED
#else
# define DESC_USDTNET_ENABLE_MULTI_TP
# define DESC_USDTNET_DISABLE_SINGLE_TP_OPTIMIZED
#endif

/* Inter-context network will be supported. */
#define DESC_ENABLE_DESCICN_SUPPORT
/* Inter-context network client resource lock will not be supported. */
#define DESC_USDTNET_DISABLE_TX_LOCK_DESCICN
/* Multi inter-context network will not be supported. */
#define DESC_USDTNET_DISABLE_MULTI_DESCICN
/* LongServiceExecution will not be supported. */
#define DESC_USDTNET_DISABLE_LONGSERVICE_SUPPORT
/* Ring buffer will not be supported. */
#define DESC_USDTNET_DISABLE_RING_BUFFER
/* Far RAM buffer will not be supported. */
#define DESC_USDTNET_DISABLE_FAR_BUFFER
/* Shared buffer multi client usage will not be supported. */
#define DESC_USDTNET_DISABLE_MULTI_OWNER_SHARED_BUFFER
/* Dynamic buffer usage will not be supported. */
#define DESC_USDTNET_DISABLE_DYNAMIC_BUFFER_LENGTH
/* Static buffer allocation */
#define DESC_USDTNET_ENABLE_VECTOR_ISO_TP

/* UUDT Network will be supported. */
#define DESC_ENABLE_UUDT_NET
/* UUDT mutli-bus will not be supported. */
#define DESC_UUDTNET_DISABLE_MULTI_BUS_SUPPORT
/* UUDT mutli-client will be supported. */
#define DESC_UUDTNET_ENABLE_MULTI_CLIENT
/* UUDT dynamic CAN channels will be supported. */
#define DESC_UUDTNET_ENABLE_DYN_MULTICAN_SUPPORT
/* Enable if some of the resources shall be only once reserved until explicit release */
#define DESC_UUDTNET_DISABLE_DYN_LIFETIME_SUPPORT

/* By default enable the (zero) padding */
#define DESC_UUDTNET_ENABLE_MSG_PADDING

/* Optimization (future option) */
#define DESC_UUDTNET_DISABLE_DATALENGTH_USAGE

#define DESC_UUDTNET_DISABLE_DATA_QUEUE
/* Addressing information validation */
#define DESC_DISABLE_PHYSREQ_TA_CHECK
#define DESC_DISABLE_PHYSREQ_SA_CHECK
#define DESC_ENABLE_FUNCREQ_TA_CHECK
#define DESC_DISABLE_FUNCREQ_SA_CHECK

/* Principally enable response on functional request (optimization) */
#define DESC_ENABLE_RES_ON_FUNC_REQUEST
/* Check message DLC (must be 8 for OBD) */
#define DESC_DISABLE_FORCE_DLC_8
/* specify if in case of not fitting into the
* buffer request a negative response to be sent 
*/
#define DESC_ENABLE_NEGRES_ON_MSG_TOO_LONG
/* Do use the second path */
#define DESC_ENABLE_FUNC_RX_PATH

/* High-Speed programming will not be supported. */
#define DESC_DISABLE_HIGH_SPEED_SUPPORT
/* Check before message reception will not be supported. */
#define DESC_DISABLE_CHECK_MSG_RX_ACCEPTANCE
/* Bus abstraction will not be supported. */
#define DESC_DISABLE_USDT_MULTI_BUS_SUPPORT
/* Spontaneous response will be supported. */
#define DESC_ENABLE_SPONTANEOUS_RES
/* Secured data transmission API will not be supported. */
#define DESC_DISABLE_SECURED_DATA_TRANSMISSION
/* Multi channel system will be supported. */
#define DESC_ENABLE_MULTI_CHANNEL_SUPPORT
#if defined (C_SINGLE_RECEIVE_CHANNEL) || defined (C_MULTIPLE_RECEIVE_CHANNEL)
/* Code-doubled CANdriver will not be supported. */
#define DESC_DISABLE_CODE_DOUBLED_DRIVER_API
#endif
#if !defined (C_SINGLE_RECEIVE_CHANNEL) && !defined (C_MULTIPLE_RECEIVE_CHANNEL)
/* Code-doubled CANdriver will be supported. */
#define DESC_ENABLE_CODE_DOUBLED_DRIVER_API
#endif
/* Parallel reception and rejection diagnostic service will not be supported. */
#define DESC_DISABLE_BUSY_REPEAT_RESPONDER
/* Additional OBD reception path will not be supported. */
#define DESC_DISABLE_OBD_FUNC_REQUEST
/* Parallel handling of OBD service will not be supported. */
#define DESC_DISABLE_PARALLEL_OBD
/* CCL usage */
#if defined (VGEN_ENABLE_CCL)
# define DESC_ENABLE_CCL_SUPPORT
#else
# define DESC_DISABLE_CCL_SUPPORT
#endif
/* Transport layer type */
#if defined (TP_ENABLE_SINGLE_CHANNEL_TP)
# define DESC_DISABLE_MULTI_TP
# define DESC_ENABLE_SINGLE_TP_OPTIMIZED
#else
# define DESC_ENABLE_MULTI_TP
# define DESC_DISABLE_SINGLE_TP_OPTIMIZED
#endif

/* Non-constant S1 timeout will not be supported. */
#define DESC_DISABLE_DYN_S1_TIMEOUT
/* TesterPresent monitoring will be supported. */
#define DESC_ENABLE_S1_TIME_MONITORING
/* No RCR-RP limitation will be used. */
#define DESC_DISABLE_RES_PENDING_TIME_LIMIT
#define DESC_DISABLE_RES_PENDING_COUNT_LIMIT
/* Application forced RCR-RP response transmission will not be supported. */
#define DESC_DISABLE_FORCE_RCR_RP
#define DESC_DISABLE_OEM_HANDLING_ON_RCRRP_LIMIT_EXPIRATION
#define DESC_DISABLE_S1_ANY_SVC_RELOAD
#define DESC_ENABLE_S1_SINGLE_SVC_RELOAD

/* Automaticaly managed states will be supported. */
#define DESC_ENABLE_AUTO_STATES
/* Provides control of SID session check */
#define DESC_DISABLE_SESSION_CHECK_ON_SID_LEVEL

/* Support extended negative response (with additional data bytes) */
#define DESC_ENABLE_EXT_NEG_RES_CODE_HANDLING

/* Treat any PID not supported in current security state as not supported */
#define DESC_ENABLE_SKIP_PID_ON_WRONG_SECURITY_STATE

/* Do send NRC for wrong security state only if none of the requested PIDs are supported in the security state */
/*#define DESC_ENABLE_PID_NRC_ALL_ON_WRONG_SECURITY_STATE*/
/* Not necessary for GM, because same Nrc for not supported and secured*/


/* Each main-handler will be called only once. The application shall take care about calling DescProcessingDone from somwhere at the end of the request process. */
#define DESC_DISABLE_MAINHANDLER_MULTICALL
#define DESC_DISABLE_INDIVIDUAL_MAINHANDLER_MULTICALL
#define DESC_DISABLE_PERMANENT_MAINHANDLER_MULTICALL
/* Request minimum length check will not be supported. */
#define DESC_DISABLE_MIN_REQ_LEN_CHECK
/* Any pre-Handler from the SvcInst table will be supported. */
#define DESC_ENABLE_PREHANDLER_USAGE
/* Any post-Handler from the SvcInst table will be supported. */
#define DESC_ENABLE_POSTHANDLER_USAGE
/* User (unknown) service-handler will be supported. */
#define DESC_ENABLE_GENERIC_USER_SERVICE_SUPPORT
/* User (unknown) service post-handler will be supported. */
#define DESC_ENABLE_GENERIC_USER_POST_HANDLER_SUPPORT
/* Session check before format check will not be supported. */
#define DESC_DISABLE_SESSION_FORMAT_STATE_CHECK
/* If OBD services are present enable conformance */
#if defined (DESC_ENABLE_OBD_FUNC_REQUEST)
# define DESC_ENABLE_OBDII_NR_CONFORMANCE
#endif

/* Is skip PID supported? */
#if defined (DESC_ENABLE_SKIP_PID_ON_WRONG_SESSION) || \
    defined (DESC_ENABLE_SKIP_PID_ON_WRONG_SECURITY_STATE)
# define DESC_ENABLE_SKIP_PID
#else
# define DESC_DISABLE_SKIP_PID
#endif

/* Pre-handlers will be supported. */
#define DESC_ENABLE_ANY_PREHANDLER_USAGE
/* Post-handlers will be supported. */
#define DESC_ENABLE_ANY_POSTHANDLER_USAGE
/* Use linear search for optimal runtime. */
#define DESC_DISABLE_BINARY_SVCINST_SEARCH
#define DESC_ENABLE_LINEAR_SVCINST_SEARCH
/* Sub-service protocol information will be supported. */
#define DESC_ENABLE_SUB_SVC_USAGE
/* Special NRC for subfuction not supported in active session will not be supported. */
#define DESC_DISABLE_NRC_SUBFUNCTION_WRONG_SESSION
/* Supported only for GMLAN and low speed ECU */
#if defined (DESC_ENABLE_HIGH_SPEED_SUPPORT) && \
    defined (NM_TYPE_GMLAN)
# define DESC_ENABLE_REQ_HISPEED_PROG
#else
# define DESC_DISABLE_REQ_HISPEED_PROG
#endif

/* Service "DisableAllDTCs" will be supported. */
#define DESC_ENABLE_SERVICE_10_02
/* Service "EnableDTCsDuringDeviceControl" will be supported. */
#define DESC_ENABLE_SERVICE_10_03
/* Communication control service will not be supported. */
#define DESC_DISABLE_COMM_CTRL
/* Programming session OEM handling will be supported. */
#define DESC_ENABLE_PROGRAMMING_SESSION
/* Stop session service will be supported. */
#define DESC_ENABLE_SERVICE_STOP_SESSION
/* Service $A9 will be supported. */
#define DESC_ENABLE_SERVICE_A9_SUPPORT
/* Sub-function $80 of SID $A9 will not be supported. */
#define DESC_DISABLE_SERVICE_A9_80_SUPPORT
/* Sub-function $81 of SID $A9 will be supported. */
#define DESC_ENABLE_SERVICE_A9_81_SUPPORT
/* Sub-function $82 of SID $A9 will not be supported. */
#define DESC_DISABLE_SERVICE_A9_82_SUPPORT
/* Security access service will not be supported. */
#define DESC_DISABLE_SECURITY_ACCESS
/* Unified PID management will not be supported. */
#define DESC_DISABLE_UNIFIED_PID_MGR
/* PidList mode simulation will not be supported. */
#define DESC_DISABLE_SIM_PID_LIST_MODE
/* PIDs pre-Handlers will not be supported. */
#define DESC_DISABLE_PID_PREHANDLER_USAGE
/* PIDs post-Handlers will not be supported. */
#define DESC_DISABLE_PID_POSTHANDLER_USAGE
/* Combinable PID with dynamic data length will not be supported. */
#define DESC_DISABLE_DYN_DID_RES_LENGTH
#define DESC_DISABLE_PID_SECURITY_FILTER
/* Routine control management will not be supported. */
#define DESC_DISABLE_ROUTINE_CONTROL_MODE
/* Scheduled DID will be supported. */
#define DESC_ENABLE_SCHEDULED
/* Multiple PID in single request will be supported. */
#define DESC_ENABLE_PID_LIST_MODE
/* Dynamically defined DIDs will not be supported. */
#define DESC_DISABLE_DYN_DEFINED_DID_MODE
/* Dynamically defined by Id DIDs will not be supported. */
#define DESC_DISABLE_DEF_DYN_ID_BY_PID
/* Dynamically defined by memory DIDs will not be supported. */
#define DESC_DISABLE_DEF_DYN_ID_BY_MEM
/* Dynamically defined DPIDs will be supported. */
#define DESC_ENABLE_DYN_DEFINED_DPID_MODE
/* ResponseOnEvent service will not be supported. */
#define DESC_DISABLE_ROE_SUPPORT
/* Ring-buffer handling will not be supported. */
#define DESC_DISABLE_RES_RINGBUFFER


/* -----------------------------------------------------------------------------
    &&&~ Preprocessor constants (defines)
 ----------------------------------------------------------------------------- */

/* ##V_CFG_MANAGEMENT ##CQProject : Diag_CanDesc__core CQComponent : Implementation */
#define DIAG_CANDESC__CORE_VERSION                                   0x0507
#define DIAG_CANDESC__CORE_RELEASE_VERSION                           0x31
#define DESC_VERSION                                                 0x0507
#define DESC_RELEASE_VERSION                                         0x31
/* Desc generic return codes */
#define kDescOk                                                      ((vuint8)0x00)
#define kDescFailed                                                  ((vuint8)0x01)
/*  data type according to the CPU type */
#if defined( C_CPUTYPE_8BIT )
/* 8-Bit qualifier */
# ifndef vuint8_least
#  define vuint8_least                                               vuintx
# endif
# ifndef vsint8_least
#  define vsint8_least                                               vsintx
# endif
#else
# if defined( C_CPUTYPE_16BIT )
/* 16-Bit qualifier */
#  ifndef vuint8_least
#   define vuint8_least                                              vuintx
#  endif
#  ifndef vsint8_least
#   define vsint8_least                                              vsintx
#  endif
#  ifndef vuint16_least
#   define vuint16_least                                             vuintx
#  endif
#  ifndef vsint16_least
#   define vsint16_least                                             vsintx
#  endif

# else
#  if defined( C_CPUTYPE_32BIT )
/* 32-Bit qualifier */
#   ifndef vuint8_least
#    define vuint8_least                                             vuintx
#   endif
#   ifndef vsint8_least
#    define vsint8_least                                             vsintx
#   endif
#   ifndef vuint16_least
#    define vuint16_least                                            vuintx
#   endif
#   ifndef vsint16_least
#    define vsint16_least                                            vsintx
#   endif
#   ifndef vuint32_least
#    define vuint32_least                                            vuintx
#   endif
#   ifndef vsint32_least
#    define vsint32_least                                            vsintx
#   endif
#  endif
# endif
#endif

/* Default optimized types */
#ifndef vuint8_least
# define vuint8_least                                                vuint8
#endif
#ifndef vuint16_least
# define vuint16_least                                               vuint16
#endif
#ifndef vuint32_least
# define vuint32_least                                               vuint32
#endif

#ifndef vsint8_least
# define vsint8_least                                                vsint8
#endif
#ifndef vsint16_least
# define vsint16_least                                               vsint16
#endif
#ifndef vsint32_least
# define vsint32_least                                               vsint32
#endif

/* Optimized boolean type */
#ifndef vboolean
# define vboolean                                                    vuint8_least
#endif

#ifndef V_BOOL_TRUE
# define V_BOOL_TRUE                                                 (vboolean)1
#endif

#ifndef V_BOOL_FALSE
# define V_BOOL_FALSE                                                (vboolean)0
#endif
/* CANdesc API types use the CANdesc namings convention! */
#define kDescFalse                                                   V_BOOL_FALSE
#define kDescTrue                                                    V_BOOL_TRUE
#define DESC_IGNORE_UNREF_PARAM(paramName)                           ((void)paramName)

#if !defined (VUINT8_CAST)
# if defined ( C_COMP_COSMIC_HC08 ) || defined ( C_COMP_COSMIC_HC12 ) /* any cosmic cpu */
#  define VUINT8_CAST                                                (vuint8)
#  define VSINT8_CAST                                                (vsint8)
#  define VUINT16_CAST                                               (vuint16)
#  define VSINT16_CAST                                               (vsint16)
#  define CANBITTYPE_CAST                                            (vbittype)
#  define CANSINTCPUTYPE_CAST                                        (int)
#  define CANUINTCPUTYPE_CAST                                        (unsigned int)
# else
#  define VUINT8_CAST
#  define VSINT8_CAST
#  define VUINT16_CAST
#  define VSINT16_CAST
#  define CANBITTYPE_CAST
#  define CANSINTCPUTYPE_CAST
#  define CANUINTCPUTYPE_CAST
# endif /* ( C_COMP_COSMIC_HC08 ) || defined ( C_COMP_COSMIC_HC12 ) */
#endif

#if defined (V_MEMROM0)
/* new driver ok */
#else
# define V_MEMROM0
#endif


#if defined (V_MEMROM1)
/* new driver ok */
#else
# define V_MEMROM1
#endif

#if defined (V_MEMROM2)
/* new driver ok */
#else
# define V_MEMROM2                                                   MEMORY_ROM
#endif

#if defined (V_MEMROM3)
/* new driver ok */
#else
# define V_MEMROM3
#endif

#if defined (V_MEMRAM0)
/* new driver ok */
#else
# define V_MEMRAM0
#endif

#if defined (V_MEMRAM1)
/* new driver ok */
#else
# define V_MEMRAM1
#endif

#if defined (V_MEMRAM1_FAR)
/* new driver ok */
#else
# define V_MEMRAM1_FAR
#endif

#if defined (V_MEMRAM2)
/* new driver ok */
#else
# define V_MEMRAM2
#endif

#if defined (V_MEMRAM2_FAR)
/* new driver ok */
#else
# define V_MEMRAM2_FAR
#endif

#if defined (V_MEMRAM3)
/* new driver ok */
#else
# define V_MEMRAM3
#endif
/* Define of a DESC_CONST_MEM_ABSTRACT*/
#define DESC_CONST_MEM_ABSTRACT                                      const

/* Compile memory model abstraction */
#if defined(DESC_ENABLE_FAR_BUFFER)
/* Ram Pointer to Far Ram */
# define DESC_P2FARRAM(baseType)                                     V_MEMRAM1_FAR baseType V_MEMRAM2_FAR V_MEMRAM3_FAR *
/* DESC_CONSTP2FARRAM is only used as function parameter.
Therefore, DESC_CONST_MEM_ABSTRACT is defined to const and not
explicit mapped to the ROM*/
# define DESC_CONSTP2FARRAM(baseType)                                V_MEMRAM1_FAR baseType V_MEMRAM2_FAR V_MEMRAM3_FAR * DESC_CONST_MEM_ABSTRACT
# define DESC_PUBL_DEF_VAR_FAR(baseType)                             V_MEMRAM0 V_MEMRAM1_FAR baseType V_MEMRAM2_FAR V_MEMRAM3_FAR
# define DESC_PRVT_DEF_VAR_FAR(baseType)                             V_MEMRAM0 static V_MEMRAM1_FAR baseType V_MEMRAM2_FAR
# define DESC_PUBL_DECL_VAR_FAR(baseType)                            V_MEMRAM0 extern V_MEMRAM1_FAR baseType V_MEMRAM2_FAR
#else /*DESC_ENABLE_FAR_BUFFER*/
# define DESC_P2FARRAM(baseType)                                     V_MEMRAM1 baseType V_MEMRAM2 V_MEMRAM3 *
/* DESC_CONSTP2FARRAM is only used as function parameter.
Therefore, DESC_CONST_MEM_ABSTRACT is defined to const and not
explicit mapped to the ROM*/
# define DESC_CONSTP2FARRAM(baseType)                                V_MEMRAM1 baseType V_MEMRAM2 V_MEMRAM3 * DESC_CONST_MEM_ABSTRACT
# define DESC_PUBL_DEF_VAR_FAR(baseType)                             V_MEMRAM0 V_MEMRAM1 baseType V_MEMRAM2 V_MEMRAM3
# define DESC_PRVT_DEF_VAR_FAR(baseType)                             V_MEMRAM0 static V_MEMRAM1 baseType V_MEMRAM2
# define DESC_PUBL_DECL_VAR_FAR(baseType)                            V_MEMRAM0 extern V_MEMRAM1 baseType V_MEMRAM2
#endif

#if defined(DESC_API_CALL_TYPE)
#else
  /* No paging used. */
  #define DESC_API_CALL_TYPE
#endif

#if defined(DESC_API_CALLBACK_TYPE)
#else
  /* No paging used. */
  #define DESC_API_CALLBACK_TYPE
#endif

#if defined(TP_API_CALLBACK_TYPE)
#else
  /* No paging used. */
  #define TP_API_CALLBACK_TYPE
#endif

#if defined(DRV_API_CALLBACK_TYPE)
#else
  /* No paging used. */
  #define DRV_API_CALLBACK_TYPE
#endif

#if defined(DRV_API_CALL_TYPE)
#else
  /* No paging used. */
  #define DRV_API_CALL_TYPE
#endif

/* This magic number provides inter CANdesc generation process consistency check.All CANdesc files must have the same one. */
#define DESC_PUBLIC_INTERFACE_MAGIC_NUMBER                           25472
/* ---  Debug assertion codes  --- */
#define kDescAssertWrongTpTxChannel                                  0x00
#define kDescAssertCanBufferIsNullPointer                            0x01
#define kDescAssertIndexTableInvalidReference                        0x02
#define kDescAssertSvcTableUnreachableItem                           0x03
#define kDescAssertSvcTableInvalidReference                          0x04
#define kDescAssertSvcTableInconsistentNumber                        0x05
#define kDescAssertMissingMainHandler                                0x06
/* Obsolete: 
#define kDescAssertSFMsgTooLong                                      0x07
*/
#define kDescAssertInvalidContextId                                  0x08
#define kDescAssertSvcTableIndexOutOfRange                           0x09
#define kDescAssertSvcInstTableIndexOutOfRange                       0x0A
#define kDescAssertContextIdWasModified                              0x0B
/* Obsolete: 
#define kDescAssertContextPointerWasModified                         0x0C
#define kDescAssertWrongTpRxChannel                                  0x0D
*/
#define kDescAssertProcessingDoneCallAfterResFlushing                0x0E
#define kDescAssertTooLongSingleFrameResponse                        0x0F
/* Obsolete: 
#define kDescAssertIllegalTxModeState                                0x10
*/
#define kDescAssertApplLackOfConfirmation                            0x11
/* Obsolete: 
#define kDescAssertUnconfirmedSecureServiceUsed                      0x12
*/
#define kDescAssertZeroStateValue                                    0x13
/* Obsolete: 
#define kDescAssertSecureServiceFunctionallyRequested                0x14
#define kDescAssertInvalidCanChannel                                 0x15
*/
#define kDescAssertInvalidContextMode                                0x16
#define kDescAssertUnexpectedWriteIntoRingBuffer                     0x17
#define kDescAssertRingBufferWriteExceedsTheResLen                   0x18
/* Obsolete: 
#define kDescAssertIllegalUsageOfRingBufferWithPidListMode           0x19 
#define kDescAssertIllegalUsageOfNegativeResponse                    0x1A
*/
#define kDescAssertDiagnosticBufferOverflow                          0x1B
#define kDescAssertFuncReqWoResMayNotUseRingBuffer                   0x1C
/* Obsolete: 
#define kDescAssertContextChannelRelationLost                        0x1D
*/
#define kDescAssertSchedulerTimerEventWithoutAnyPID                  0x1E
#define kDescAssertSchedulerRingBufferIsActivated                    0x1F
/* Obsolete: 
#define kDescAssertSchedulerWrongContextMode                         0x20
*/
#define kDescAssertUnknownTpTransmissionType                         0x21
#define kDescAssertIllegalAddRequestCount                            0x22
#define kDescAssertNoSidCanBeReportedInIdleMode                      0x23
#define kDescAssertInvalidUsageOfForceRcrRpApi                       0x24
/* Obsolete: 
#define kDescAssertRoeResponderWrongContextMode                      0x25
*/
#define kDescAssertPidResLenToCddDefNotMatched                       0x26
#define kDescAssertPidResLenToCurrLinearFreeSpace                    0x27
#define kDescAssertMissingDataForTransmission                        0x28
#define kDescAssertSchedulerFreeCellNotFound                         0x29
#define kDescAssertInvalidStateParameterValue                        0x2A
#define kDescAssertNoFreeICNChannel                                  0x2B
#define kDescAssertInvalidDescICNClient                              0x2C
#define kDescAssertNoFreeMsgContext                                  0x2D
#define kDescAssertUnExpectedContextWithResponse                     0x2E
#define kDescAssertIllegalCallOfRingBufferCancel                     0x2F
#define kDescAssertIllegalUsageOfRingBufferOnSupprPosRes             0x30
#define kDescAssertWrongFblPosResParameterValue                      0x31 /* former 0xA1 */

#define kDescAssertRoeUnexpectedEventNRC                             0x32
#define kDescAssertRoeUnexpectedEventSid                             0x33
/* Obsolete
#define kDescAssertRoeGeneralTransmissionError                       0x34
#define kDescAssertRoeNumEventsIsEmpty                               0x35
*/
#define kDescAssertRoeUnexpectedEventType                            0x36

#define kDescAssertMemByAddrUnexpectedType                           0x37
#define kDescAssertRoeUnexpectedResultLength                         0x38

/* DescNet assertions numbers */
#define kDescNetAssertWrongIsoTpRxChannel                            0x40
#define kDescNetAssertWrongIsoTpTxChannel                            0x41
#define kDescNetAssertWrongBusType                                   0x42

#define kDescNetAssertIllegalPduId                                   0x43




/* DescICNNet assertions numbers */
#define kDescAssertDescIcnIllegalTargetPointer                       0x50

/* up to 0x80 - desc core, up to 0x90 - RDPI, up to 0xA0 - RDI 
 */
#define kDescAssertUudtBufferAlreadyUnlocked                         0xA0
#define kDescAssertWrongUudtTransmitterHandle                        0xA1
#define kDescAssertUudtBufferStillLocked                             0xA2

/* Wrong post processing Id for programming mode */
#define kDescAssertIllegalPostProgModeId                             0xA3

/* -----------------------------------------------------------------------------
    &&&~ Negative response codes
 ----------------------------------------------------------------------------- */

#define kDescNrcGeneralReject                                        0x10
#define kDescNrcServiceNotSupported                                  0x11
#define kDescNrcSubfunctionNotSupported                              0x12
#define kDescNrcInvalidFormat                                        0x12
#define kDescNrcBusyRepeatRequest                                    0x21
#define kDescNrcConditionsNotCorrect                                 0x22
#define kDescNrcRequestSequenceError                                 0x22
#define kDescNrcRoutineNotCompleted                                  0x23
#define kDescNrcRequestOutOfRange                                    0x31
#define kDescNrcAccessDenied                                         0x33
#define kDescNrcInvalidKey                                           0x35
#define kDescNrcExceedNumOfAttempts                                  0x36
#define kDescNrcTimeDelayNotExpired                                  0x37
#define kDescNrcDownloadNotAccepted                                  0x40
#define kDescNrcImproperDownloadType                                 0x41
#define kDescNrcCantDownloadToAddress                                0x42
#define kDescNrcCantDownloadNumOfBytes                               0x43
#define kDescNrcUploadNotAccepted                                    0x50
#define kDescNrcImproperUploadType                                   0x51
#define kDescNrcCantUploadFromAddress                                0x52
#define kDescNrcCantUploadNumOfBytes                                 0x53
#define kDescNrcTransferSuspended                                    0x71
#define kDescNrcTransferAborted                                      0x72
#define kDescNrcIllegalAddressInBlockTransfer                        0x74
#define kDescNrcIllegalByteCountInBlockTransfer                      0x75
#define kDescNrcIllegalBlockTransferType                             0x76
#define kDescNrcBlockTransferDataChecksumError                       0x77
#define kDescNrcResponsePending                                      0x78
#define kDescNrcIncorrectByteCntDgBlockTransfer                      0x79
#define kDescNrcServiceNotSupportedInActiveMode                      0x80
#define kDescNrcSchedulerFull                                        0x81
#define kDescNrcVoltageRangeFault                                    0x83
#define kDescNrcProgramFailure                                       0x85
#define kDescNrcDeviceTypeError                                      0x89
#define kDescNrcReady_for_download_DTC_stored                        0x99
#define kDescNrcDeviceControlLimitExceeded                           0xE3


#define TP_CHANNEL_PARAM_TYPE                                        vuint8
#define TP_CHANNEL_RX_PARAM_NAME                                     tpRxChannel
#define TP_CHANNEL_TX_PARAM_NAME                                     tpTxChannel

#if defined (DESC_USDTNET_ENABLE_MULTI_TP)
/* rx */
# define TP_CHANNEL_RX_FORMAL_PARAM_DEF_ONLY                         TP_CHANNEL_PARAM_TYPE TP_CHANNEL_RX_PARAM_NAME
# define TP_CHANNEL_RX_PARAM_DEF_LOCAL                               TP_CHANNEL_RX_FORMAL_PARAM_DEF_ONLY;
# define TP_CHANNEL_RX_FORMAL_PARAM_DEF_FIRST                        TP_CHANNEL_RX_FORMAL_PARAM_DEF_ONLY,
# define TP_CHANNEL_RX_PARAM_IGNORE_UNREF                            DESC_IGNORE_UNREF_PARAM(TP_CHANNEL_RX_PARAM_NAME)
/* tx */
# define TP_CHANNEL_TX_FORMAL_PARAM_DEF_ONLY                         TP_CHANNEL_PARAM_TYPE TP_CHANNEL_TX_PARAM_NAME
# define TP_CHANNEL_TX_PARAM_DEF_LOCAL                               TP_CHANNEL_TX_FORMAL_PARAM_DEF_ONLY;
# define TP_CHANNEL_TX_FORMAL_PARAM_DEF_FIRST                        TP_CHANNEL_TX_FORMAL_PARAM_DEF_ONLY,
# define TP_CHANNEL_TX_PARAM_IGNORE_UNREF                            DESC_IGNORE_UNREF_PARAM(TP_CHANNEL_TX_PARAM_NAME)
#else
/* rx */
# define TP_CHANNEL_RX_FORMAL_PARAM_DEF_ONLY                         void
# define TP_CHANNEL_RX_PARAM_DEF_LOCAL
# define TP_CHANNEL_RX_FORMAL_PARAM_DEF_FIRST
# define TP_CHANNEL_RX_PARAM_IGNORE_UNREF
/* tx */
# define TP_CHANNEL_TX_FORMAL_PARAM_DEF_ONLY                         void
# define TP_CHANNEL_TX_PARAM_DEF_LOCAL
# define TP_CHANNEL_TX_FORMAL_PARAM_DEF_FIRST
# define TP_CHANNEL_TX_PARAM_IGNORE_UNREF
#endif

#define DESC_USDTNET_CONST_MEM_ABSTRACT                              const
/* Compile memory model abstraction */
#if defined(DESC_USDTNET_ENABLE_FAR_BUFFER)
/* Ram Pointer to Far Ram */
# define DESC_USDTNET_P2FARRAM(baseType)                             V_MEMRAM1_FAR baseType V_MEMRAM2_FAR V_MEMRAM3_FAR *
/* DESC_CONSTP2FARRAM is not used until now.
DESC_USDTNET_CONST_MEM_ABSTRACT is defined to const and not
explicit mapped to the ROM*/
# define DESC_USDTNET_CONSTP2FARRAM(baseType)                        V_MEMRAM1_FAR baseType V_MEMRAM2_FAR V_MEMRAM3_FAR * DESC_USDTNET_CONST_MEM_ABSTRACT
# define DESC_USDTNET_PUBL_DEF_VAR_FAR(baseType)                     V_MEMRAM0 V_MEMRAM1_FAR baseType V_MEMRAM2_FAR V_MEMRAM3_FAR
# define DESC_USDTNET_PRVT_DEF_VAR_FAR(baseType)                     V_MEMRAM0 static V_MEMRAM1_FAR baseType V_MEMRAM2_FAR
# define DESC_USDTNET_PUBL_DECL_VAR_FAR(baseType)                    V_MEMRAM0 extern V_MEMRAM1_FAR baseType V_MEMRAM2_FAR
#else /*DESC_USDTNET_ENABLE_FAR_BUFFER*/
# define DESC_USDTNET_P2FARRAM(baseType)                             V_MEMRAM1 baseType V_MEMRAM2 V_MEMRAM3 *
/* DESC_CONSTP2FARRAM is not used until now.
DESC_USDTNET_CONST_MEM_ABSTRACT is defined to const and not
explicit mapped to the ROM*/
# define DESC_USDTNET_CONSTP2FARRAM(baseType)                        V_MEMRAM1 baseType V_MEMRAM2 V_MEMRAM3 * DESC_USDTNET_CONST_MEM_ABSTRACT
# define DESC_USDTNET_PUBL_DEF_VAR_FAR(baseType)                     V_MEMRAM0 V_MEMRAM1 baseType V_MEMRAM2 V_MEMRAM3
# define DESC_USDTNET_PRVT_DEF_VAR_FAR(baseType)                     V_MEMRAM0 static V_MEMRAM1 baseType V_MEMRAM2
# define DESC_USDTNET_PUBL_DECL_VAR_FAR(baseType)                    V_MEMRAM0 extern V_MEMRAM1 baseType V_MEMRAM2
#endif

/* A special CAN channel value to mark free objects /channels*/
#define kDescUudtNetNoCanChannel                                     ((vuint8)(0xFF))

#define kDescUudtNetQueueSize                                        2
#define kDescUudtNetNumEcus                                          1
#define kDescUudtNetNumCanMsgs                                       2
#define kDescUudtNetConfTimeout                                      100
#define kDescUudtNetCycleCallTime                                    10
#define kDescNumCommChannels                                         2
#define kDescCanChannel                                              0
#define kDescNumContexts                                             3
#define kDescPrimBufferLen                                           900
#if defined (DESC_ENABLE_MULTI_CHANNEL_SUPPORT)
# define DESC_COMM_CHANNEL_FORMAL_PARAM_DEF_ONLY                     vuint8_least commChannel
# define DESC_COMM_CHANNEL_FORMAL_PARAM_DEF_FIRST                    DESC_COMM_CHANNEL_FORMAL_PARAM_DEF_ONLY,
# define DESC_COMM_CHANNEL_PARAM_VALUE                               commChannel
# define DESC_COMM_CHANNEL_PARAM_ONLY                                commChannel
# define DESC_COMM_CHANNEL_PARAM_FIRST                               DESC_COMM_CHANNEL_PARAM_ONLY,
# define DESC_COMM_CHANNEL_LOCAL_PARAM_DEF                           DESC_COMM_CHANNEL_FORMAL_PARAM_DEF_ONLY;
# define DESC_COMM_CHANNEL_PARAM_VALUE_INIT                          DESC_COMM_CHANNEL_PARAM_VALUE = kDescNumCommChannels
# define DESC_COMM_CHANNEL_PARAM_VALUE_DEC                           DESC_COMM_CHANNEL_PARAM_VALUE--
# define DESC_COMM_CHANNEL_LOOP                                      while(commChannel != 0)
# define DESC_COMM_CHANNEL_PARAM_WRAP_ONLY(channel)                  (channel)
# define DESC_COMM_CHANNEL_PARAM_WRAP_INDEX(channel)                 (channel)
#else
# define DESC_COMM_CHANNEL_FORMAL_PARAM_DEF_ONLY                     void
# define DESC_COMM_CHANNEL_FORMAL_PARAM_DEF_FIRST
# define DESC_COMM_CHANNEL_PARAM_ONLY
# define DESC_COMM_CHANNEL_PARAM_FIRST
# define DESC_COMM_CHANNEL_PARAM_VALUE                               0
# define DESC_COMM_CHANNEL_LOCAL_PARAM_DEF
# define DESC_COMM_CHANNEL_PARAM_VALUE_INIT
# define DESC_COMM_CHANNEL_PARAM_VALUE_DEC
# define DESC_COMM_CHANNEL_LOOP
# define DESC_COMM_CHANNEL_PARAM_WRAP_ONLY(channel)
# define DESC_COMM_CHANNEL_PARAM_WRAP_INDEX(channel)                 0
#endif

/* If more than one parallel request may be processed - use real context */
#if (kDescNumContexts > 1)
# define DESC_CONTEXT_PARAM_TYPE_ONLY                                vuint8                                                /* Used in CANdesc for function prototypes */
# define DESC_CONTEXT_PARAM_TYPE_FIRST                               vuint8,                                               /* Used in CANdesc for function prototypes */
# define DESC_CONTEXT_PARAM_VALUE                                    iContext                                              /* Used in CANdesc context accesses as "g_descMsgContext[DESC_CONTEXT_PARAM_VALUE].reqDataLen" in case the parameter is defined using the other optimization macros */
# define DESC_CONTEXT_PARAM_ONLY                                     iContext                                              /* Used in application/CANdesc functions as DescProcessingDone(DESC_CONTEXT_PARAM_ONLY), in case the parameter is defined using the other optimization macros */
# define DESC_CONTEXT_PARAM_FIRST                                    iContext,                                             /* Used in application/CANdesc functions as DescSetNegResponse(DESC_CONTEXT_PARAM_FIRST, kDescNrcCode), in case the parameter is defined using the other optimization macros */
# define DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY                          DESC_CONTEXT_PARAM_TYPE_ONLY DESC_CONTEXT_PARAM_ONLY  /* Used in application/CANdesc functions as DescProcessingDone(DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY);*/
# define DESC_CONTEXT_PARAM_DEF_LOCAL                                DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY;                   /* Used in functions as a local variable definition so it can be used with all other optimization macros */
# define DESC_CONTEXT_FORMAL_PARAM_DEF_FIRST                         DESC_CONTEXT_PARAM_TYPE_ONLY DESC_CONTEXT_PARAM_ONLY, /* Used in application/CANdesc functions as ApplDescPostHandler(DESC_CONTEXT_FORMAL_PARAM_DEF_FIRST vuint8 status) */
# define DESC_CONTEXT_PARAM_WRAPPER_ONLY(contextConst)               contextConst                                          /* Used in call backs as DescProcessingDone(DESC_CONTEXT_PARAM_WRAPPER_ONLY(pMsgContext->iContext)) as universal ignore parameter macro */
# define DESC_CONTEXT_PARAM_WRAPPER_FIRST(contextConst)              contextConst,                                         /* Used in call backs as DescSetNegResponse(DESC_CONTEXT_PARAM_WRAPPER_FIRST(pMsgContext->iContext) kDescNrcConditionsNotCorrect) as universal ignore parameter macro */
# define DESC_CONTEXT_PARAM_WRAPPER_INDEX(contextConst)              contextConst                                          /* Used for accessing context specific tables */
# define DESC_CONTEXT_PARAM_DUMMY_USE                                DESC_IGNORE_UNREF_PARAM(DESC_CONTEXT_PARAM_ONLY)      /* Used to avoid compiler warnings for unreferenced variables */
#else
# define DESC_CONTEXT_PARAM_TYPE_ONLY                                void
# define DESC_CONTEXT_PARAM_TYPE_FIRST
# define DESC_CONTEXT_PARAM_VALUE                                    ((vuint8)0)
# define DESC_CONTEXT_PARAM_ONLY
# define DESC_CONTEXT_PARAM_FIRST
# define DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY                          void
# define DESC_CONTEXT_FORMAL_PARAM_DEF_FIRST
# define DESC_CONTEXT_PARAM_DEF_LOCAL
# define DESC_CONTEXT_PARAM_WRAPPER_ONLY(contextConst)
# define DESC_CONTEXT_PARAM_WRAPPER_FIRST(contextConst)
# define DESC_CONTEXT_PARAM_WRAPPER_INDEX(contextConst)              0
# define DESC_CONTEXT_PARAM_DUMMY_USE
#endif

/* Diag connection number (in case of TPMC with DYN_ID usage) */
#if ! defined(kDescDiagConnection)
# define kDescDiagConnection                                         ((vuint8)0xF0)
#endif

#if ! defined(kDescDiagObdConnection)
# define kDescDiagObdConnection                                      ((vuint8)0xF1)
#endif

#if ! defined(kDescDiagAddConnection)
# define kDescDiagAddConnection                                      ((vuint8)0xF2)
#endif

/* -- Context specific activity states -- */
#define kDescContextIdle                                             ((DescContextActivity)0x00)
#define kDescContextActiveRxBegin                                    ((DescContextActivity)0x01)
#define kDescContextActiveRxEnd                                      ((DescContextActivity)0x02)
#define kDescContextActiveProcess                                    ((DescContextActivity)0x04)
#define kDescContextActiveProcessEnd                                 ((DescContextActivity)0x08)
#define kDescContextActiveTxReady                                    ((DescContextActivity)0x10)
#define kDescContextActiveTx                                         ((DescContextActivity)0x20)
#define kDescContextActivePostProcess                                ((DescContextActivity)0x40)

/* Any transmission is currently active */
#define kDescContextActiveRx                                         (DescContextActivity)(kDescContextActiveRxBegin | kDescContextActiveRxEnd)


/* ---  Addressing methods  --- */
#define kDescPhysReq                                                 ((vuint8)0x01)
#define kDescFuncReq                                                 ((vuint8)0x02)

#define kDescPrimContext                                             (vuint8) 0
#define kDescSecContext                                              (vuint8) 1
#define kDescReadDynDpidContext                                      (vuint8) 2
#define kDescEcuAddress                                              0x31
#define kDescVnDiagTimerTicks                                        800
#define kDescP2Ticks                                                 9
#define kDescP3maxTicks                                              499
#define kDescCallCycleUs                                             10000
#define kDescS1TimerTicks                                            500
#define kDescStateValueInvalid                                       (DescStateGroup)0xFFFF

/* CANdesc supports at maximum as many states pro StateGroup as given below: */
#define kDescMaxAllowedNumStates                                     16
#define kDescNumStateSecurity_Access                                 4
#define kDescStateSecurity_AccessLock                                ((DescStateGroup)0x01)
#define kDescStateSecurity_AccessSPS_Unlock                          ((DescStateGroup)0x02)
#define kDescStateSecurity_AccessCPID_Unlock                         ((DescStateGroup)0x04)
#define kDescStateSecurity_AccessNxtr_Unlock                      ((DescStateGroup)0x08)
#define kDescNumStateDiagnostic_Mode                                 3
#define kDescStateDiagnostic_ModeEnableDTCsDuringDevCtrl             ((DescStateGroup)0x01)
#define kDescStateDiagnostic_ModeDisableAllDTCs                      ((DescStateGroup)0x02)
#define kDescStateDiagnostic_ModeNxtr_Mode                        ((DescStateGroup)0x04)
#define kDescNumStateDevice_Control                                  2
#define kDescStateDevice_ControlActive                               ((DescStateGroup)0x01)
#define kDescStateDevice_ControlNot_Active                           ((DescStateGroup)0x02)
#define kDescNumStateMEC                                             2
#define kDescStateMECEnabled                                         ((DescStateGroup)0x01)
#define kDescStateMECDisabled                                        ((DescStateGroup)0x02)
/* ---- Communication states ---- */
#define kDescCommDisabled                                            0x01
#define kDescCommEnabled                                             0x02

#define kDescCommInitial                                             kDescCommEnabled

/* ---- Programming states ---- */
#define kDescProgModeIdle                                            0x01
#define kDescProgModeAccepted                                        0x02
#define kDescProgModeActive                                          0x04

#define kDescProgModeInitial                                         kDescProgModeIdle

#if defined (DESC_ENABLE_REQ_HISPEED_PROG)
/* ---- Programming states ---- */
# define kDescHiSpeedModeIdle                                        0x01
# define kDescHiSpeedModeAccepted                                    0x02
# define kDescHiSpeedModeActive                                      0x04

# define kDescHiSpeedModeInitial                                     kDescHiSpeedModeIdle
#endif

/* Override defaults */
#define kDescOemNrcParamIdNotSupportedInSecurityState                kDescNrcRequestOutOfRange

/* Error free diagnsotic request process */
#define kDescNrcNone                                                 ((DescNegResCode)0x00)
#define kDescExtNrcNone                                              ((vuint16)0x0000)

/* ---  Post handler status masks --- */
#define kDescPostHandlerStateOk                                      ((vuint8)0x01)
#define kDescPostHandlerStateNegResSent                              ((vuint8)0x02)
#define kDescPostHandlerStateTxFailed                                ((vuint8)0x04)

/* Default BOOT state */
#define kDescPowerOnInitParam                                        (DescInitParam)0

/* till 0x80 are core assertion codes */
/* till 0x90 are RDPI assertion codes */
#define kDescAssertInvalidA9Mode                                     0x91

#define kDescRdpiDpidNumItems                                        4
#define kDescNumOfPeriodicPids                                       4
#define kDescRdpiSlowRateTicks                                       100
#define kDescRdpiMediumRateTicks                                     20
#define kDescRdpiFastRateTicks                                       3
#define kDescRdpiTableBottomOffset                                   0
#define kDescRdpiTableTopOffset                                      0
#define kDescRdpiDpidSearchTableSize                                 32
/* till 0x80 are core assertion codes */
#define kDescAssertInvalidDpidHandle                                 0x80
#define kDescAssertNoScheduledDpidsButSchedulingActive               0x81
#define kDescAssertDpidListInvalidReference                          0x82
#define kDescAssertDpidListInvalidCount                              0x83



/* -----------------------------------------------------------------------------
    &&&~ Datatype definitions
 ----------------------------------------------------------------------------- */

/* CANdesc internal boolean type (used for better code readability and code optimum) */
typedef vboolean DescBool;
#if defined (DESC_USE_ANSI_C_BIT_TYPE)
typedef unsigned int DescBitType;
#else
typedef vbittype     DescBitType;
#endif


typedef struct t_AddrInfoIsoTpTag
{
#if defined (TP_ENABLE_SINGLE_CHANNEL_TP)
  vuint8  Dummy;
#else
  vuint8  Connection;
#endif
#if defined (TP_ENABLE_NORMAL_ADDRESSING)       || \
    defined (TP_ENABLE_MIXED_11_ADDRESSING)
# if defined (TP_ENABLE_DYNAMIC_CHANNELS)
  vuint16 TransmitID;
  vuint16 ReceiveID;
# else
# endif
#endif
#if (TP_USE_EXTENDED_ADDRESSING == kTpOn) || \
    defined (TP_ENABLE_NORMAL_FIXED_ADDRESSING) || \
    defined(TP_FUNC_ENABLE_EXTENDED_ADDRESSING) || \
    defined (TP_ENABLE_MIXED_29_ADDRESSING)
  vuint8 SourceAddress;
  vuint8 TargetAddress;
#endif
#if ( kCanNumberOfChannels > 1 ) /* more than one canChannel ? */
  vuint8 CanChannel;
#endif
#if (TP_USE_EXTENDED_ADDRESSING == kTpOn)
# if (TP_USE_MULTIPLE_BASEADDRESS == kTpOn)
  vuint16 BaseAddress;
# endif
#endif
} t_AddrInfoIsoTp;

typedef enum
{
  kDescIcnClientNone,
  kDescIcnClientDynDefDid,
  kDescIcnClientDynDefDpid,
  kDescIcnClientPeriodicDid,
  kDescIcnClientRoe
}t_DescClients;

typedef struct t_AddrInfoDescICNTag
{
  vuint8          SourceContext;
  vuint8          TargetContext;
  t_DescClients   Client;
} t_AddrInfoDescICN;

/* USDT Net result return type */
typedef enum
{
  kDescUsdtNetworkOk = 0,
  kDescUsdtNetworkFailed = 1,
  kDescUsdtNetBufferUnderrun = 2,
  kDescUsdtNetworkAbort = 3
} t_descUsdtNetResult;

/* CANdesc internal handle type */
typedef vuint8 t_descHandle;

/* USDT Net bus handle type */
typedef vuint8 t_descUsdtNetBusHandle;

typedef enum
{
  kDescUsdtNetReqTypePhysical,
  kDescUsdtNetReqTypeFunctional,
  kDescUsdtNetReqTypeInternal
} t_descUsdtNetReqType;

typedef enum
{
  kDescUsdtResponseNone,
  kDescUsdtResponsePositive,
  kDescUsdtResponseRingBuffer,
  kDescUsdtResponseNegative,
  kDescUsdtResponseNegativeRCR_RP,
  kDescUsdtResponseNegativeApplRCR_RP,
  kDescUsdtResponseRoe,
  kDescUsdtResponsePeriodic,
  kDescUsdtResponseSpontaneous
} t_descUsdtNetResType;

typedef DESC_USDTNET_P2FARRAM(vuint8) DescUsdtNetMsg;

typedef enum
{
  kDescUsdtNetBusTypeNone, 
  kDescUsdtNetBusTypeIsoTp, 
  kDescUsdtNetBusTypeDescICN
} t_descUsdtNetBusType;
typedef union t_descUsdtNetAddrInfoTag
{
  t_AddrInfoIsoTp isoTp;
  t_AddrInfoDescICN descICN;
} t_descUsdtNetAddrInfo;
typedef struct
{
  vuint8                comChannel; /* relevant only on multi-channel systems (e.g. multi CAN channels) */
  vuint8                testerId;   /* in some cases the tester address (ID) is from importance - store here if you have it */
  t_descUsdtNetBusType  busType;        /* from DescUsdtNetDispatcher.h */
  t_descUsdtNetAddrInfo addressingInfo; /* from DescUsdtNetDispatcher.h */
#if defined (DESC_USDTNET_ENABLE_DYNAMIC_BUFFER_LENGTH)
  vuint16               availBufferLength;
#endif
} t_descUsdtNetBus;

typedef vuint8                                        DescContextActivity;
typedef vuint8                                        DescMsgItem;

typedef DESC_P2FARRAM(DescMsgItem)                    DescMsg;
typedef DESC_CONSTP2FARRAM(DescMsgItem)               DescConstPtr;
typedef vuint16                                       DescMsgLen;

/* Some groups can have more than 8 states */
typedef unsigned int DescStateGroup;

/* Negative response codes is normally single Byte */
typedef vuint8 DescNegResCode;
/* Additional information about a request */
typedef struct
{
  DescBitType reqType   :2; /* 0x01: Phys 0x02: Func */
  DescBitType resOnReq  :2; /* 0x01: Phys 0x02: Func */
  DescBitType suppPosRes:1; /* 0x00: No   0x02: Yes  */
} DescMsgAddInfo;

/* Context information of a request */
typedef struct
{
  DescMsg             reqData;
  DescMsgLen          reqDataLen;
  DescMsg             resData;
  DescMsgLen          resDataLen;
  DescMsgAddInfo      msgAddInfo;
  DESC_CONTEXT_PARAM_DEF_LOCAL /* No iContext in non-parallel system */
  t_descUsdtNetBus    busInfo;
} DescMsgContext;

/* Main handler function pointer type */
typedef void DESC_API_CALL_TYPE (*DescMainHandler)     (DescMsgContext*);

#if defined (DESC_ENABLE_EXT_NEG_RES_CODE_HANDLING)
/* Additional error data to be sent with extended negative response */
typedef vuint16 DescExtNegResCode;
#endif

typedef vuint8 DescInitParam;

typedef struct
{
  vuint16 nextIterPos;
  vuint16 dtcNum;
  vuint8  failureTypeByte;
  vuint8  statusByte;
}DescRdiDtcRecord;

typedef enum
{
  kDescDataPacketOk = 0,
  kDescDataPacketFailedSendDummy,
  kDescDataPacketFailedDoNotSend
}DescDataPacketProcessStatus;



/* -----------------------------------------------------------------------------
    &&&~ Function prototypes
 ----------------------------------------------------------------------------- */

#if defined (TP_ENABLE_DYNAMIC_CHANNELS)
/* Rx path phys */
TP_MEMORY_MODEL_DATA vuint8* TP_API_CALLBACK_TYPE DescGetBuffer(TP_CHANNEL_RX_FORMAL_PARAM_DEF_FIRST vuint16 dataLength);
void    TP_API_CALLBACK_TYPE DescRxErrorIndication(TP_CHANNEL_RX_FORMAL_PARAM_DEF_FIRST vuint8 status);
void    TP_API_CALLBACK_TYPE DescPhysReqInd(TP_CHANNEL_RX_FORMAL_PARAM_DEF_FIRST vuint16 dataLen);

/* Rx path func */
# if defined(TP_FUNC_ENABLE_RECEPTION) && \
     !defined (TP_ENABLE_EXTENDED_ADDRESSING)
TP_MEMORY_MODEL_DATA vuint8* TP_API_CALLBACK_TYPE DescGetFuncBuffer(vuint16 dataLength);
void TP_API_CALLBACK_TYPE DescFuncReqInd(vuint16 dataLen);
# endif

/* Tx path */
vuint8 TP_API_CALLBACK_TYPE DescCopyToCAN(TpCopyToCanInfoStructPtr infoStruct);
vuint8 TP_API_CALLBACK_TYPE DescTxErrorIndication(TP_CHANNEL_TX_FORMAL_PARAM_DEF_FIRST vuint8 status);
void   TP_API_CALLBACK_TYPE DescConfirmation(TP_CHANNEL_TX_FORMAL_PARAM_DEF_FIRST vuint8 status);
#endif

#if defined (DESC_UUDTNET_ENABLE_TX_FAILED_SIM)
void DescUudtNetCanDoSimTxFailed(DescBool doSim);
#endif

#if defined (DESC_ENABLE_SPONTANEOUS_RES)
/* ---- Extended functionality ---- */
void DESC_API_CALL_TYPE DescTransmitSingleFrame(DescMsg resData, vuint8 resLen);
#endif

/* Reports the current diagnostic activity state (e.g. Idle, ActiveRx, ActiveProcess, ActiveTx.*/
DescContextActivity DESC_API_CALL_TYPE DescGetActivityState(DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY);

#if defined (DESC_ENABLE_ACCESS_TESTER_ADDRESS_API)
vuint8 DESC_API_CALL_TYPE DescGetTesterAddress(DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY);
#endif

/*Get access to the current communication parameters */
t_descUsdtNetBus* DESC_API_CALL_TYPE DescGetCurrentBusInfo (DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY);

#if defined (DESC_ENABLE_FORCE_RCR_RP)
/* Force CANdesc to send RCR-RP response */
void DESC_API_CALL_TYPE DescForceRcrRpResponse(DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY);
#endif

/* activate tester present timeout monitoring 
 * through application call */
void DescActivateS1Timer(void);

#if defined (DESC_ENABLE_AUTO_STATES)
/* If needed - reset the whole state machine (only the states defined in the CDD!!!) */
void DESC_API_CALL_TYPE DescStateInit(void);
#endif

DescStateGroup DESC_API_CALL_TYPE DescGetStateSecurity_Access(void);
void DESC_API_CALL_TYPE DescSetStateSecurity_Access(DescStateGroup descState);
DescStateGroup DESC_API_CALL_TYPE DescGetStateDiagnostic_Mode(void);
void DESC_API_CALL_TYPE DescSetStateDiagnostic_Mode(DescStateGroup descState);
DescStateGroup DESC_API_CALL_TYPE DescGetStateDevice_Control(void);
void DESC_API_CALL_TYPE DescSetStateDevice_Control(DescStateGroup descState);
DescStateGroup DESC_API_CALL_TYPE DescGetStateMEC(void);
void DESC_API_CALL_TYPE DescSetStateMEC(DescStateGroup descState);
/* Reports the communication state (enabled disabled)*/
vuint8 DescGetCommState(void);
#if defined (DESC_ENABLE_PROGRAMMING_SESSION)
/* Reports the programming state */
vuint8 DescGetProgMode(void);
#endif
/* Reports the hi-speed state (on/off)*/
#if defined (DESC_ENABLE_REQ_HISPEED_PROG)
vuint8 DescGetHiSpeedMode(void);
#endif

#if defined(DESC_ENABLE_QNX_CONTEXT_SWITCH)
/* Context switch support */
void DescSetCommState(DESC_COMM_CHANNEL_FORMAL_PARAM_DEF_FIRST vuint8 state);
# if defined (DESC_ENABLE_PROGRAMMING_SESSION)
void DescSetProgMode(vuint8 state);
# endif
# if defined (DESC_ENABLE_REQ_HISPEED_PROG)
void DescSetHiSpeedMode(vuint8 state);
# endif
#endif

#if defined (DESC_ENABLE_MAINHANDLER_MULTICALL)
/* Use this function if you want your application to be polled for a certain service */
void DESC_API_CALL_TYPE DescStartRepeatedServiceCall(DESC_CONTEXT_FORMAL_PARAM_DEF_FIRST DescMainHandler mainHandler);
#endif
/* Activate linear response transmission */
void DESC_API_CALL_TYPE DescProcessingDone(DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY);
/* Set a diagnostic error */
void DESC_API_CALL_TYPE DescSetNegResponse(DESC_CONTEXT_FORMAL_PARAM_DEF_FIRST DescNegResCode errorCode);
#if defined(DESC_ENABLE_GENERIC_USER_SERVICE_SUPPORT)
/* Returns the current service's Sid */
DescMsgItem DESC_API_CALL_TYPE DescGetServiceId(DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY);
#endif

#if defined (DESC_ENABLE_EXT_NEG_RES_CODE_HANDLING)
void DescSetExtNegResponse(DESC_CONTEXT_FORMAL_PARAM_DEF_FIRST DescNegResCode errorCode, DescExtNegResCode  extErrorCode);
#endif

/* Initilize the CANdesc on PowerOnReset using this function */
void DESC_API_CALL_TYPE DescInitPowerOn(DescInitParam initParam);
/* Initilize the CANdesc if needed during the ECU  runtime using this function (status reset) */
void DESC_API_CALL_TYPE DescInit(DescInitParam initParam);

/* DescTask function must be call cyclically in the specified period of time */
void DESC_API_CALL_TYPE DescTask(void);

void DESC_API_CALL_TYPE DescTimerTask(void);
void DESC_API_CALL_TYPE DescStateTask(void);

/* $A9 $81 */
void DescRdiDtcStatusByMaskFound(DescRdiDtcRecord *pDtcReport);
void DescRdiDtcStatusByMaskNotFound(vuint8 dtcSam);

void DescDataPacketProcessingDone(DescDataPacketProcessStatus status);

/* Hi-performance processing */
#if defined (DESC_ENABLE_HIPERFORMANCE_DYNDID_MODE)
DescBool DescMayCallStateTaskAgain(void);
#endif



/* -----------------------------------------------------------------------------
    &&&~ ROM definitions
 ----------------------------------------------------------------------------- */

/* Version information */
V_MEMROM0 extern V_MEMROM1 vuint8 V_MEMROM2 g_descMainVersion;
V_MEMROM0 extern V_MEMROM1 vuint8 V_MEMROM2 g_descSubVersion;
V_MEMROM0 extern V_MEMROM1 vuint8 V_MEMROM2 g_descBugFixVersion;



/* -----------------------------------------------------------------------------
    &&&~ Macro definitions
 ----------------------------------------------------------------------------- */

#if defined (DESC_ENABLE_FAR_BUFFER)
/* Copy RAM->FAR RAM */
# define DescCopyNByteRAM(t,s,l)                                     (VStdMemCpyRamToFarRam((t),(s),(l)))
/* Copy ROM->FAR RAM */
# define DescCopyNByteROM(t,s,l)                                     (VStdMemCpyRomToFarRam((t),(s),(l)))

# define DescMsgCopyRamToRam(t,s,l)                                  (VStdMemCpyRamToRam((t),(s),(l)))
# define DescMsgCopyFarRamToRam(t,s,l)                               (VStdMemCpyFarRamToRam((t),(s),(l)))
# define DescMsgCopyRamToFarRam(t,s,l)                               (VStdMemCpyRamToFarRam((t),(s),(l)))
# define DescMsgCopyFarRamToFarRam(t,s,l)                            (VStdMemCpyFarRamToFarRam((t),(s),(l)))
# define DescMsgCopyRomToRam(t,s,l)                                  (VStdMemCpyRomToRam((t),(s),(l)))
# define DescMsgCopyRomToFarRam(t,s,l)                               (VStdMemCpyRomToFarRam((t),(s),(l)))
#else
/* TMS320 specifics */
# if defined (VStdMemCpyRamToRamElement)
#  define DescWrapCpyRamToRam(t,s,l)                                 (VStdMemCpyRamToRamElement((t),(s),(l)))
#  define DescWrapCpyRomToRam(t,s,l)                                 (VStdMemCpyRomToRamElement((t),(s),(l)))
# else
#  define DescWrapCpyRamToRam(t,s,l)                                 (VStdMemCpyRamToRam((t),(s),(l)))
#  define DescWrapCpyRomToRam(t,s,l)                                 (VStdMemCpyRomToRam((t),(s),(l)))
# endif
/* Copy RAM->RAM */
# define DescCopyNByteRAM(t,s,l)                                     (DescWrapCpyRamToRam((t),(s),(l)))
/* Copy ROM->RAM */
# define DescCopyNByteROM(t,s,l)                                     (DescWrapCpyRomToRam((t),(s),(l)))

# define DescMsgCopyRamToRam(t,s,l)                                  (DescWrapCpyRamToRam((t),(s),(l)))
# define DescMsgCopyFarRamToRam(t,s,l)                               (DescWrapCpyRamToRam((t),(s),(l)))
# define DescMsgCopyRamToFarRam(t,s,l)                               (DescWrapCpyRamToRam((t),(s),(l)))
# define DescMsgCopyFarRamToFarRam(t,s,l)                            (DescWrapCpyRamToRam((t),(s),(l)))
# define DescMsgCopyRomToRam(t,s,l)                                  (DescWrapCpyRomToRam((t),(s),(l)))
# define DescMsgCopyRomToFarRam(t,s,l)                               (DescWrapCpyRomToRam((t),(s),(l)))
#endif

/* Global initialization of the state machine */
#if defined (DESC_ENABLE_AUTO_STATES)
/* Func prototype is used */
#else
# define DescStateInit()                                             /* Not used */
#endif

/* Data assemble/deassemble macros */
/* compose from byte stream a 16 bit data */
#define DescMake16Bit(hiByte,loByte)                                 ((vuint16)((((vuint16)(hiByte))<<8)| \
                                                                     ((vuint16)(loByte))))
/* compose from byte stream a 32 bit data */
#define DescMake32Bit(hiHiByte,hiLoByte,loHiByte,loLoByte)           ((vuint32)((((vuint32)(hiHiByte))<<24)| \
                                                                     (((vuint32)(hiLoByte))<<16)| \
                                                                     (((vuint32)(loHiByte))<<8) | \
                                                                     ((vuint32)(loLoByte))))
/* decompose 16 bit data in byte stream */
#define DescGetHiByte(data)                                          ((vuint8)(((vuint16)(data))>>8))
#define DescGetLoByte(data)                                          ((vuint8)(data))

/* decompose 32 bit data in byte stream */
#define DescGetHiHiByte(data)                                        ((vuint8)(((vuint32)(data))>>24))
#define DescGetHiLoByte(data)                                        ((vuint8)(((vuint32)(data))>>16))
#define DescGetLoHiByte(data)                                        ((vuint8)(((vuint32)(data))>>8))
#define DescGetLoLoByte(data)                                        ((vuint8)(data))



#endif /* __DESC_H__ */
