/* -----------------------------------------------------------------------------
  Filename:    drv_par.h
  Description: Toolversion: 08.31.00.01.01.01.23.01.00.00
                
                Serial Number: CBD1010123
                Customer Info: Nxtr
                               Package: GM GMLAN_30_Indx 
                               Micro: TI TMS570 TMS570X5LS20216
                               Compiler: Code Composer Studio 4.6.4
                
                
                Generator Fwk   : GENy 
                Generator Module: GenTool_GenyDriverBase
                
                Configuration   : C:\_synergy\9BXX_CZ8L9T\GM_9BXX_EPS_TMS570\Tools\AsrProject\GENy\RT_2.0_Mod.gny
                
                ECU: 
                        TargetSystem: Hw_Tms470/570Cpu (Dcan)
                        Compiler:     TexasInstruments
                        Derivates:    TMS570PSFC66
                
                Channel "Channel0":
                        Databasefile: C:\_synergy\9BXX_CZ8L9T\GM_9BXX_EPS_TMS570\Tools\AsrProject\GENy\GlobalA_HS.dbc
                        Bussystem:    CAN
                        Manufacturer: General Motors
                        Node:         EPS_HS
                Channel "Channel1":
                        Databasefile: C:\Synergy\GM_C1XX_EPS_TMS570-zz4r1x1\GM_C1XX_EPS_TMS570\Tools\AsrProject\GENy\GlobalA_CE.dbc
                        Bussystem:    CAN
                        Manufacturer: General Motors
                        Node:         EPS_CE

  Generated by , 2016-04-28  10:27:04
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2008 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__DRV_PAR_H__)
#define __DRV_PAR_H__

#include "nm_cfg.h"

/* -----------------------------------------------------------------------------
    &&&~ Signal Structures
 ----------------------------------------------------------------------------- */

typedef struct _c_PPEI_Hybrid_General_Status_3_HS_msgTypeTag
{
  vbittype ActAxleTrqV : 1;
  vbittype ActAxleTrq_1 : 7;
  vbittype ActAxleTrq_0 : 8;
} _c_PPEI_Hybrid_General_Status_3_HS_msgType;
typedef struct _c_PPEI_Hybrid_General_Status_3_HS_ActAxleTrqGroup_msgTypeTag
{
  vbittype ActAxleTrqGroup_1 : 8;
  vbittype ActAxleTrqGroup_0 : 8;
} _c_PPEI_Hybrid_General_Status_3_HS_ActAxleTrqGroup_msgType;
typedef struct _c_Wheel_Pulses_HS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlPlsPerRevDrvn_0 : 7;
  vbittype unused1 : 1;
  vbittype WhlPlsPerRevNonDrvn_0 : 7;
  vbittype unused2 : 5;
  vbittype WhlRotStatTmstmpRes_1 : 3;
  vbittype WhlRotStatTmstmpRes_0 : 8;
} _c_Wheel_Pulses_HS_msgType;
typedef struct _c_Driving_Mode_Control_HS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 2;
  vbittype StgSysPerfMdRq : 3;
  vbittype unused4 : 3;
  vbittype DrvMdCntrlState : 8;
} _c_Driving_Mode_Control_HS_msgType;
typedef struct _c_Brake_Pedal_Driver_Status_HS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 6;
  vbittype AutoBrkngAvlbl : 1;
  vbittype unused3 : 1;
  vbittype unused4 : 8;
  vbittype RedntVSEAct : 1;
  vbittype RedntVSEActARC : 2;
  vbittype unused5 : 5;
  vbittype unused6 : 1;
  vbittype ABSActvProt : 1;
  vbittype ABSActvProtARC : 2;
  vbittype ABSActvProtPVal : 2;
  vbittype unused7 : 2;
} _c_Brake_Pedal_Driver_Status_HS_msgType;
typedef struct _c_Power_Steering_Information_HS_msgTypeTag
{
  vbittype unused0 : 4;
  vbittype StrAsstRdcdLvl3IO : 1;
  vbittype StrAsstRdcdLvl2IO : 1;
  vbittype StrngAsstRdcdIO : 1;
  vbittype PwrStrIO : 1;
} _c_Power_Steering_Information_HS_msgType;
typedef struct _c_DTC_Triggered_778_msgTypeTag
{
  vbittype DTCIUnused1_778 : 1;
  vbittype DTCIUnused2_778 : 1;
  vbittype DTCIUnused3_778 : 1;
  vbittype DTCIUnused4_778 : 1;
  vbittype DTCIUnused5_778 : 1;
  vbittype DTCIUnused6_778 : 1;
  vbittype DTCIUnused7_778 : 1;
  vbittype DTCI_DTCTriggered_778 : 1;
  vbittype DTCI_DTCSource_778 : 8;
  vbittype DTCI_DTCNumber_778_1 : 8;
  vbittype DTCI_DTCNumber_778_0 : 8;
  vbittype DTCI_DTCFailType_778 : 8;
  vbittype DTCI_WrnIndRqdSt_778 : 1;
  vbittype DTCI_TstFldPwrUpSt_778 : 1;
  vbittype DTCI_TstNPsdPwrUpSt_778 : 1;
  vbittype DTCI_HistStat_778 : 1;
  vbittype DTCI_TstFldCdClrdStat_778 : 1;
  vbittype DTCI_TstNPsdCdClrdSt_778 : 1;
  vbittype DTCI_CurrentStatus_778 : 1;
  vbittype DTCI_CodeSupported_778 : 1;
  vbittype DTCI_DTCFaultType_778 : 8;
} _c_DTC_Triggered_778_msgType;
typedef struct _c_DTC_Triggered_778_DTCInfo_778_msgTypeTag
{
  vbittype DTCInfo_778_6 : 8;
  vbittype DTCInfo_778_5 : 8;
  vbittype DTCInfo_778_4 : 8;
  vbittype DTCInfo_778_3 : 8;
  vbittype DTCInfo_778_2 : 8;
  vbittype DTCInfo_778_1 : 8;
  vbittype DTCInfo_778_0 : 8;
} _c_DTC_Triggered_778_DTCInfo_778_msgType;
typedef struct _c_PPEI_Steering_Wheel_Angle_msgTypeTag
{
  vbittype StrWhAngV_0 : 1;
  vbittype StrWhlAngSenCalStat_0 : 2;
  vbittype StrWhlAngSenTyp_0 : 2;
  vbittype StrWhAngMsk_0 : 1;
  vbittype unused0 : 2;
  vbittype StrWhAng_0_1 : 8;
  vbittype StrWhAng_0_0 : 8;
  vbittype StrWhAngGrdV_0 : 1;
  vbittype StWhlAngAliveRollCnt_0 : 2;
  vbittype StrWhAngGrdMsk_0 : 1;
  vbittype StrWhAngGrd_0_1 : 4;
  vbittype StrWhAngGrd_0_0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 5;
  vbittype StrAngSnsChksm_0_1 : 3;
  vbittype StrAngSnsChksm_0_0 : 8;
} _c_PPEI_Steering_Wheel_Angle_msgType;
typedef struct _c_PPEI_Steering_Wheel_Angle_StrWhAngGroup_0_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype cunused2 : 2;
  vbittype cunused1 : 2;
  vbittype cunused0 : 1;
  vbittype unused1 : 2;
  vbittype StrWhAngGroup_0_1 : 8;
  vbittype StrWhAngGroup_0_0 : 8;
  vbittype unused2 : 1;
  vbittype cunused4 : 2;
  vbittype cunused3 : 1;
  vbittype unused3 : 4;
  vbittype cunused5 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 5;
  vbittype cunused8 : 3;
  vbittype cunused7 : 8;
} _c_PPEI_Steering_Wheel_Angle_StrWhAngGroup_0_msgType;
typedef struct _c_PPEI_Steering_Wheel_Angle_StrWhAngGrdGroup_0_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype cunused2 : 2;
  vbittype cunused1 : 2;
  vbittype cunused0 : 1;
  vbittype unused1 : 2;
  vbittype cunused4 : 8;
  vbittype cunused3 : 8;
  vbittype unused2 : 1;
  vbittype cunused7 : 2;
  vbittype cunused6 : 1;
  vbittype unused3 : 4;
  vbittype StrWhAngGrdGroup_0_0 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 5;
  vbittype cunused9 : 3;
  vbittype cunused8 : 8;
} _c_PPEI_Steering_Wheel_Angle_StrWhAngGrdGroup_0_msgType;
typedef struct _c_PPEI_Vehicle_Speed_and_Distance_msgTypeTag
{
  vbittype VehSpdAvgDrvnV_0 : 1;
  vbittype VehSpdAvgDrvn_0_1 : 7;
  vbittype VehSpdAvgDrvn_0_0 : 8;
  vbittype VehSpdAvgDrvnSrc_0 : 1;
  vbittype DistRollCntAvgDrvnV : 1;
  vbittype DstRolCntAvgDrnRstOc : 1;
  vbittype DistRollCntAvgDrvn_1 : 5;
  vbittype DistRollCntAvgDrvn_0 : 8;
  vbittype VehSpdAvgNDrvnV : 1;
  vbittype VehSpdAvgNDrvn_1 : 7;
  vbittype VehSpdAvgNDrvn_0 : 8;
  vbittype DistRollCntAvgDrvnSrc : 1;
  vbittype DstRolCntAvgNonDrvnV : 1;
  vbittype DstRolCntAvNDrRstOc : 1;
  vbittype DstRolCntAvgNonDrvn_1 : 5;
  vbittype DstRolCntAvgNonDrvn_0 : 8;
} _c_PPEI_Vehicle_Speed_and_Distance_msgType;
typedef struct _c_PPEI_Vehicle_Speed_and_Distance_VehSpdAvgDrvnGroup_0_msgTypeTag
{
  vbittype VehSpdAvgDrvnGroup_0_1 : 8;
  vbittype VehSpdAvgDrvnGroup_0_0 : 8;
  vbittype cunused3 : 1;
  vbittype unused0 : 1;
  vbittype cunused0 : 1;
  vbittype unused1 : 5;
  vbittype cunused1 : 8;
  vbittype cunused5 : 8;
  vbittype cunused4 : 8;
  vbittype cunused9 : 1;
  vbittype unused2 : 1;
  vbittype cunused6 : 1;
  vbittype unused3 : 5;
  vbittype cunused7 : 8;
} _c_PPEI_Vehicle_Speed_and_Distance_VehSpdAvgDrvnGroup_0_msgType;
typedef struct _c_PPEI_Vehicle_Speed_and_Distance_DistRollCntAvgDrvnGroup_msgTypeTag
{
  vbittype cunused1 : 8;
  vbittype cunused0 : 8;
  vbittype cunused3 : 1;
  vbittype unused0 : 1;
  vbittype cunused2 : 1;
  vbittype unused1 : 5;
  vbittype DistRollCntAvgDrvnGroup_0 : 8;
  vbittype cunused5 : 8;
  vbittype cunused4 : 8;
  vbittype cunused9 : 1;
  vbittype unused2 : 1;
  vbittype cunused6 : 1;
  vbittype unused3 : 5;
  vbittype cunused7 : 8;
} _c_PPEI_Vehicle_Speed_and_Distance_DistRollCntAvgDrvnGroup_msgType;
typedef struct _c_PPEI_Vehicle_Speed_and_Distance_VehSpdAvgNDrvnGroup_msgTypeTag
{
  vbittype cunused1 : 8;
  vbittype cunused0 : 8;
  vbittype cunused5 : 1;
  vbittype unused0 : 1;
  vbittype cunused2 : 1;
  vbittype unused1 : 5;
  vbittype cunused3 : 8;
  vbittype VehSpdAvgNDrvnGroup_1 : 8;
  vbittype VehSpdAvgNDrvnGroup_0 : 8;
  vbittype cunused9 : 1;
  vbittype unused2 : 1;
  vbittype cunused6 : 1;
  vbittype unused3 : 5;
  vbittype cunused7 : 8;
} _c_PPEI_Vehicle_Speed_and_Distance_VehSpdAvgNDrvnGroup_msgType;
typedef struct _c_PPEI_Vehicle_Speed_and_Distance_DstRolCntAvgNonDrvnGroup_msgTypeTag
{
  vbittype cunused1 : 8;
  vbittype cunused0 : 8;
  vbittype cunused5 : 1;
  vbittype unused0 : 1;
  vbittype cunused2 : 1;
  vbittype unused1 : 5;
  vbittype cunused3 : 8;
  vbittype cunused7 : 8;
  vbittype cunused6 : 8;
  vbittype cunused9 : 1;
  vbittype unused2 : 1;
  vbittype cunused8 : 1;
  vbittype unused3 : 5;
  vbittype DstRolCntAvgNonDrvnGroup_0 : 8;
} _c_PPEI_Vehicle_Speed_and_Distance_DstRolCntAvgNonDrvnGroup_msgType;
typedef struct _c_NonDriven_Wheel_Grnd_Velocity_HS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftNnDrvnV_0 : 1;
  vbittype WhlGrndVlctyLftNnDrvn_0_1 : 6;
  vbittype WhlGrndVlctyLftNnDrvn_0_0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtNnDrvnV_0 : 1;
  vbittype WhlGrndVlctyRtNnDrvn_0_1 : 6;
  vbittype WhlGrndVlctyRtNnDrvn_0_0 : 8;
  vbittype unused2 : 2;
  vbittype WhlRotDrctnlStLfNDrvn : 3;
  vbittype WhlRotDrctnlSRtNDrvn : 3;
} _c_NonDriven_Wheel_Grnd_Velocity_HS_msgType;
typedef struct _c_NonDriven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyLftNnDrvnGroup_0_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftNnDrvnGroup_0_1 : 7;
  vbittype WhlGrndVlctyLftNnDrvnGroup_0_0 : 8;
  vbittype unused1 : 1;
  vbittype cunused1 : 7;
  vbittype cunused0 : 8;
  vbittype unused2 : 2;
  vbittype cunused3 : 3;
  vbittype cunused2 : 3;
} _c_NonDriven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyLftNnDrvnGroup_0_msgType;
typedef struct _c_NonDriven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyRtNnDrvnGroup_0_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype cunused1 : 7;
  vbittype cunused0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtNnDrvnGroup_0_1 : 7;
  vbittype WhlGrndVlctyRtNnDrvnGroup_0_0 : 8;
  vbittype unused2 : 2;
  vbittype cunused3 : 3;
  vbittype cunused2 : 3;
} _c_NonDriven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyRtNnDrvnGroup_0_msgType;
typedef struct _c_PPEI_Engine_General_Status_4_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype EngCltTmpV : 1;
  vbittype unused1 : 6;
  vbittype unused2 : 8;
  vbittype EngCltTmp : 8;
} _c_PPEI_Engine_General_Status_4_msgType;
typedef struct _c_PPEI_Engine_General_Status_4_EngCltTmpGroup_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype EngCltTmpGroup_2 : 7;
  vbittype EngCltTmpGroup_1 : 8;
  vbittype EngCltTmpGroup_0 : 8;
} _c_PPEI_Engine_General_Status_4_EngCltTmpGroup_msgType;
typedef struct _c_PPEI_Engine_General_Status_1_msgTypeTag
{
  vbittype EngRunAtv : 1;
  vbittype PT_CrnkAct : 1;
  vbittype unused0 : 4;
  vbittype EngSpdStat : 2;
  vbittype EngSpd_1 : 8;
  vbittype EngSpd_0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 2;
  vbittype Eng12vStrtrMtrCmmdOn : 1;
  vbittype unused5 : 5;
} _c_PPEI_Engine_General_Status_1_msgType;
typedef struct _c_PPEI_Trans_General_Status_2_msgTypeTag
{
  vbittype unused0 : 3;
  vbittype TransEstGearV : 1;
  vbittype TransEstGear : 4;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 3;
  vbittype TrnsShftLvrPosV : 1;
  vbittype TrnsShftLvrPos : 4;
  vbittype unused4 : 8;
  vbittype unused5 : 3;
  vbittype TrnShftPtrnActStat : 3;
  vbittype unused6 : 2;
} _c_PPEI_Trans_General_Status_2_msgType;
typedef struct _c_PPEI_Trans_General_Status_2_TransEstGearGroup_msgTypeTag
{
  vbittype unused0 : 3;
  vbittype TransEstGearGroup : 5;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 3;
  vbittype cunused0 : 5;
  vbittype unused4 : 8;
  vbittype unused5 : 3;
  vbittype cunused1 : 3;
  vbittype unused6 : 2;
} _c_PPEI_Trans_General_Status_2_TransEstGearGroup_msgType;
typedef struct _c_PPEI_Trans_General_Status_2_TrnsShftLvrPosGroup_msgTypeTag
{
  vbittype unused0 : 3;
  vbittype cunused0 : 5;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 3;
  vbittype TrnsShftLvrPosGroup : 5;
  vbittype unused4 : 8;
  vbittype unused5 : 3;
  vbittype cunused1 : 3;
  vbittype unused6 : 2;
} _c_PPEI_Trans_General_Status_2_TrnsShftLvrPosGroup_msgType;
typedef struct _c_PPEI_Platform_Eng_Cntrl_Requests_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 4;
  vbittype EngOffTmVDA : 1;
  vbittype EngOffTmExtRngV : 1;
  vbittype unused4 : 2;
  vbittype EngOffTmExtRng : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 4;
  vbittype OtsAirTmpCrValMsk : 1;
  vbittype unused7 : 2;
  vbittype OtsAirTmpCrValV : 1;
  vbittype OtsAirTmpCrVal : 8;
} _c_PPEI_Platform_Eng_Cntrl_Requests_msgType;
typedef struct _c_PPEI_Platform_Eng_Cntrl_Requests_EngOffTmExtRngGroup_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 4;
  vbittype cunused0 : 1;
  vbittype EngOffTmExtRngGroup_1 : 3;
  vbittype EngOffTmExtRngGroup_0 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 4;
  vbittype cunused3 : 1;
  vbittype unused6 : 2;
  vbittype cunused2 : 1;
  vbittype cunused1 : 8;
} _c_PPEI_Platform_Eng_Cntrl_Requests_EngOffTmExtRngGroup_msgType;
typedef struct _c_PPEI_Platform_Eng_Cntrl_Requests_OtsAirTmpCrValGroup_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 4;
  vbittype cunused2 : 1;
  vbittype cunused1 : 3;
  vbittype cunused0 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 4;
  vbittype cunused3 : 1;
  vbittype unused6 : 2;
  vbittype OtsAirTmpCrValGroup_1 : 1;
  vbittype OtsAirTmpCrValGroup_0 : 8;
} _c_PPEI_Platform_Eng_Cntrl_Requests_OtsAirTmpCrValGroup_msgType;
typedef struct _c_PPEI_Platform_General_Status_msgTypeTag
{
  vbittype BkupPwrModeMstrVDA : 1;
  vbittype SysBkupPwrMdEn : 1;
  vbittype SysBkUpPwrMd : 2;
  vbittype unused0 : 2;
  vbittype SysPwrMd : 2;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 5;
  vbittype TrStLgMdAtv : 1;
  vbittype unused5 : 2;
} _c_PPEI_Platform_General_Status_msgType;
typedef struct _c_PPEI_Platform_General_Status_BkupPwrModeMstrGroup_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype cunused2 : 1;
  vbittype cunused1 : 2;
  vbittype unused1 : 2;
  vbittype cunused0 : 2;
  vbittype BkupPwrModeMstrGroup_6 : 8;
  vbittype BkupPwrModeMstrGroup_5 : 8;
  vbittype BkupPwrModeMstrGroup_4 : 8;
  vbittype unused2 : 5;
  vbittype cunused3 : 1;
  vbittype unused3 : 2;
  vbittype BkupPwrModeMstrGroup_2 : 8;
  vbittype BkupPwrModeMstrGroup_1 : 8;
  vbittype BkupPwrModeMstrGroup_0 : 3;
  vbittype unused4 : 5;
} _c_PPEI_Platform_General_Status_BkupPwrModeMstrGroup_msgType;
typedef struct _c_Driven_Wheel_Grnd_Velocity_HS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftDrvnV_0 : 1;
  vbittype WhlGrndVlctyLftDrvn_0_1 : 6;
  vbittype WhlGrndVlctyLftDrvn_0_0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtDrvnV_0 : 1;
  vbittype WhlGrndVlctyRtDrvn_0_1 : 6;
  vbittype WhlGrndVlctyRtDrvn_0_0 : 8;
  vbittype unused2 : 2;
  vbittype WhlRotDrctnlStLftDrvn : 3;
  vbittype WhlRotDrctnlStRtDrvn : 3;
} _c_Driven_Wheel_Grnd_Velocity_HS_msgType;
typedef struct _c_Driven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyLftDrvnGroup_0_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftDrvnGroup_0_1 : 7;
  vbittype WhlGrndVlctyLftDrvnGroup_0_0 : 8;
  vbittype unused1 : 1;
  vbittype cunused1 : 7;
  vbittype cunused0 : 8;
  vbittype unused2 : 2;
  vbittype cunused3 : 3;
  vbittype cunused2 : 3;
} _c_Driven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyLftDrvnGroup_0_msgType;
typedef struct _c_Driven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyRtDrvnGroup_0_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype cunused1 : 7;
  vbittype cunused0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtDrvnGroup_0_1 : 7;
  vbittype WhlGrndVlctyRtDrvnGroup_0_0 : 8;
  vbittype unused2 : 2;
  vbittype cunused3 : 3;
  vbittype cunused2 : 3;
} _c_Driven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyRtDrvnGroup_0_msgType;
typedef struct _c_PPEI_Driven_Whl_Rotational_Stat_msgTypeTag
{
  vbittype WRSLDWhlDisTpRC : 2;
  vbittype WRSLDSeqNum : 2;
  vbittype WRSLDWhlRotStatRst : 1;
  vbittype WRSLDWhlDistVal : 1;
  vbittype WRSLDWhlDistPlsCntr_1 : 2;
  vbittype WRSLDWhlDistPlsCntr_0 : 8;
  vbittype WRSLDWhlDistTmstm_1 : 8;
  vbittype WRSLDWhlDistTmstm_0 : 8;
  vbittype WRSRDWhlDisTpRC : 2;
  vbittype WRSRDSeqNum : 2;
  vbittype WRSRDWhlRotStatRst : 1;
  vbittype WRSRDWhlDistVal : 1;
  vbittype WRSRDWhlDistPlsCntr_1 : 2;
  vbittype WRSRDWhlDistPlsCntr_0 : 8;
  vbittype WRSRDWhlDistTmstm_1 : 8;
  vbittype WRSRDWhlDistTmstm_0 : 8;
} _c_PPEI_Driven_Whl_Rotational_Stat_msgType;
typedef struct _c_PPEI_Driven_Whl_Rotational_Stat_WhlRotatStatLftDrvn_msgTypeTag
{
  vbittype WhlRotatStatLftDrvn_3 : 8;
  vbittype WhlRotatStatLftDrvn_2 : 8;
  vbittype WhlRotatStatLftDrvn_1 : 8;
  vbittype WhlRotatStatLftDrvn_0 : 8;
  vbittype cunused3 : 8;
  vbittype cunused2 : 8;
  vbittype cunused1 : 8;
  vbittype cunused0 : 8;
} _c_PPEI_Driven_Whl_Rotational_Stat_WhlRotatStatLftDrvn_msgType;
typedef struct _c_PPEI_Driven_Whl_Rotational_Stat_WhlRotatStatRtDrvn_msgTypeTag
{
  vbittype cunused3 : 8;
  vbittype cunused2 : 8;
  vbittype cunused1 : 8;
  vbittype cunused0 : 8;
  vbittype WhlRotatStatRtDrvn_3 : 8;
  vbittype WhlRotatStatRtDrvn_2 : 8;
  vbittype WhlRotatStatRtDrvn_1 : 8;
  vbittype WhlRotatStatRtDrvn_0 : 8;
} _c_PPEI_Driven_Whl_Rotational_Stat_WhlRotatStatRtDrvn_msgType;
typedef struct _c_PPEI_Chassis_General_Status_1_msgTypeTag
{
  vbittype BrkPdlDrvAppPrsDetcdV : 1;
  vbittype BrkPdlDrvAppPrsDetcd : 1;
  vbittype unused0 : 1;
  vbittype VSELatAccV : 1;
  vbittype VSELatAcc_1 : 4;
  vbittype VSELatAcc_0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 1;
  vbittype ABSAtv_0 : 1;
  vbittype ABSFld : 1;
  vbittype TCSysAtv : 1;
  vbittype TCSysEnbld : 1;
  vbittype TracCntrlSysDrIntnt : 1;
  vbittype unused3 : 1;
  vbittype VSEAct_0 : 1;
  vbittype VhDynCntlSysSt : 3;
  vbittype VehDynYawRateV : 1;
  vbittype VehDynYawRate_1 : 4;
  vbittype VehDynYawRate_0 : 8;
  vbittype unused4 : 5;
  vbittype VehDynOvrUndrStrV_0 : 1;
  vbittype VehDynOvrUndrStr_0_1 : 2;
  vbittype VehDynOvrUndrStr_0_0 : 8;
} _c_PPEI_Chassis_General_Status_1_msgType;
typedef struct _c_PPEI_Chassis_General_Status_1_VSELatAccGroup_msgTypeTag
{
  vbittype cunused0 : 2;
  vbittype unused0 : 1;
  vbittype VSELatAccGroup_1 : 5;
  vbittype VSELatAccGroup_0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 1;
  vbittype cunused6 : 1;
  vbittype cunused5 : 1;
  vbittype cunused4 : 1;
  vbittype cunused3 : 1;
  vbittype cunused2 : 1;
  vbittype unused3 : 1;
  vbittype cunused1 : 1;
  vbittype cunused9 : 3;
  vbittype cunused8 : 5;
  vbittype cunused7 : 8;
  vbittype unused4 : 5;
  vbittype cunused11 : 3;
  vbittype cunused10 : 8;
} _c_PPEI_Chassis_General_Status_1_VSELatAccGroup_msgType;
typedef struct _c_PPEI_Chassis_General_Status_1_BrkPdlDrvAppPrsDetcdGroup_msgTypeTag
{
  vbittype BrkPdlDrvAppPrsDetcdGroup : 2;
  vbittype unused0 : 1;
  vbittype cunused1 : 5;
  vbittype cunused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 1;
  vbittype cunused7 : 1;
  vbittype cunused6 : 1;
  vbittype cunused5 : 1;
  vbittype cunused4 : 1;
  vbittype cunused3 : 1;
  vbittype unused3 : 1;
  vbittype cunused2 : 1;
  vbittype cunused10 : 3;
  vbittype cunused9 : 5;
  vbittype cunused8 : 8;
  vbittype unused4 : 5;
  vbittype cunused12 : 3;
  vbittype cunused11 : 8;
} _c_PPEI_Chassis_General_Status_1_BrkPdlDrvAppPrsDetcdGroup_msgType;
typedef struct _c_PPEI_Chassis_General_Status_1_VehDynYawRateGroup_msgTypeTag
{
  vbittype cunused2 : 2;
  vbittype unused0 : 1;
  vbittype cunused1 : 5;
  vbittype cunused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 1;
  vbittype cunused8 : 1;
  vbittype cunused7 : 1;
  vbittype cunused6 : 1;
  vbittype cunused5 : 1;
  vbittype cunused4 : 1;
  vbittype unused3 : 1;
  vbittype cunused3 : 1;
  vbittype cunused9 : 3;
  vbittype VehDynYawRateGroup_1 : 5;
  vbittype VehDynYawRateGroup_0 : 8;
  vbittype unused4 : 5;
  vbittype cunused11 : 3;
  vbittype cunused10 : 8;
} _c_PPEI_Chassis_General_Status_1_VehDynYawRateGroup_msgType;
typedef struct _c_PPEI_Chassis_General_Status_1_VehDynOvrUndrStrGroup_0_msgTypeTag
{
  vbittype cunused2 : 2;
  vbittype unused0 : 1;
  vbittype cunused1 : 5;
  vbittype cunused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 1;
  vbittype cunused8 : 1;
  vbittype cunused7 : 1;
  vbittype cunused6 : 1;
  vbittype cunused5 : 1;
  vbittype cunused4 : 1;
  vbittype unused3 : 1;
  vbittype cunused3 : 1;
  vbittype cunused11 : 3;
  vbittype cunused10 : 5;
  vbittype cunused9 : 8;
  vbittype unused4 : 5;
  vbittype VehDynOvrUndrStrGroup_0_1 : 3;
  vbittype VehDynOvrUndrStrGroup_0_0 : 8;
} _c_PPEI_Chassis_General_Status_1_VehDynOvrUndrStrGroup_0_msgType;
typedef struct _c_Antilock_Brake_and_TC_Status_HS_msgTypeTag
{
  vbittype TCSysOpMd : 3;
  vbittype VehStabEnhmntStat_0 : 3;
  vbittype unused0 : 2;
} _c_Antilock_Brake_and_TC_Status_HS_msgType;
typedef struct _c_UUDT_Resp_From_EHPS_EPS_HS_msgTypeTag
{
  vbittype DgnInf_HS542_7 : 8;
  vbittype DgnInf_HS542_6 : 8;
  vbittype DgnInf_HS542_5 : 8;
  vbittype DgnInf_HS542_4 : 8;
  vbittype DgnInf_HS542_3 : 8;
  vbittype DgnInf_HS542_2 : 8;
  vbittype DgnInf_HS542_1 : 8;
  vbittype DgnInf_HS542_0 : 8;
} _c_UUDT_Resp_From_EHPS_EPS_HS_msgType;
typedef struct _c_USDT_Resp_From_EHPS_EPS_HS_msgTypeTag
{
  vbittype DgnInf_0_7 : 8;
  vbittype DgnInf_0_6 : 8;
  vbittype DgnInf_0_5 : 8;
  vbittype DgnInf_0_4 : 8;
  vbittype DgnInf_0_3 : 8;
  vbittype DgnInf_0_2 : 8;
  vbittype DgnInf_0_1 : 8;
  vbittype DgnInf_0_0 : 8;
} _c_USDT_Resp_From_EHPS_EPS_HS_msgType;
typedef struct _c_LKA_Steering_Trq_Overlay_Stat_HS_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype LKATrqOvrlTrqDStat : 3;
  vbittype LKAElPwrStTtlTqDlvd_1 : 3;
  vbittype LKAElPwrStTtlTqDlvd_0 : 8;
  vbittype unused1 : 1;
  vbittype HndsOffStrWhlDtStV : 1;
  vbittype HndsOffStrWhlDtSt : 1;
  vbittype HndsOffStrWhlDtMd : 2;
  vbittype LKATrqOvrlDltTrqDlvd_1 : 3;
  vbittype LKATrqOvrlDltTrqDlvd_0 : 8;
  vbittype unused2 : 1;
  vbittype LKATrqOvrlDlvdRC : 4;
  vbittype LKATrqOvrlStatChksm_1 : 3;
  vbittype LKATrqOvrlStatChksm_0 : 8;
  vbittype unused3 : 4;
  vbittype LKADrvAppldTrqV : 1;
  vbittype LKADrvAppldTrq_1 : 3;
  vbittype LKADrvAppldTrq_0 : 8;
} _c_LKA_Steering_Trq_Overlay_Stat_HS_msgType;
typedef struct _c_LKA_Steering_Trq_Overlay_Stat_HS_HndsOffStrWhlDtStGroup_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype cunused2 : 3;
  vbittype cunused1 : 3;
  vbittype cunused0 : 8;
  vbittype unused1 : 1;
  vbittype HndsOffStrWhlDtStGroup : 2;
  vbittype cunused5 : 2;
  vbittype cunused4 : 3;
  vbittype cunused3 : 8;
  vbittype unused2 : 1;
  vbittype cunused8 : 4;
  vbittype cunused7 : 3;
  vbittype cunused6 : 8;
  vbittype unused3 : 4;
  vbittype cunused10 : 4;
  vbittype cunused9 : 8;
} _c_LKA_Steering_Trq_Overlay_Stat_HS_HndsOffStrWhlDtStGroup_msgType;
typedef struct _c_LKA_Steering_Trq_Overlay_Stat_HS_LKADrvAppldTrqGroup_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype cunused2 : 3;
  vbittype cunused1 : 3;
  vbittype cunused0 : 8;
  vbittype unused1 : 1;
  vbittype cunused6 : 2;
  vbittype cunused5 : 2;
  vbittype cunused4 : 3;
  vbittype cunused3 : 8;
  vbittype unused2 : 1;
  vbittype cunused9 : 4;
  vbittype cunused8 : 3;
  vbittype cunused7 : 8;
  vbittype unused3 : 4;
  vbittype LKADrvAppldTrqGroup_1 : 4;
  vbittype LKADrvAppldTrqGroup_0 : 8;
} _c_LKA_Steering_Trq_Overlay_Stat_HS_LKADrvAppldTrqGroup_msgType;
typedef struct _c_LKA_Steering_Torque_Cmd_HS_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype LKATqOvrDltCmdRC : 2;
  vbittype LKATODC_TrqRqAct : 1;
  vbittype LKATODC_TrqVl_1 : 3;
  vbittype LKATODC_TrqVl_0 : 8;
  vbittype unused1 : 4;
  vbittype LKATqOvrDltCmdPrtVl_1 : 4;
  vbittype LKATqOvrDltCmdPrtVl_0 : 8;
} _c_LKA_Steering_Torque_Cmd_HS_msgType;
typedef struct _c_LKA_Steering_Torque_Cmd_HS_LKATqOvrDltCmd_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype cunused0 : 2;
  vbittype LKATqOvrDltCmd_1 : 4;
  vbittype LKATqOvrDltCmd_0 : 8;
  vbittype unused1 : 4;
  vbittype cunused2 : 4;
  vbittype cunused1 : 8;
} _c_LKA_Steering_Torque_Cmd_HS_LKATqOvrDltCmd_msgType;
typedef struct _c_Xcp_Master_Msg_msgTypeTag
{
  vbittype Xcp_Master_Byte0 : 8;
  vbittype Xcp_Master_Byte1 : 8;
  vbittype Xcp_Master_Byte2 : 8;
  vbittype Xcp_Master_Byte3 : 8;
  vbittype Xcp_Master_Byte4 : 8;
  vbittype Xcp_Master_Byte5 : 8;
  vbittype Xcp_Master_Byte6 : 8;
  vbittype Xcp_Master_Byte7 : 8;
} _c_Xcp_Master_Msg_msgType;
typedef struct _c_Xcp_Slave_Msg_msgTypeTag
{
  vbittype Xcp_Slave_Byte0 : 8;
  vbittype Xcp_Slave_Byte1 : 8;
  vbittype Xcp_Slave_Byte2 : 8;
  vbittype Xcp_Slave_Byte3 : 8;
  vbittype Xcp_Slave_Byte4 : 8;
  vbittype Xcp_Slave_Byte5 : 8;
  vbittype Xcp_Slave_Byte6 : 8;
  vbittype Xcp_Slave_Byte7 : 8;
} _c_Xcp_Slave_Msg_msgType;
typedef struct _c_T1_HostToTarget_msgTypeTag
{
  vbittype T1_HostToTarget_0 : 8;
  vbittype T1_HostToTarget_1 : 8;
  vbittype T1_HostToTarget_2 : 8;
  vbittype T1_HostToTarget_3 : 8;
  vbittype T1_HostToTarget_4 : 8;
  vbittype T1_HostToTarget_5 : 8;
  vbittype T1_HostToTarget_6 : 8;
  vbittype T1_HostToTarget_7 : 8;
} _c_T1_HostToTarget_msgType;
typedef struct _c_Park_Assist_Parallel_CE_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype StrWhlTctlFdbkReqActProtVal : 2;
  vbittype StrWhlTctlFdbkReqAct : 1;
  vbittype unused1 : 1;
  vbittype StrWhlTctlFdbkReqActRC : 2;
  vbittype unused2 : 6;
  vbittype SWAR_ReqAct : 1;
  vbittype SWAR_ReqActV : 1;
  vbittype SWAR_TrgtAng_1 : 8;
  vbittype SWAR_TrgtAng_0 : 8;
  vbittype unused3 : 4;
  vbittype StrWhlAngReqARC : 2;
  vbittype StrWhlAngReqPrtVal_2 : 2;
  vbittype StrWhlAngReqPrtVal_1 : 8;
  vbittype StrWhlAngReqPrtVal_0 : 8;
} _c_Park_Assist_Parallel_CE_msgType;
typedef struct _c_Park_Assist_Parallel_CE_StrWhlAngReq_msgTypeTag
{
  vbittype unused0 : 2;
  vbittype cunused2 : 2;
  vbittype cunused1 : 1;
  vbittype unused1 : 1;
  vbittype cunused0 : 2;
  vbittype unused2 : 6;
  vbittype StrWhlAngReq_2 : 2;
  vbittype StrWhlAngReq_1 : 8;
  vbittype StrWhlAngReq_0 : 8;
  vbittype unused3 : 4;
  vbittype cunused6 : 2;
  vbittype cunused5 : 2;
  vbittype cunused4 : 8;
  vbittype cunused3 : 8;
} _c_Park_Assist_Parallel_CE_StrWhlAngReq_msgType;
typedef struct _c_Electric_Power_Steering_CE_msgTypeTag
{
  vbittype DrvStrIntfrDetPrtVal : 2;
  vbittype DrvStrIntfrDetARC : 2;
  vbittype DrvStrIntfrDtcd : 1;
  vbittype DrvStrIntfrDtcdV : 1;
  vbittype ElecPwrStrAvalStat : 2;
  vbittype unused0 : 4;
  vbittype ElcPwrStrAvalStatPVal : 2;
  vbittype ElcPwrStrAvalStatARC : 2;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
} _c_Electric_Power_Steering_CE_msgType;
typedef struct _c_Electric_Power_Steering_CE_DrvStrIntfrDtcdGroup_msgTypeTag
{
  vbittype cunused2 : 2;
  vbittype cunused1 : 2;
  vbittype DrvStrIntfrDtcdGroup : 2;
  vbittype cunused0 : 2;
  vbittype unused0 : 4;
  vbittype cunused4 : 2;
  vbittype cunused3 : 2;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
} _c_Electric_Power_Steering_CE_DrvStrIntfrDtcdGroup_msgType;
typedef struct _c_UUDT_Resp_From_EPS_EPS_JR_CE_msgTypeTag
{
  vbittype DgnInf_CE542_7 : 8;
  vbittype DgnInf_CE542_6 : 8;
  vbittype DgnInf_CE542_5 : 8;
  vbittype DgnInf_CE542_4 : 8;
  vbittype DgnInf_CE542_3 : 8;
  vbittype DgnInf_CE542_2 : 8;
  vbittype DgnInf_CE542_1 : 8;
  vbittype DgnInf_CE542_0 : 8;
} _c_UUDT_Resp_From_EPS_EPS_JR_CE_msgType;
typedef struct _c_USDT_Resp_From_EPS_EPS_JR_CE_msgTypeTag
{
  vbittype DgnInf_1_7 : 8;
  vbittype DgnInf_1_6 : 8;
  vbittype DgnInf_1_5 : 8;
  vbittype DgnInf_1_4 : 8;
  vbittype DgnInf_1_3 : 8;
  vbittype DgnInf_1_2 : 8;
  vbittype DgnInf_1_1 : 8;
  vbittype DgnInf_1_0 : 8;
} _c_USDT_Resp_From_EPS_EPS_JR_CE_msgType;
typedef struct _c_Steering_Torque_Command_CE_msgTypeTag
{
  vbittype TrqOvrlARC : 4;
  vbittype TqOvrDltTqCmdAct : 1;
  vbittype TqOvrDltTqCmdVl_1 : 3;
  vbittype TqOvrDltTqCmdVl_0 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 5;
  vbittype TrqOvrlCmdChksm_1 : 3;
  vbittype TrqOvrlCmdChksm_0 : 8;
} _c_Steering_Torque_Command_CE_msgType;
typedef struct _c_Steering_Torque_Overlay_Stat_CE_msgTypeTag
{
  vbittype unused0 : 3;
  vbittype TrqOvrlTrqDStat : 2;
  vbittype ElPwrStTtlTqDlrd_1 : 3;
  vbittype ElPwrStTtlTqDlrd_0 : 8;
  vbittype unused1 : 1;
  vbittype TrqOvrlDvrdARC : 4;
  vbittype unused2 : 3;
  vbittype unused3 : 8;
  vbittype unused4 : 5;
  vbittype TrqOvrlDltTrqDlrd_1 : 3;
  vbittype TrqOvrlDltTrqDlrd_0 : 8;
  vbittype unused5 : 5;
  vbittype TrqOvrlDChksm_1 : 3;
  vbittype TrqOvrlDChksm_0 : 8;
} _c_Steering_Torque_Overlay_Stat_CE_msgType;
typedef struct _c_Vehicle_Dynamics_ESC_Hyb_CE_msgTypeTag
{
  vbittype unused0 : 4;
  vbittype VSELongAccLoResV : 1;
  vbittype unused1 : 2;
  vbittype VSEAct_1 : 1;
  vbittype unused2 : 3;
  vbittype VehStabEnhmntStat_1 : 3;
  vbittype VSELongAccLoRes_1 : 2;
  vbittype VSELongAccLoRes_0 : 8;
  vbittype unused3 : 5;
  vbittype VehDynOvrUndrStrV_1 : 1;
  vbittype VehDynOvrUndrStr_1_1 : 2;
  vbittype VehDynOvrUndrStr_1_0 : 8;
} _c_Vehicle_Dynamics_ESC_Hyb_CE_msgType;
typedef struct _c_Vehicle_Dynamics_ESC_Hyb_CE_VSELongAccLoResGroup_msgTypeTag
{
  vbittype unused0 : 7;
  vbittype cunused0 : 1;
  vbittype unused1 : 3;
  vbittype cunused1 : 3;
  vbittype unused2 : 2;
  vbittype VSELongAccLoResGroup_0 : 8;
  vbittype unused3 : 5;
  vbittype cunused3 : 3;
  vbittype cunused2 : 8;
} _c_Vehicle_Dynamics_ESC_Hyb_CE_VSELongAccLoResGroup_msgType;
typedef struct _c_Vehicle_Dynamics_ESC_Hyb_CE_VehDynOvrUndrStrGroup_1_msgTypeTag
{
  vbittype unused0 : 7;
  vbittype cunused0 : 1;
  vbittype unused1 : 3;
  vbittype cunused4 : 3;
  vbittype unused2 : 2;
  vbittype cunused1 : 8;
  vbittype unused3 : 5;
  vbittype VehDynOvrUndrStrGroup_1_1 : 3;
  vbittype VehDynOvrUndrStrGroup_1_0 : 8;
} _c_Vehicle_Dynamics_ESC_Hyb_CE_VehDynOvrUndrStrGroup_1_msgType;
typedef struct _c_NonDriven_Wheel_Grnd_Velocity_CE_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftNnDrvnV_1 : 1;
  vbittype WhlGrndVlctyLftNnDrvn_1_1 : 6;
  vbittype WhlGrndVlctyLftNnDrvn_1_0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtNnDrvnV_1 : 1;
  vbittype WhlGrndVlctyRtNnDrvn_1_1 : 6;
  vbittype WhlGrndVlctyRtNnDrvn_1_0 : 8;
  vbittype unused2 : 1;
  vbittype WhlPlsPerRevNonDrvn_1 : 7;
} _c_NonDriven_Wheel_Grnd_Velocity_CE_msgType;
typedef struct _c_NonDriven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyLftNnDrvnGroup_1_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftNnDrvnGroup_1_1 : 7;
  vbittype WhlGrndVlctyLftNnDrvnGroup_1_0 : 8;
  vbittype unused1 : 1;
  vbittype cunused1 : 7;
  vbittype cunused0 : 8;
  vbittype unused2 : 1;
  vbittype cunused2 : 7;
} _c_NonDriven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyLftNnDrvnGroup_1_msgType;
typedef struct _c_NonDriven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyRtNnDrvnGroup_1_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype cunused1 : 7;
  vbittype cunused0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtNnDrvnGroup_1_1 : 7;
  vbittype WhlGrndVlctyRtNnDrvnGroup_1_0 : 8;
  vbittype unused2 : 1;
  vbittype cunused2 : 7;
} _c_NonDriven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyRtNnDrvnGroup_1_msgType;
typedef struct _c_Driven_Wheel_Grnd_Velocity_CE_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftDrvnV_1 : 1;
  vbittype WhlGrndVlctyLftDrvn_1_1 : 6;
  vbittype WhlGrndVlctyLftDrvn_1_0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtDrvnV_1 : 1;
  vbittype WhlGrndVlctyRtDrvn_1_1 : 6;
  vbittype WhlGrndVlctyRtDrvn_1_0 : 8;
  vbittype unused2 : 1;
  vbittype WhlPlsPerRevDrvn_1 : 7;
} _c_Driven_Wheel_Grnd_Velocity_CE_msgType;
typedef struct _c_Driven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyLftDrvnGroup_1_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftDrvnGroup_1_1 : 7;
  vbittype WhlGrndVlctyLftDrvnGroup_1_0 : 8;
  vbittype unused1 : 1;
  vbittype cunused1 : 7;
  vbittype cunused0 : 8;
  vbittype unused2 : 1;
  vbittype cunused2 : 7;
} _c_Driven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyLftDrvnGroup_1_msgType;
typedef struct _c_Driven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyRtDrvnGroup_1_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype cunused1 : 7;
  vbittype cunused0 : 8;
  vbittype unused1 : 1;
  vbittype WhlGrndVlctyRtDrvnGroup_1_1 : 7;
  vbittype WhlGrndVlctyRtDrvnGroup_1_0 : 8;
  vbittype unused2 : 1;
  vbittype cunused2 : 7;
} _c_Driven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyRtDrvnGroup_1_msgType;
typedef struct _c_PPEI_Steering_Wheel_Angle_CE_msgTypeTag
{
  vbittype StrWhAngV_1 : 1;
  vbittype StrWhlAngSenCalStat_1 : 2;
  vbittype StrWhlAngSenTyp_1 : 2;
  vbittype StrWhAngMsk_1 : 1;
  vbittype unused0 : 2;
  vbittype StrWhAng_1_1 : 8;
  vbittype StrWhAng_1_0 : 8;
  vbittype StrWhAngGrdV_1 : 1;
  vbittype StWhlAngAliveRollCnt_1 : 2;
  vbittype StrWhAngGrdMsk_1 : 1;
  vbittype StrWhAngGrd_1_1 : 4;
  vbittype StrWhAngGrd_1_0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 5;
  vbittype StrAngSnsChksm_1_1 : 3;
  vbittype StrAngSnsChksm_1_0 : 8;
} _c_PPEI_Steering_Wheel_Angle_CE_msgType;
typedef struct _c_PPEI_Steering_Wheel_Angle_CE_StrWhAngGroup_1_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype cunused2 : 2;
  vbittype cunused1 : 2;
  vbittype cunused0 : 1;
  vbittype unused1 : 2;
  vbittype StrWhAngGroup_1_1 : 8;
  vbittype StrWhAngGroup_1_0 : 8;
  vbittype unused2 : 1;
  vbittype cunused4 : 2;
  vbittype cunused3 : 1;
  vbittype unused3 : 4;
  vbittype cunused5 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 5;
  vbittype cunused8 : 3;
  vbittype cunused7 : 8;
} _c_PPEI_Steering_Wheel_Angle_CE_StrWhAngGroup_1_msgType;
typedef struct _c_PPEI_Steering_Wheel_Angle_CE_StrWhAngGrdGroup_1_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype cunused2 : 2;
  vbittype cunused1 : 2;
  vbittype cunused0 : 1;
  vbittype unused1 : 2;
  vbittype cunused4 : 8;
  vbittype cunused3 : 8;
  vbittype unused2 : 1;
  vbittype cunused7 : 2;
  vbittype cunused6 : 1;
  vbittype unused3 : 4;
  vbittype StrWhAngGrdGroup_1_0 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 5;
  vbittype cunused9 : 3;
  vbittype cunused8 : 8;
} _c_PPEI_Steering_Wheel_Angle_CE_StrWhAngGrdGroup_1_msgType;
/* -----------------------------------------------------------------------------
    &&&~ Signal Structures for group signals
 ----------------------------------------------------------------------------- */

typedef struct _c_DTCInfo_778_msgTypeTag
{
  vbittype DTCIUnused1_778 : 1;
  vbittype DTCIUnused2_778 : 1;
  vbittype DTCIUnused3_778 : 1;
  vbittype DTCIUnused4_778 : 1;
  vbittype DTCIUnused5_778 : 1;
  vbittype DTCIUnused6_778 : 1;
  vbittype DTCIUnused7_778 : 1;
  vbittype DTCI_DTCTriggered_778 : 1;
  vbittype DTCI_DTCSource_778 : 8;
  vbittype DTCI_DTCNumber_778_1 : 8;
  vbittype DTCI_DTCNumber_778_0 : 8;
  vbittype DTCI_DTCFailType_778 : 8;
  vbittype DTCI_WrnIndRqdSt_778 : 1;
  vbittype DTCI_TstFldPwrUpSt_778 : 1;
  vbittype DTCI_TstNPsdPwrUpSt_778 : 1;
  vbittype DTCI_HistStat_778 : 1;
  vbittype DTCI_TstFldCdClrdStat_778 : 1;
  vbittype DTCI_TstNPsdCdClrdSt_778 : 1;
  vbittype DTCI_CurrentStatus_778 : 1;
  vbittype DTCI_CodeSupported_778 : 1;
  vbittype DTCI_DTCFaultType_778 : 8;
} _c_DTCInfo_778_msgType;
typedef struct _c_StrWhAngGroup_0_msgTypeTag
{
  vbittype StrWhAngV_0 : 1;
  vbittype unused0 : 7;
  vbittype StrWhAng_0_1 : 8;
  vbittype StrWhAng_0_0 : 8;
} _c_StrWhAngGroup_0_msgType;
typedef struct _c_StrWhAngGrdGroup_0_msgTypeTag
{
  vbittype StrWhAngGrdV_0 : 1;
  vbittype unused0 : 3;
  vbittype StrWhAngGrd_0_1 : 4;
  vbittype StrWhAngGrd_0_0 : 8;
} _c_StrWhAngGrdGroup_0_msgType;
typedef struct _c_HndsOffStrWhlDtStGroup_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype HndsOffStrWhlDtStV : 1;
  vbittype HndsOffStrWhlDtSt : 1;
  vbittype unused1 : 5;
} _c_HndsOffStrWhlDtStGroup_msgType;
typedef struct _c_LKADrvAppldTrqGroup_msgTypeTag
{
  vbittype unused0 : 4;
  vbittype LKADrvAppldTrqV : 1;
  vbittype LKADrvAppldTrq_1 : 3;
  vbittype LKADrvAppldTrq_0 : 8;
} _c_LKADrvAppldTrqGroup_msgType;
typedef struct _c_DrvStrIntfrDtcdGroup_msgTypeTag
{
  vbittype unused0 : 4;
  vbittype DrvStrIntfrDtcd : 1;
  vbittype DrvStrIntfrDtcdV : 1;
  vbittype unused1 : 2;
} _c_DrvStrIntfrDtcdGroup_msgType;
typedef struct _c_StrWhAngGroup_1_msgTypeTag
{
  vbittype StrWhAngV_1 : 1;
  vbittype unused0 : 7;
  vbittype StrWhAng_1_1 : 8;
  vbittype StrWhAng_1_0 : 8;
} _c_StrWhAngGroup_1_msgType;
typedef struct _c_StrWhAngGrdGroup_1_msgTypeTag
{
  vbittype StrWhAngGrdV_1 : 1;
  vbittype unused0 : 3;
  vbittype StrWhAngGrd_1_1 : 4;
  vbittype StrWhAngGrd_1_0 : 8;
} _c_StrWhAngGrdGroup_1_msgType;
typedef struct _c_EngCltTmpGroup_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype EngCltTmpV : 1;
  vbittype unused1 : 6;
  vbittype unused2 : 8;
  vbittype EngCltTmp : 8;
} _c_EngCltTmpGroup_msgType;
typedef struct _c_EngOffTmExtRngGroup_msgTypeTag
{
  vbittype unused0 : 5;
  vbittype EngOffTmExtRngV : 1;
  vbittype unused1 : 2;
  vbittype EngOffTmExtRng : 8;
} _c_EngOffTmExtRngGroup_msgType;
typedef struct _c_OtsAirTmpCrValGroup_msgTypeTag
{
  vbittype unused0 : 7;
  vbittype OtsAirTmpCrValV : 1;
  vbittype OtsAirTmpCrVal : 8;
} _c_OtsAirTmpCrValGroup_msgType;
typedef struct _c_VehSpdAvgDrvnGroup_0_msgTypeTag
{
  vbittype VehSpdAvgDrvnV_0 : 1;
  vbittype VehSpdAvgDrvn_0_1 : 7;
  vbittype VehSpdAvgDrvn_0_0 : 8;
} _c_VehSpdAvgDrvnGroup_0_msgType;
typedef struct _c_DistRollCntAvgDrvnGroup_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype DistRollCntAvgDrvnV : 1;
  vbittype unused1 : 1;
  vbittype DistRollCntAvgDrvn_1 : 5;
  vbittype DistRollCntAvgDrvn_0 : 8;
} _c_DistRollCntAvgDrvnGroup_msgType;
typedef struct _c_VehSpdAvgNDrvnGroup_msgTypeTag
{
  vbittype VehSpdAvgNDrvnV : 1;
  vbittype VehSpdAvgNDrvn_1 : 7;
  vbittype VehSpdAvgNDrvn_0 : 8;
} _c_VehSpdAvgNDrvnGroup_msgType;
typedef struct _c_DstRolCntAvgNonDrvnGroup_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype DstRolCntAvgNonDrvnV : 1;
  vbittype unused1 : 1;
  vbittype DstRolCntAvgNonDrvn_1 : 5;
  vbittype DstRolCntAvgNonDrvn_0 : 8;
} _c_DstRolCntAvgNonDrvnGroup_msgType;
typedef struct _c_WhlGrndVlctyLftNnDrvnGroup_0_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftNnDrvnV_0 : 1;
  vbittype WhlGrndVlctyLftNnDrvn_0_1 : 6;
  vbittype WhlGrndVlctyLftNnDrvn_0_0 : 8;
} _c_WhlGrndVlctyLftNnDrvnGroup_0_msgType;
typedef struct _c_WhlGrndVlctyRtNnDrvnGroup_0_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyRtNnDrvnV_0 : 1;
  vbittype WhlGrndVlctyRtNnDrvn_0_1 : 6;
  vbittype WhlGrndVlctyRtNnDrvn_0_0 : 8;
} _c_WhlGrndVlctyRtNnDrvnGroup_0_msgType;
typedef struct _c_WhlGrndVlctyLftDrvnGroup_0_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftDrvnV_0 : 1;
  vbittype WhlGrndVlctyLftDrvn_0_1 : 6;
  vbittype WhlGrndVlctyLftDrvn_0_0 : 8;
} _c_WhlGrndVlctyLftDrvnGroup_0_msgType;
typedef struct _c_WhlGrndVlctyRtDrvnGroup_0_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyRtDrvnV_0 : 1;
  vbittype WhlGrndVlctyRtDrvn_0_1 : 6;
  vbittype WhlGrndVlctyRtDrvn_0_0 : 8;
} _c_WhlGrndVlctyRtDrvnGroup_0_msgType;
typedef struct _c_TransEstGearGroup_msgTypeTag
{
  vbittype unused0 : 3;
  vbittype TransEstGearV : 1;
  vbittype TransEstGear : 4;
} _c_TransEstGearGroup_msgType;
typedef struct _c_TrnsShftLvrPosGroup_msgTypeTag
{
  vbittype unused0 : 3;
  vbittype TrnsShftLvrPosV : 1;
  vbittype TrnsShftLvrPos : 4;
} _c_TrnsShftLvrPosGroup_msgType;
typedef struct _c_BkupPwrModeMstrGroup_msgTypeTag
{
  vbittype BkupPwrModeMstrVDA : 1;
  vbittype unused0 : 7;
} _c_BkupPwrModeMstrGroup_msgType;
typedef struct _c_VSELatAccGroup_msgTypeTag
{
  vbittype unused0 : 3;
  vbittype VSELatAccV : 1;
  vbittype VSELatAcc_1 : 4;
  vbittype VSELatAcc_0 : 8;
} _c_VSELatAccGroup_msgType;
typedef struct _c_BrkPdlDrvAppPrsDetcdGroup_msgTypeTag
{
  vbittype BrkPdlDrvAppPrsDetcdV : 1;
  vbittype BrkPdlDrvAppPrsDetcd : 1;
  vbittype unused0 : 6;
} _c_BrkPdlDrvAppPrsDetcdGroup_msgType;
typedef struct _c_VehDynYawRateGroup_msgTypeTag
{
  vbittype unused0 : 3;
  vbittype VehDynYawRateV : 1;
  vbittype VehDynYawRate_1 : 4;
  vbittype VehDynYawRate_0 : 8;
} _c_VehDynYawRateGroup_msgType;
typedef struct _c_VehDynOvrUndrStrGroup_0_msgTypeTag
{
  vbittype unused0 : 5;
  vbittype VehDynOvrUndrStrV_0 : 1;
  vbittype VehDynOvrUndrStr_0_1 : 2;
  vbittype VehDynOvrUndrStr_0_0 : 8;
} _c_VehDynOvrUndrStrGroup_0_msgType;
typedef struct _c_LKATqOvrDltCmd_msgTypeTag
{
  vbittype unused0 : 4;
  vbittype LKATODC_TrqRqAct : 1;
  vbittype LKATODC_TrqVl_1 : 3;
  vbittype LKATODC_TrqVl_0 : 8;
} _c_LKATqOvrDltCmd_msgType;
typedef struct _c_ActAxleTrqGroup_msgTypeTag
{
  vbittype ActAxleTrqV : 1;
  vbittype ActAxleTrq_1 : 7;
  vbittype ActAxleTrq_0 : 8;
} _c_ActAxleTrqGroup_msgType;
typedef struct _c_WhlRotatStatLftDrvn_msgTypeTag
{
  vbittype WRSLDWhlDisTpRC : 2;
  vbittype WRSLDSeqNum : 2;
  vbittype WRSLDWhlRotStatRst : 1;
  vbittype WRSLDWhlDistVal : 1;
  vbittype WRSLDWhlDistPlsCntr_1 : 2;
  vbittype WRSLDWhlDistPlsCntr_0 : 8;
  vbittype WRSLDWhlDistTmstm_1 : 8;
  vbittype WRSLDWhlDistTmstm_0 : 8;
} _c_WhlRotatStatLftDrvn_msgType;
typedef struct _c_WhlRotatStatRtDrvn_msgTypeTag
{
  vbittype WRSRDWhlDisTpRC : 2;
  vbittype WRSRDSeqNum : 2;
  vbittype WRSRDWhlRotStatRst : 1;
  vbittype WRSRDWhlDistVal : 1;
  vbittype WRSRDWhlDistPlsCntr_1 : 2;
  vbittype WRSRDWhlDistPlsCntr_0 : 8;
  vbittype WRSRDWhlDistTmstm_1 : 8;
  vbittype WRSRDWhlDistTmstm_0 : 8;
} _c_WhlRotatStatRtDrvn_msgType;
typedef struct _c_WhlGrndVlctyLftNnDrvnGroup_1_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftNnDrvnV_1 : 1;
  vbittype WhlGrndVlctyLftNnDrvn_1_1 : 6;
  vbittype WhlGrndVlctyLftNnDrvn_1_0 : 8;
} _c_WhlGrndVlctyLftNnDrvnGroup_1_msgType;
typedef struct _c_WhlGrndVlctyRtNnDrvnGroup_1_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyRtNnDrvnV_1 : 1;
  vbittype WhlGrndVlctyRtNnDrvn_1_1 : 6;
  vbittype WhlGrndVlctyRtNnDrvn_1_0 : 8;
} _c_WhlGrndVlctyRtNnDrvnGroup_1_msgType;
typedef struct _c_WhlGrndVlctyLftDrvnGroup_1_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyLftDrvnV_1 : 1;
  vbittype WhlGrndVlctyLftDrvn_1_1 : 6;
  vbittype WhlGrndVlctyLftDrvn_1_0 : 8;
} _c_WhlGrndVlctyLftDrvnGroup_1_msgType;
typedef struct _c_WhlGrndVlctyRtDrvnGroup_1_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype WhlGrndVlctyRtDrvnV_1 : 1;
  vbittype WhlGrndVlctyRtDrvn_1_1 : 6;
  vbittype WhlGrndVlctyRtDrvn_1_0 : 8;
} _c_WhlGrndVlctyRtDrvnGroup_1_msgType;
typedef struct _c_StrWhlAngReq_msgTypeTag
{
  vbittype unused0 : 6;
  vbittype SWAR_ReqAct : 1;
  vbittype SWAR_ReqActV : 1;
  vbittype SWAR_TrgtAng_1 : 8;
  vbittype SWAR_TrgtAng_0 : 8;
} _c_StrWhlAngReq_msgType;
typedef struct _c_VSELongAccLoResGroup_msgTypeTag
{
  vbittype unused0 : 4;
  vbittype VSELongAccLoResV : 1;
  vbittype unused1 : 3;
  vbittype unused2 : 6;
  vbittype VSELongAccLoRes_1 : 2;
  vbittype VSELongAccLoRes_0 : 8;
} _c_VSELongAccLoResGroup_msgType;
typedef struct _c_VehDynOvrUndrStrGroup_1_msgTypeTag
{
  vbittype unused0 : 5;
  vbittype VehDynOvrUndrStrV_1 : 1;
  vbittype VehDynOvrUndrStr_1_1 : 2;
  vbittype VehDynOvrUndrStr_1_0 : 8;
} _c_VehDynOvrUndrStrGroup_1_msgType;




/* -----------------------------------------------------------------------------
    &&&~ Signal value names
 ----------------------------------------------------------------------------- */



/* -----------------------------------------------------------------------------
    &&&~ Message Unions
 ----------------------------------------------------------------------------- */

typedef union _c_PPEI_Hybrid_General_Status_3_HS_bufTag
{
  vuint8 _c[2];
  _c_PPEI_Hybrid_General_Status_3_HS_msgType PPEI_Hybrid_General_Status_3_HS;
  _c_PPEI_Hybrid_General_Status_3_HS_ActAxleTrqGroup_msgType PPEI_Hybrid_General_Status_3_HS_ActAxleTrqGroup;
} _c_PPEI_Hybrid_General_Status_3_HS_buf;
typedef union _c_Wheel_Pulses_HS_bufTag
{
  vuint8 _c[4];
  _c_Wheel_Pulses_HS_msgType Wheel_Pulses_HS;
} _c_Wheel_Pulses_HS_buf;
typedef union _c_Driving_Mode_Control_HS_bufTag
{
  vuint8 _c[5];
  _c_Driving_Mode_Control_HS_msgType Driving_Mode_Control_HS;
} _c_Driving_Mode_Control_HS_buf;
typedef union _c_Brake_Pedal_Driver_Status_HS_bufTag
{
  vuint8 _c[6];
  _c_Brake_Pedal_Driver_Status_HS_msgType Brake_Pedal_Driver_Status_HS;
} _c_Brake_Pedal_Driver_Status_HS_buf;
typedef union _c_Power_Steering_Information_HS_bufTag
{
  vuint8 _c[1];
  _c_Power_Steering_Information_HS_msgType Power_Steering_Information_HS;
} _c_Power_Steering_Information_HS_buf;
typedef union _c_DTC_Triggered_778_bufTag
{
  vuint8 _c[7];
  _c_DTC_Triggered_778_msgType DTC_Triggered_778;
  _c_DTC_Triggered_778_DTCInfo_778_msgType DTC_Triggered_778_DTCInfo_778;
} _c_DTC_Triggered_778_buf;
typedef union _c_PPEI_Steering_Wheel_Angle_bufTag
{
  vuint8 _c[8];
  _c_PPEI_Steering_Wheel_Angle_msgType PPEI_Steering_Wheel_Angle;
  _c_PPEI_Steering_Wheel_Angle_StrWhAngGroup_0_msgType PPEI_Steering_Wheel_Angle_StrWhAngGroup_0;
  _c_PPEI_Steering_Wheel_Angle_StrWhAngGrdGroup_0_msgType PPEI_Steering_Wheel_Angle_StrWhAngGrdGroup_0;
} _c_PPEI_Steering_Wheel_Angle_buf;
typedef union _c_PPEI_Vehicle_Speed_and_Distance_bufTag
{
  vuint8 _c[8];
  _c_PPEI_Vehicle_Speed_and_Distance_msgType PPEI_Vehicle_Speed_and_Distance;
  _c_PPEI_Vehicle_Speed_and_Distance_VehSpdAvgDrvnGroup_0_msgType PPEI_Vehicle_Speed_and_Distance_VehSpdAvgDrvnGroup_0;
  _c_PPEI_Vehicle_Speed_and_Distance_DistRollCntAvgDrvnGroup_msgType PPEI_Vehicle_Speed_and_Distance_DistRollCntAvgDrvnGroup;
  _c_PPEI_Vehicle_Speed_and_Distance_VehSpdAvgNDrvnGroup_msgType PPEI_Vehicle_Speed_and_Distance_VehSpdAvgNDrvnGroup;
  _c_PPEI_Vehicle_Speed_and_Distance_DstRolCntAvgNonDrvnGroup_msgType PPEI_Vehicle_Speed_and_Distance_DstRolCntAvgNonDrvnGroup;
} _c_PPEI_Vehicle_Speed_and_Distance_buf;
typedef union _c_NonDriven_Wheel_Grnd_Velocity_HS_bufTag
{
  vuint8 _c[5];
  _c_NonDriven_Wheel_Grnd_Velocity_HS_msgType NonDriven_Wheel_Grnd_Velocity_HS;
  _c_NonDriven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyLftNnDrvnGroup_0_msgType NonDriven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyLftNnDrvnGroup_0;
  _c_NonDriven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyRtNnDrvnGroup_0_msgType NonDriven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyRtNnDrvnGroup_0;
} _c_NonDriven_Wheel_Grnd_Velocity_HS_buf;
typedef union _c_PPEI_Engine_General_Status_4_bufTag
{
  vuint8 _c[3];
  _c_PPEI_Engine_General_Status_4_msgType PPEI_Engine_General_Status_4;
  _c_PPEI_Engine_General_Status_4_EngCltTmpGroup_msgType PPEI_Engine_General_Status_4_EngCltTmpGroup;
} _c_PPEI_Engine_General_Status_4_buf;
typedef union _c_PPEI_Engine_General_Status_1_bufTag
{
  vuint8 _c[7];
  _c_PPEI_Engine_General_Status_1_msgType PPEI_Engine_General_Status_1;
} _c_PPEI_Engine_General_Status_1_buf;
typedef union _c_PPEI_Trans_General_Status_2_bufTag
{
  vuint8 _c[6];
  _c_PPEI_Trans_General_Status_2_msgType PPEI_Trans_General_Status_2;
  _c_PPEI_Trans_General_Status_2_TransEstGearGroup_msgType PPEI_Trans_General_Status_2_TransEstGearGroup;
  _c_PPEI_Trans_General_Status_2_TrnsShftLvrPosGroup_msgType PPEI_Trans_General_Status_2_TrnsShftLvrPosGroup;
} _c_PPEI_Trans_General_Status_2_buf;
typedef union _c_PPEI_Platform_Eng_Cntrl_Requests_bufTag
{
  vuint8 _c[8];
  _c_PPEI_Platform_Eng_Cntrl_Requests_msgType PPEI_Platform_Eng_Cntrl_Requests;
  _c_PPEI_Platform_Eng_Cntrl_Requests_EngOffTmExtRngGroup_msgType PPEI_Platform_Eng_Cntrl_Requests_EngOffTmExtRngGroup;
  _c_PPEI_Platform_Eng_Cntrl_Requests_OtsAirTmpCrValGroup_msgType PPEI_Platform_Eng_Cntrl_Requests_OtsAirTmpCrValGroup;
} _c_PPEI_Platform_Eng_Cntrl_Requests_buf;
typedef union _c_PPEI_Platform_General_Status_bufTag
{
  vuint8 _c[8];
  _c_PPEI_Platform_General_Status_msgType PPEI_Platform_General_Status;
  _c_PPEI_Platform_General_Status_BkupPwrModeMstrGroup_msgType PPEI_Platform_General_Status_BkupPwrModeMstrGroup;
} _c_PPEI_Platform_General_Status_buf;
typedef union _c_Driven_Wheel_Grnd_Velocity_HS_bufTag
{
  vuint8 _c[5];
  _c_Driven_Wheel_Grnd_Velocity_HS_msgType Driven_Wheel_Grnd_Velocity_HS;
  _c_Driven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyLftDrvnGroup_0_msgType Driven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyLftDrvnGroup_0;
  _c_Driven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyRtDrvnGroup_0_msgType Driven_Wheel_Grnd_Velocity_HS_WhlGrndVlctyRtDrvnGroup_0;
} _c_Driven_Wheel_Grnd_Velocity_HS_buf;
typedef union _c_PPEI_Driven_Whl_Rotational_Stat_bufTag
{
  vuint8 _c[8];
  _c_PPEI_Driven_Whl_Rotational_Stat_msgType PPEI_Driven_Whl_Rotational_Stat;
  _c_PPEI_Driven_Whl_Rotational_Stat_WhlRotatStatLftDrvn_msgType PPEI_Driven_Whl_Rotational_Stat_WhlRotatStatLftDrvn;
  _c_PPEI_Driven_Whl_Rotational_Stat_WhlRotatStatRtDrvn_msgType PPEI_Driven_Whl_Rotational_Stat_WhlRotatStatRtDrvn;
} _c_PPEI_Driven_Whl_Rotational_Stat_buf;
typedef union _c_PPEI_Chassis_General_Status_1_bufTag
{
  vuint8 _c[8];
  _c_PPEI_Chassis_General_Status_1_msgType PPEI_Chassis_General_Status_1;
  _c_PPEI_Chassis_General_Status_1_VSELatAccGroup_msgType PPEI_Chassis_General_Status_1_VSELatAccGroup;
  _c_PPEI_Chassis_General_Status_1_BrkPdlDrvAppPrsDetcdGroup_msgType PPEI_Chassis_General_Status_1_BrkPdlDrvAppPrsDetcdGroup;
  _c_PPEI_Chassis_General_Status_1_VehDynYawRateGroup_msgType PPEI_Chassis_General_Status_1_VehDynYawRateGroup;
  _c_PPEI_Chassis_General_Status_1_VehDynOvrUndrStrGroup_0_msgType PPEI_Chassis_General_Status_1_VehDynOvrUndrStrGroup_0;
} _c_PPEI_Chassis_General_Status_1_buf;
typedef union _c_Antilock_Brake_and_TC_Status_HS_bufTag
{
  vuint8 _c[1];
  _c_Antilock_Brake_and_TC_Status_HS_msgType Antilock_Brake_and_TC_Status_HS;
} _c_Antilock_Brake_and_TC_Status_HS_buf;
typedef union _c_UUDT_Resp_From_EHPS_EPS_HS_bufTag
{
  vuint8 _c[8];
  _c_UUDT_Resp_From_EHPS_EPS_HS_msgType UUDT_Resp_From_EHPS_EPS_HS;
} _c_UUDT_Resp_From_EHPS_EPS_HS_buf;
typedef union _c_USDT_Resp_From_EHPS_EPS_HS_bufTag
{
  vuint8 _c[8];
  _c_USDT_Resp_From_EHPS_EPS_HS_msgType USDT_Resp_From_EHPS_EPS_HS;
} _c_USDT_Resp_From_EHPS_EPS_HS_buf;
typedef union _c_LKA_Steering_Trq_Overlay_Stat_HS_bufTag
{
  vuint8 _c[8];
  _c_LKA_Steering_Trq_Overlay_Stat_HS_msgType LKA_Steering_Trq_Overlay_Stat_HS;
  _c_LKA_Steering_Trq_Overlay_Stat_HS_HndsOffStrWhlDtStGroup_msgType LKA_Steering_Trq_Overlay_Stat_HS_HndsOffStrWhlDtStGroup;
  _c_LKA_Steering_Trq_Overlay_Stat_HS_LKADrvAppldTrqGroup_msgType LKA_Steering_Trq_Overlay_Stat_HS_LKADrvAppldTrqGroup;
} _c_LKA_Steering_Trq_Overlay_Stat_HS_buf;
typedef union _c_LKA_Steering_Torque_Cmd_HS_bufTag
{
  vuint8 _c[4];
  _c_LKA_Steering_Torque_Cmd_HS_msgType LKA_Steering_Torque_Cmd_HS;
  _c_LKA_Steering_Torque_Cmd_HS_LKATqOvrDltCmd_msgType LKA_Steering_Torque_Cmd_HS_LKATqOvrDltCmd;
} _c_LKA_Steering_Torque_Cmd_HS_buf;
typedef union _c_Xcp_Master_Msg_bufTag
{
  vuint8 _c[8];
  _c_Xcp_Master_Msg_msgType Xcp_Master_Msg;
} _c_Xcp_Master_Msg_buf;
typedef union _c_Xcp_Slave_Msg_bufTag
{
  vuint8 _c[8];
  _c_Xcp_Slave_Msg_msgType Xcp_Slave_Msg;
} _c_Xcp_Slave_Msg_buf;
typedef union _c_T1_HostToTarget_bufTag
{
  vuint8 _c[8];
  _c_T1_HostToTarget_msgType T1_HostToTarget;
} _c_T1_HostToTarget_buf;
typedef union _c_Park_Assist_Parallel_CE_bufTag
{
  vuint8 _c[7];
  _c_Park_Assist_Parallel_CE_msgType Park_Assist_Parallel_CE;
  _c_Park_Assist_Parallel_CE_StrWhlAngReq_msgType Park_Assist_Parallel_CE_StrWhlAngReq;
} _c_Park_Assist_Parallel_CE_buf;
typedef union _c_Electric_Power_Steering_CE_bufTag
{
  vuint8 _c[4];
  _c_Electric_Power_Steering_CE_msgType Electric_Power_Steering_CE;
  _c_Electric_Power_Steering_CE_DrvStrIntfrDtcdGroup_msgType Electric_Power_Steering_CE_DrvStrIntfrDtcdGroup;
} _c_Electric_Power_Steering_CE_buf;
typedef union _c_UUDT_Resp_From_EPS_EPS_JR_CE_bufTag
{
  vuint8 _c[8];
  _c_UUDT_Resp_From_EPS_EPS_JR_CE_msgType UUDT_Resp_From_EPS_EPS_JR_CE;
} _c_UUDT_Resp_From_EPS_EPS_JR_CE_buf;
typedef union _c_USDT_Resp_From_EPS_EPS_JR_CE_bufTag
{
  vuint8 _c[8];
  _c_USDT_Resp_From_EPS_EPS_JR_CE_msgType USDT_Resp_From_EPS_EPS_JR_CE;
} _c_USDT_Resp_From_EPS_EPS_JR_CE_buf;
typedef union _c_Steering_Torque_Command_CE_bufTag
{
  vuint8 _c[8];
  _c_Steering_Torque_Command_CE_msgType Steering_Torque_Command_CE;
} _c_Steering_Torque_Command_CE_buf;
typedef union _c_Steering_Torque_Overlay_Stat_CE_bufTag
{
  vuint8 _c[8];
  _c_Steering_Torque_Overlay_Stat_CE_msgType Steering_Torque_Overlay_Stat_CE;
} _c_Steering_Torque_Overlay_Stat_CE_buf;
typedef union _c_Vehicle_Dynamics_ESC_Hyb_CE_bufTag
{
  vuint8 _c[5];
  _c_Vehicle_Dynamics_ESC_Hyb_CE_msgType Vehicle_Dynamics_ESC_Hyb_CE;
  _c_Vehicle_Dynamics_ESC_Hyb_CE_VSELongAccLoResGroup_msgType Vehicle_Dynamics_ESC_Hyb_CE_VSELongAccLoResGroup;
  _c_Vehicle_Dynamics_ESC_Hyb_CE_VehDynOvrUndrStrGroup_1_msgType Vehicle_Dynamics_ESC_Hyb_CE_VehDynOvrUndrStrGroup_1;
} _c_Vehicle_Dynamics_ESC_Hyb_CE_buf;
typedef union _c_NonDriven_Wheel_Grnd_Velocity_CE_bufTag
{
  vuint8 _c[5];
  _c_NonDriven_Wheel_Grnd_Velocity_CE_msgType NonDriven_Wheel_Grnd_Velocity_CE;
  _c_NonDriven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyLftNnDrvnGroup_1_msgType NonDriven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyLftNnDrvnGroup_1;
  _c_NonDriven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyRtNnDrvnGroup_1_msgType NonDriven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyRtNnDrvnGroup_1;
} _c_NonDriven_Wheel_Grnd_Velocity_CE_buf;
typedef union _c_Driven_Wheel_Grnd_Velocity_CE_bufTag
{
  vuint8 _c[5];
  _c_Driven_Wheel_Grnd_Velocity_CE_msgType Driven_Wheel_Grnd_Velocity_CE;
  _c_Driven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyLftDrvnGroup_1_msgType Driven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyLftDrvnGroup_1;
  _c_Driven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyRtDrvnGroup_1_msgType Driven_Wheel_Grnd_Velocity_CE_WhlGrndVlctyRtDrvnGroup_1;
} _c_Driven_Wheel_Grnd_Velocity_CE_buf;
typedef union _c_PPEI_Steering_Wheel_Angle_CE_bufTag
{
  vuint8 _c[8];
  _c_PPEI_Steering_Wheel_Angle_CE_msgType PPEI_Steering_Wheel_Angle_CE;
  _c_PPEI_Steering_Wheel_Angle_CE_StrWhAngGroup_1_msgType PPEI_Steering_Wheel_Angle_CE_StrWhAngGroup_1;
  _c_PPEI_Steering_Wheel_Angle_CE_StrWhAngGrdGroup_1_msgType PPEI_Steering_Wheel_Angle_CE_StrWhAngGrdGroup_1;
} _c_PPEI_Steering_Wheel_Angle_CE_buf;
/* -----------------------------------------------------------------------------
    &&&~ Signal Unions for group signals
 ----------------------------------------------------------------------------- */

typedef union _c_DTCInfo_778_bufTag
{
  vuint8 _c[7];
  _c_DTCInfo_778_msgType DTCInfo_778;
} _c_DTCInfo_778_buf;
typedef union _c_StrWhAngGroup_0_bufTag
{
  vuint8 _c[3];
  _c_StrWhAngGroup_0_msgType StrWhAngGroup_0;
} _c_StrWhAngGroup_0_buf;
typedef union _c_StrWhAngGrdGroup_0_bufTag
{
  vuint8 _c[2];
  _c_StrWhAngGrdGroup_0_msgType StrWhAngGrdGroup_0;
} _c_StrWhAngGrdGroup_0_buf;
typedef union _c_HndsOffStrWhlDtStGroup_bufTag
{
  vuint8 _c[1];
  _c_HndsOffStrWhlDtStGroup_msgType HndsOffStrWhlDtStGroup;
} _c_HndsOffStrWhlDtStGroup_buf;
typedef union _c_LKADrvAppldTrqGroup_bufTag
{
  vuint8 _c[2];
  _c_LKADrvAppldTrqGroup_msgType LKADrvAppldTrqGroup;
} _c_LKADrvAppldTrqGroup_buf;
typedef union _c_DrvStrIntfrDtcdGroup_bufTag
{
  vuint8 _c[1];
  _c_DrvStrIntfrDtcdGroup_msgType DrvStrIntfrDtcdGroup;
} _c_DrvStrIntfrDtcdGroup_buf;
typedef union _c_StrWhAngGroup_1_bufTag
{
  vuint8 _c[3];
  _c_StrWhAngGroup_1_msgType StrWhAngGroup_1;
} _c_StrWhAngGroup_1_buf;
typedef union _c_StrWhAngGrdGroup_1_bufTag
{
  vuint8 _c[2];
  _c_StrWhAngGrdGroup_1_msgType StrWhAngGrdGroup_1;
} _c_StrWhAngGrdGroup_1_buf;
typedef union _c_EngCltTmpGroup_bufTag
{
  vuint8 _c[3];
  _c_EngCltTmpGroup_msgType EngCltTmpGroup;
} _c_EngCltTmpGroup_buf;
typedef union _c_EngOffTmExtRngGroup_bufTag
{
  vuint8 _c[2];
  _c_EngOffTmExtRngGroup_msgType EngOffTmExtRngGroup;
} _c_EngOffTmExtRngGroup_buf;
typedef union _c_OtsAirTmpCrValGroup_bufTag
{
  vuint8 _c[2];
  _c_OtsAirTmpCrValGroup_msgType OtsAirTmpCrValGroup;
} _c_OtsAirTmpCrValGroup_buf;
typedef union _c_VehSpdAvgDrvnGroup_0_bufTag
{
  vuint8 _c[2];
  _c_VehSpdAvgDrvnGroup_0_msgType VehSpdAvgDrvnGroup_0;
} _c_VehSpdAvgDrvnGroup_0_buf;
typedef union _c_DistRollCntAvgDrvnGroup_bufTag
{
  vuint8 _c[2];
  _c_DistRollCntAvgDrvnGroup_msgType DistRollCntAvgDrvnGroup;
} _c_DistRollCntAvgDrvnGroup_buf;
typedef union _c_VehSpdAvgNDrvnGroup_bufTag
{
  vuint8 _c[2];
  _c_VehSpdAvgNDrvnGroup_msgType VehSpdAvgNDrvnGroup;
} _c_VehSpdAvgNDrvnGroup_buf;
typedef union _c_DstRolCntAvgNonDrvnGroup_bufTag
{
  vuint8 _c[2];
  _c_DstRolCntAvgNonDrvnGroup_msgType DstRolCntAvgNonDrvnGroup;
} _c_DstRolCntAvgNonDrvnGroup_buf;
typedef union _c_WhlGrndVlctyLftNnDrvnGroup_0_bufTag
{
  vuint8 _c[2];
  _c_WhlGrndVlctyLftNnDrvnGroup_0_msgType WhlGrndVlctyLftNnDrvnGroup_0;
} _c_WhlGrndVlctyLftNnDrvnGroup_0_buf;
typedef union _c_WhlGrndVlctyRtNnDrvnGroup_0_bufTag
{
  vuint8 _c[2];
  _c_WhlGrndVlctyRtNnDrvnGroup_0_msgType WhlGrndVlctyRtNnDrvnGroup_0;
} _c_WhlGrndVlctyRtNnDrvnGroup_0_buf;
typedef union _c_WhlGrndVlctyLftDrvnGroup_0_bufTag
{
  vuint8 _c[2];
  _c_WhlGrndVlctyLftDrvnGroup_0_msgType WhlGrndVlctyLftDrvnGroup_0;
} _c_WhlGrndVlctyLftDrvnGroup_0_buf;
typedef union _c_WhlGrndVlctyRtDrvnGroup_0_bufTag
{
  vuint8 _c[2];
  _c_WhlGrndVlctyRtDrvnGroup_0_msgType WhlGrndVlctyRtDrvnGroup_0;
} _c_WhlGrndVlctyRtDrvnGroup_0_buf;
typedef union _c_TransEstGearGroup_bufTag
{
  vuint8 _c[1];
  _c_TransEstGearGroup_msgType TransEstGearGroup;
} _c_TransEstGearGroup_buf;
typedef union _c_TrnsShftLvrPosGroup_bufTag
{
  vuint8 _c[1];
  _c_TrnsShftLvrPosGroup_msgType TrnsShftLvrPosGroup;
} _c_TrnsShftLvrPosGroup_buf;
typedef union _c_BkupPwrModeMstrGroup_bufTag
{
  vuint8 _c[1];
  _c_BkupPwrModeMstrGroup_msgType BkupPwrModeMstrGroup;
} _c_BkupPwrModeMstrGroup_buf;
typedef union _c_VSELatAccGroup_bufTag
{
  vuint8 _c[2];
  _c_VSELatAccGroup_msgType VSELatAccGroup;
} _c_VSELatAccGroup_buf;
typedef union _c_BrkPdlDrvAppPrsDetcdGroup_bufTag
{
  vuint8 _c[1];
  _c_BrkPdlDrvAppPrsDetcdGroup_msgType BrkPdlDrvAppPrsDetcdGroup;
} _c_BrkPdlDrvAppPrsDetcdGroup_buf;
typedef union _c_VehDynYawRateGroup_bufTag
{
  vuint8 _c[2];
  _c_VehDynYawRateGroup_msgType VehDynYawRateGroup;
} _c_VehDynYawRateGroup_buf;
typedef union _c_VehDynOvrUndrStrGroup_0_bufTag
{
  vuint8 _c[2];
  _c_VehDynOvrUndrStrGroup_0_msgType VehDynOvrUndrStrGroup_0;
} _c_VehDynOvrUndrStrGroup_0_buf;
typedef union _c_LKATqOvrDltCmd_bufTag
{
  vuint8 _c[2];
  _c_LKATqOvrDltCmd_msgType LKATqOvrDltCmd;
} _c_LKATqOvrDltCmd_buf;
typedef union _c_ActAxleTrqGroup_bufTag
{
  vuint8 _c[2];
  _c_ActAxleTrqGroup_msgType ActAxleTrqGroup;
} _c_ActAxleTrqGroup_buf;
typedef union _c_WhlRotatStatLftDrvn_bufTag
{
  vuint8 _c[4];
  _c_WhlRotatStatLftDrvn_msgType WhlRotatStatLftDrvn;
} _c_WhlRotatStatLftDrvn_buf;
typedef union _c_WhlRotatStatRtDrvn_bufTag
{
  vuint8 _c[4];
  _c_WhlRotatStatRtDrvn_msgType WhlRotatStatRtDrvn;
} _c_WhlRotatStatRtDrvn_buf;
typedef union _c_WhlGrndVlctyLftNnDrvnGroup_1_bufTag
{
  vuint8 _c[2];
  _c_WhlGrndVlctyLftNnDrvnGroup_1_msgType WhlGrndVlctyLftNnDrvnGroup_1;
} _c_WhlGrndVlctyLftNnDrvnGroup_1_buf;
typedef union _c_WhlGrndVlctyRtNnDrvnGroup_1_bufTag
{
  vuint8 _c[2];
  _c_WhlGrndVlctyRtNnDrvnGroup_1_msgType WhlGrndVlctyRtNnDrvnGroup_1;
} _c_WhlGrndVlctyRtNnDrvnGroup_1_buf;
typedef union _c_WhlGrndVlctyLftDrvnGroup_1_bufTag
{
  vuint8 _c[2];
  _c_WhlGrndVlctyLftDrvnGroup_1_msgType WhlGrndVlctyLftDrvnGroup_1;
} _c_WhlGrndVlctyLftDrvnGroup_1_buf;
typedef union _c_WhlGrndVlctyRtDrvnGroup_1_bufTag
{
  vuint8 _c[2];
  _c_WhlGrndVlctyRtDrvnGroup_1_msgType WhlGrndVlctyRtDrvnGroup_1;
} _c_WhlGrndVlctyRtDrvnGroup_1_buf;
typedef union _c_StrWhlAngReq_bufTag
{
  vuint8 _c[3];
  _c_StrWhlAngReq_msgType StrWhlAngReq;
} _c_StrWhlAngReq_buf;
typedef union _c_VSELongAccLoResGroup_bufTag
{
  vuint8 _c[3];
  _c_VSELongAccLoResGroup_msgType VSELongAccLoResGroup;
} _c_VSELongAccLoResGroup_buf;
typedef union _c_VehDynOvrUndrStrGroup_1_bufTag
{
  vuint8 _c[2];
  _c_VehDynOvrUndrStrGroup_1_msgType VehDynOvrUndrStrGroup_1;
} _c_VehDynOvrUndrStrGroup_1_buf;




/* -----------------------------------------------------------------------------
    &&&~ Message Buffers
 ----------------------------------------------------------------------------- */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Hybrid_General_Status_3_HS_buf V_MEMRAM2 PPEI_Hybrid_General_Status_3_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Wheel_Pulses_HS_buf V_MEMRAM2 Wheel_Pulses_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Driving_Mode_Control_HS_buf V_MEMRAM2 Driving_Mode_Control_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Brake_Pedal_Driver_Status_HS_buf V_MEMRAM2 Brake_Pedal_Driver_Status_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Power_Steering_Information_HS_buf V_MEMRAM2 Power_Steering_Information_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_DTC_Triggered_778_buf V_MEMRAM2 DTC_Triggered_778;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Steering_Wheel_Angle_buf V_MEMRAM2 PPEI_Steering_Wheel_Angle;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Vehicle_Speed_and_Distance_buf V_MEMRAM2 PPEI_Vehicle_Speed_and_Distance;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_NonDriven_Wheel_Grnd_Velocity_HS_buf V_MEMRAM2 NonDriven_Wheel_Grnd_Velocity_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Engine_General_Status_4_buf V_MEMRAM2 PPEI_Engine_General_Status_4;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Engine_General_Status_1_buf V_MEMRAM2 PPEI_Engine_General_Status_1;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Trans_General_Status_2_buf V_MEMRAM2 PPEI_Trans_General_Status_2;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Platform_Eng_Cntrl_Requests_buf V_MEMRAM2 PPEI_Platform_Eng_Cntrl_Requests;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Platform_General_Status_buf V_MEMRAM2 PPEI_Platform_General_Status;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Driven_Wheel_Grnd_Velocity_HS_buf V_MEMRAM2 Driven_Wheel_Grnd_Velocity_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Driven_Whl_Rotational_Stat_buf V_MEMRAM2 PPEI_Driven_Whl_Rotational_Stat;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Chassis_General_Status_1_buf V_MEMRAM2 PPEI_Chassis_General_Status_1;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Antilock_Brake_and_TC_Status_HS_buf V_MEMRAM2 Antilock_Brake_and_TC_Status_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_UUDT_Resp_From_EHPS_EPS_HS_buf V_MEMRAM2 UUDT_Resp_From_EHPS_EPS_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_USDT_Resp_From_EHPS_EPS_HS_buf V_MEMRAM2 USDT_Resp_From_EHPS_EPS_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_LKA_Steering_Trq_Overlay_Stat_HS_buf V_MEMRAM2 LKA_Steering_Trq_Overlay_Stat_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_LKA_Steering_Torque_Cmd_HS_buf V_MEMRAM2 LKA_Steering_Torque_Cmd_HS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Xcp_Master_Msg_buf V_MEMRAM2 Xcp_Master_Msg;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Xcp_Slave_Msg_buf V_MEMRAM2 Xcp_Slave_Msg;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_T1_HostToTarget_buf V_MEMRAM2 T1_HostToTarget;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Park_Assist_Parallel_CE_buf V_MEMRAM2 Park_Assist_Parallel_CE;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Electric_Power_Steering_CE_buf V_MEMRAM2 Electric_Power_Steering_CE;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_UUDT_Resp_From_EPS_EPS_JR_CE_buf V_MEMRAM2 UUDT_Resp_From_EPS_EPS_JR_CE;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_USDT_Resp_From_EPS_EPS_JR_CE_buf V_MEMRAM2 USDT_Resp_From_EPS_EPS_JR_CE;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Steering_Torque_Command_CE_buf V_MEMRAM2 Steering_Torque_Command_CE;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Steering_Torque_Overlay_Stat_CE_buf V_MEMRAM2 Steering_Torque_Overlay_Stat_CE;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Vehicle_Dynamics_ESC_Hyb_CE_buf V_MEMRAM2 Vehicle_Dynamics_ESC_Hyb_CE;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_NonDriven_Wheel_Grnd_Velocity_CE_buf V_MEMRAM2 NonDriven_Wheel_Grnd_Velocity_CE;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Driven_Wheel_Grnd_Velocity_CE_buf V_MEMRAM2 Driven_Wheel_Grnd_Velocity_CE;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PPEI_Steering_Wheel_Angle_CE_buf V_MEMRAM2 PPEI_Steering_Wheel_Angle_CE;
/* RAM CATEGORY 2 END */

/* -----------------------------------------------------------------------------
    &&&~ Extern decl for message buffer for group signals
 ----------------------------------------------------------------------------- */

V_MEMRAM0 extern  V_MEMRAM1 _c_DTCInfo_778_buf V_MEMRAM2 DTCInfo_778;
V_MEMRAM0 extern  V_MEMRAM1 _c_StrWhAngGroup_0_buf V_MEMRAM2 StrWhAngGroup_0;
V_MEMRAM0 extern  V_MEMRAM1 _c_StrWhAngGrdGroup_0_buf V_MEMRAM2 StrWhAngGrdGroup_0;
V_MEMRAM0 extern  V_MEMRAM1 _c_HndsOffStrWhlDtStGroup_buf V_MEMRAM2 HndsOffStrWhlDtStGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_LKADrvAppldTrqGroup_buf V_MEMRAM2 LKADrvAppldTrqGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_DrvStrIntfrDtcdGroup_buf V_MEMRAM2 DrvStrIntfrDtcdGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_StrWhAngGroup_1_buf V_MEMRAM2 StrWhAngGroup_1;
V_MEMRAM0 extern  V_MEMRAM1 _c_StrWhAngGrdGroup_1_buf V_MEMRAM2 StrWhAngGrdGroup_1;
V_MEMRAM0 extern  V_MEMRAM1 _c_EngCltTmpGroup_buf V_MEMRAM2 EngCltTmpGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_EngOffTmExtRngGroup_buf V_MEMRAM2 EngOffTmExtRngGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_OtsAirTmpCrValGroup_buf V_MEMRAM2 OtsAirTmpCrValGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_VehSpdAvgDrvnGroup_0_buf V_MEMRAM2 VehSpdAvgDrvnGroup_0;
V_MEMRAM0 extern  V_MEMRAM1 _c_DistRollCntAvgDrvnGroup_buf V_MEMRAM2 DistRollCntAvgDrvnGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_VehSpdAvgNDrvnGroup_buf V_MEMRAM2 VehSpdAvgNDrvnGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_DstRolCntAvgNonDrvnGroup_buf V_MEMRAM2 DstRolCntAvgNonDrvnGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_WhlGrndVlctyLftNnDrvnGroup_0_buf V_MEMRAM2 WhlGrndVlctyLftNnDrvnGroup_0;
V_MEMRAM0 extern  V_MEMRAM1 _c_WhlGrndVlctyRtNnDrvnGroup_0_buf V_MEMRAM2 WhlGrndVlctyRtNnDrvnGroup_0;
V_MEMRAM0 extern  V_MEMRAM1 _c_WhlGrndVlctyLftDrvnGroup_0_buf V_MEMRAM2 WhlGrndVlctyLftDrvnGroup_0;
V_MEMRAM0 extern  V_MEMRAM1 _c_WhlGrndVlctyRtDrvnGroup_0_buf V_MEMRAM2 WhlGrndVlctyRtDrvnGroup_0;
V_MEMRAM0 extern  V_MEMRAM1 _c_TransEstGearGroup_buf V_MEMRAM2 TransEstGearGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_TrnsShftLvrPosGroup_buf V_MEMRAM2 TrnsShftLvrPosGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_BkupPwrModeMstrGroup_buf V_MEMRAM2 BkupPwrModeMstrGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_VSELatAccGroup_buf V_MEMRAM2 VSELatAccGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_BrkPdlDrvAppPrsDetcdGroup_buf V_MEMRAM2 BrkPdlDrvAppPrsDetcdGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_VehDynYawRateGroup_buf V_MEMRAM2 VehDynYawRateGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_VehDynOvrUndrStrGroup_0_buf V_MEMRAM2 VehDynOvrUndrStrGroup_0;
V_MEMRAM0 extern  V_MEMRAM1 _c_LKATqOvrDltCmd_buf V_MEMRAM2 LKATqOvrDltCmd;
V_MEMRAM0 extern  V_MEMRAM1 _c_ActAxleTrqGroup_buf V_MEMRAM2 ActAxleTrqGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_WhlRotatStatLftDrvn_buf V_MEMRAM2 WhlRotatStatLftDrvn;
V_MEMRAM0 extern  V_MEMRAM1 _c_WhlRotatStatRtDrvn_buf V_MEMRAM2 WhlRotatStatRtDrvn;
V_MEMRAM0 extern  V_MEMRAM1 _c_WhlGrndVlctyLftNnDrvnGroup_1_buf V_MEMRAM2 WhlGrndVlctyLftNnDrvnGroup_1;
V_MEMRAM0 extern  V_MEMRAM1 _c_WhlGrndVlctyRtNnDrvnGroup_1_buf V_MEMRAM2 WhlGrndVlctyRtNnDrvnGroup_1;
V_MEMRAM0 extern  V_MEMRAM1 _c_WhlGrndVlctyLftDrvnGroup_1_buf V_MEMRAM2 WhlGrndVlctyLftDrvnGroup_1;
V_MEMRAM0 extern  V_MEMRAM1 _c_WhlGrndVlctyRtDrvnGroup_1_buf V_MEMRAM2 WhlGrndVlctyRtDrvnGroup_1;
V_MEMRAM0 extern  V_MEMRAM1 _c_StrWhlAngReq_buf V_MEMRAM2 StrWhlAngReq;
V_MEMRAM0 extern  V_MEMRAM1 _c_VSELongAccLoResGroup_buf V_MEMRAM2 VSELongAccLoResGroup;
V_MEMRAM0 extern  V_MEMRAM1 _c_VehDynOvrUndrStrGroup_1_buf V_MEMRAM2 VehDynOvrUndrStrGroup_1;






/* disable magic number check for support of multiple projects */
#ifndef SKIP_MAGIC_NUMBER
#define SKIP_MAGIC_NUMBER
#endif

#include "drv_par_1.h"


/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 133574485
      #error "The magic number of the generated file <C:\Synergy\GM_C1XX_EPS_TMS570-dzxvzg\GM_C1XX_EPS_TMS570\SwProject\Source\_GenData\drv_par.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 133574485
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __DRV_PAR_H__ */
