/* -----------------------------------------------------------------------------
  Filename:    gmlcal.h
  Description: Toolversion: 08.31.00.01.01.01.23.01.00.00
                
                Serial Number: CBD1010123
                Customer Info: Nxtr
                               Package: GMLAN 3.0 Multi Channel 
                               Micro: TI TMS570 LS2125
                               Compiler: Texas Instruments 4.9.0
                
                
                Generator Fwk   : GENy 
                Generator Module: Nm_Gmlan_Gm
                
                Configuration   : C:\Synergy\GM_C1XX_EPS_TMS570-zz4r1x1\GM_C1XX_EPS_TMS570\Tools\AsrProject\GENy\RT_2.0_Mod.gny
                
                ECU: 
                        TargetSystem: Hw_Tms470/570Cpu (Dcan)
                        Compiler:     TexasInstruments
                        Derivates:    TMS570PSFC66
                
                Channel "Channel0":
                        Databasefile: C:\Synergy\GM_C1XX_EPS_TMS570-zz4r1x1\GM_C1XX_EPS_TMS570\Tools\AsrProject\GENy\GlobalA_HS.dbc
                        Bussystem:    CAN
                        Manufacturer: General Motors
                        Node:         EPS_HS
                Channel "Channel1":
                        Databasefile: C:\Synergy\GM_C1XX_EPS_TMS570-zz4r1x1\GM_C1XX_EPS_TMS570\Tools\AsrProject\GENy\GlobalA_CE.dbc
                        Bussystem:    CAN
                        Manufacturer: General Motors
                        Node:         EPS_CE

  Generated by , 2014-07-30  14:06:24
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2008 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__GMLCAL_H__)
#define __GMLCAL_H__

#include "v_cfg.h"
#include "v_def.h"
#include "nm_cfg.h"
#ifdef VGEN_ENABLE_IL_VECTOR
#include "il_inc.h"
#endif

#define GMLCAL_START_SEC_CONST
/*lint -e537*/
/* 2007-11-26, vismas: do not inform about multiple includes: MemDef.h is intended to be multiply included */
#include "MemDef.h"
/*lint +e537*/
#ifdef VGEN_ENABLE_NM_GMLAN
GMLCAL_MEMROM0 extern GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 nmInitDelayTimeCalCnt[kNmNumberOfChannels];

GMLCAL_MEMROM0 extern GMLCAL_MEMROM1 vuint16 GMLCAL_MEMROM2 nmBusOffRecoverTimeCalCnt[kNmNumberOfChannels];

GMLCAL_MEMROM0 extern GMLCAL_MEMROM1 vuint16 GMLCAL_MEMROM2 nmVNMFStartSendCalCnt[kNmNumberOfChannels];

GMLCAL_MEMROM0 extern GMLCAL_MEMROM1 vuint16 GMLCAL_MEMROM2 nmVNMFSendTimeCalCnt[kNmNumberOfChannels];


#endif

/* -----------------------------------------------------------------------------
    &&&~ Il_Vector_Gmlcal start
 ----------------------------------------------------------------------------- */

#if defined(VGEN_ENABLE_IL_VECTOR)
#if defined(IL_ENABLE_TX)
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 IlVnTxSendOnInit[kIlNrOfPackedTxObjectBytes];
#endif


#if defined(C_MULTIPLE_RECEIVE_CHANNEL) && (kIlNumberOfChannels > 1) && defined(IL_ENABLE_RX_EXT_TIMEOUT)
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 IltRxExtIDTimeoutCounter GMLCAL_MEMROM2 kGMLANNodeStatusTimeoutTimeCalCnt[kIlNumberOfChannels];
#endif


#if defined(IL_ENABLE_RX)
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 IlVnRxMessageEnabled[kIlNrOfPackedRxObjectBytes];
#endif


#if defined(IL_ENABLE_TX)
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 IlVnTxMessageEnabled[kIlNrOfPackedTxObjectBytes];
#endif


/* -----------------------------------------------------------------------------
    &&&~ TxDefaultInitValue Message Tables
 ----------------------------------------------------------------------------- */

GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 DTC_Triggered_778IlTxDefaultInitValue[7];
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 PPEI_Steering_Wheel_AngleIlTxDefaultInitValue[8];
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 LKA_Steering_Trq_Overlay_Stat_HSIlTxDefaultInitValue[8];
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 Power_Steering_Information_HSIlTxDefaultInitValue[1];
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 Electric_Power_Steering_CEIlTxDefaultInitValue[4];
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 PPEI_Steering_Wheel_Angle_CEIlTxDefaultInitValue[8];
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 vuint8 GMLCAL_MEMROM2 Steering_Torque_Overlay_Stat_CEIlTxDefaultInitValue[8];


#if defined(IL_ENABLE_TX)
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 IltTxCounter GMLCAL_MEMROM2 IlTxStartCycles[kIlNumberOfTxObjects];
#endif


#if defined(IL_ENABLE_TX)
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 IltTxUpdateCounter GMLCAL_MEMROM2 IlTxUpdateCycles[kIlNumberOfTxObjects];
#endif


#if defined(IL_ENABLE_TX)
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 IltTxCounter GMLCAL_MEMROM2 IlTxCyclicCycles[kIlNumberOfTxObjects];
#endif


#if defined(IL_ENABLE_TX) && (defined(IL_ENABLE_TX_CYCLIC_EVENT) || defined(IL_ENABLE_TX_SECURE_EVENT) || defined(IL_ENABLE_TX_FAST_ON_START))
GMLCAL_MEMROM0 extern  GMLCAL_MEMROM1 IltTxCounter GMLCAL_MEMROM2 IlTxEventCycles[kIlNumberOfTxObjects];
#endif


#endif

/* -----------------------------------------------------------------------------
    &&&~ Il_Vector_Gmlcal end
 ----------------------------------------------------------------------------- */


#define GMLCAL_STOP_SEC_CONST
/*lint -e537*/
/* 2007-11-26, vismas: do not inform about multiple includes: MemDef.h is intended to be multiply included */
#include "MemDef.h"
/*lint +e537*/

/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 133574485
      #error "The magic number of the generated file <C:\Synergy\GM_C1XX_EPS_TMS570-dzxvzg\GM_C1XX_EPS_TMS570\SwProject\Source\_GenData\gmlcal.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 133574485
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __GMLCAL_H__ */
