/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with
 * message 0883 below. Anyhow, there is a double include prevention and therefore,
 * the message is considered to be wrong. */
/* double include preventer */
#ifndef _TRUSTCFT_H      /* PRQA S 0883 EOF */ /* see MISRA comment above */
#define _TRUSTCFT_H
/* file: trustfct.h, automatically generated by genTMS570SafeCtxAS.exe, Version: 5.07 */
/* configuration read from: C:\Users\cz8l9t\AppData\Local\Temp\~cfg4_314_EPS.ecuc.arxml.oil */
/* generation at  : Wed May 18 15:08:50 2016 */
/* Unlimited license CBD1010124 for Nxtr Automotive */
/* Implementation: TMS570LS3x */
/* Version of general code: 5.23c */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 7
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#ifndef _OS_TRUSTFCT_H_
#define _OS_TRUSTFCT_H_

/* Trusted Functions */

#define NtWrapS_NvMProxy_Init 0
void TRUSTED_NtWrapS_NvMProxy_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Appdesc_BLTransition 1
void TRUSTED_TWrapS_Appdesc_BLTransition(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_PwmCdd_Init 2
void TRUSTED_NtWrapS_PwmCdd_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Adc2_Init1 3
void TRUSTED_NtWrapS_Adc2_Init1(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Wdg_TMS570LS3x_Init 4
void TRUSTED_NtWrapS_Wdg_TMS570LS3x_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_WdgM_Init 5
void TRUSTED_NtWrapS_WdgM_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Adc_Init 6
void TRUSTED_NtWrapS_Adc_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_XcpWriteAp0 7
void TRUSTED_TWrapS_XcpWriteAp0(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_ProcessF0FF 8
void TRUSTED_NtWrapS_ProcessF0FF(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8* os_arg_t_SrvcData_Cnt_T_u08;
   uint16 os_arg_RequestDataIdx_Cnt_T_u16;
} osTFArgType_NtWrapS_ProcessF0FF;

#define NtWrapS_StaMd_Init1 9
void TRUSTED_NtWrapS_StaMd_Init1(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_FeeIf_Init 10
void TRUSTED_TWrapS_FeeIf_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_MainFunction 11
void TRUSTED_TWrapS_Fee_MainFunction(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_Read 12
void TRUSTED_TWrapS_Fee_Read(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   uint16 os_arg_BlockOffset;
   uint8* os_arg_DataBufferPtr;
   uint16 os_arg_Length;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_Read;

#define TWrapS_Fee_Write 13
void TRUSTED_TWrapS_Fee_Write(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   uint8* os_arg_DataBufferPtr;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_Write;

#define TWrapS_Fee_EraseImmediateBlock 14
void TRUSTED_TWrapS_Fee_EraseImmediateBlock(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_EraseImmediateBlock;

#define TWrapS_Fee_InvalidateBlock 15
void TRUSTED_TWrapS_Fee_InvalidateBlock(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_InvalidateBlock;

#define TWrapS_Fee_Cancel 16
void TRUSTED_TWrapS_Fee_Cancel(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_GetStatus 17
void TRUSTED_TWrapS_Fee_GetStatus(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_result;
} osTFArgType_TWrapS_Fee_GetStatus;

#define TWrapS_Fee_GetJobResult 18
void TRUSTED_TWrapS_Fee_GetJobResult(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_result;
} osTFArgType_TWrapS_Fee_GetJobResult;

#define TWrapS_uDiagVIM_RednRpdShtdn 19
void TRUSTED_TWrapS_uDiagVIM_RednRpdShtdn(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_uDiagECC_RednRpdShtdn 20
void TRUSTED_TWrapS_uDiagECC_RednRpdShtdn(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Dma_InvalidateSlowADCGroup 21
void TRUSTED_TWrapS_Dma_InvalidateSlowADCGroup(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_TI_Fee_SuspendResumeErase 22
void TRUSTED_TWrapS_TI_Fee_SuspendResumeErase(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_arg_Command;
} osTFArgType_TWrapS_TI_Fee_SuspendResumeErase;

#define NtWrapS_StaMd_Init0 23
void TRUSTED_NtWrapS_StaMd_Init0(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);


typedef union
{
   osTFArgType_NtWrapS_ProcessF0FF NtWrapS_ProcessF0FF_args;
   osTFArgType_TWrapS_Fee_Read TWrapS_Fee_Read_args;
   osTFArgType_TWrapS_Fee_Write TWrapS_Fee_Write_args;
   osTFArgType_TWrapS_Fee_EraseImmediateBlock TWrapS_Fee_EraseImmediateBlock_args;
   osTFArgType_TWrapS_Fee_InvalidateBlock TWrapS_Fee_InvalidateBlock_args;
   osTFArgType_TWrapS_Fee_GetStatus TWrapS_Fee_GetStatus_args;
   osTFArgType_TWrapS_Fee_GetJobResult TWrapS_Fee_GetJobResult_args;
   osTFArgType_TWrapS_TI_Fee_SuspendResumeErase TWrapS_TI_Fee_SuspendResumeErase_args;
} TrustedFunctionParameterType;

/* Non-trusted Functions */

#define NtWrapS_AssistLmtFunc_Scom_ManualTrqCmd 0
void NONTRUSTED_NtWrapS_AssistLmtFunc_Scom_ManualTrqCmd(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_SCom_EOLNomMtrParam_Set 1
void NONTRUSTED_NtWrapS_SCom_EOLNomMtrParam_Set(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TrqCmdScl_SCom_Set 2
void NONTRUSTED_NtWrapS_TrqCmdScl_SCom_Set(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Polarity_SCom_SetPolarity 3
void NONTRUSTED_NtWrapS_Polarity_SCom_SetPolarity(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp10 4
void NONTRUSTED_NtWrapS_XcpWriteAp10(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TrqCanc_Scom_SetCogTrqCal 5
void NONTRUSTED_NtWrapS_TrqCanc_Scom_SetCogTrqCal(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_DigColPs_SCom_CustSetTrim 6
void NONTRUSTED_NtWrapS_DigColPs_SCom_CustSetTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_DigColPs_SCom_CustClearTrim 7
void NONTRUSTED_NtWrapS_DigColPs_SCom_CustClearTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_DigColPs_SCom_NxtSetTrim 8
void NONTRUSTED_NtWrapS_DigColPs_SCom_NxtSetTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_DigColPs_SCom_NxtClearTrim 9
void NONTRUSTED_NtWrapS_DigColPs_SCom_NxtClearTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_GenPosTraj_SCom_SetInputParam 10
void NONTRUSTED_NtWrapS_GenPosTraj_SCom_SetInputParam(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TSMit_SCom_GainReset 11
void NONTRUSTED_NtWrapS_TSMit_SCom_GainReset(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_VehDyn_SCom_ForceCenter 12
void NONTRUSTED_NtWrapS_VehDyn_SCom_ForceCenter(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_CmMtrCurr3Phs_SCom_CalGain 13
void NONTRUSTED_NtWrapS_CmMtrCurr3Phs_SCom_CalGain(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_CmMtrCurr3Phs_SCom_CalGainPhs3 14
void NONTRUSTED_NtWrapS_CmMtrCurr3Phs_SCom_CalGainPhs3(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_CmMtrCurr3Phs_SCom_CalOffset3Phs 15
void NONTRUSTED_NtWrapS_CmMtrCurr3Phs_SCom_CalOffset3Phs(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_CmMtrCurr3Phs_SCom_SetMtrCurrCals3Phs 16
void NONTRUSTED_NtWrapS_CmMtrCurr3Phs_SCom_SetMtrCurrCals3Phs(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_MtrPos3SinCos_Scom_WriteEOLMtrCals 17
void NONTRUSTED_NtWrapS_MtrPos3SinCos_Scom_WriteEOLMtrCals(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AnaHwTrq_SCom_WriteT1T2OffsetTrim 18
void NONTRUSTED_NtWrapS_AnaHwTrq_SCom_WriteT1T2OffsetTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrqArbn_SCom_WriteHwTrqArbOffsetTrim 19
void NONTRUSTED_NtWrapS_HwTrqArbn_SCom_WriteHwTrqArbOffsetTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_MotPosnCmp_Scom_MotPosnCmpBackEmfWr 20
void NONTRUSTED_NtWrapS_MotPosnCmp_Scom_MotPosnCmpBackEmfWr(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AnaHwTrq_SCom_ClrAnaHwTrqScaleTrim 21
void NONTRUSTED_NtWrapS_AnaHwTrq_SCom_ClrAnaHwTrqScaleTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AnaHwTrq_SCom_ClrT1T2OffsetTrim 22
void NONTRUSTED_NtWrapS_AnaHwTrq_SCom_ClrT1T2OffsetTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AnaHwTrq_SCom_SetAnaHwTrqScaleTrim 23
void NONTRUSTED_NtWrapS_AnaHwTrq_SCom_SetAnaHwTrqScaleTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AnaHwTrq_SCom_SetT1T2OffsetTrim 24
void NONTRUSTED_NtWrapS_AnaHwTrq_SCom_SetT1T2OffsetTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrqArbn_SCom_SetHwTrqArbOffsetTrim 25
void NONTRUSTED_NtWrapS_HwTrqArbn_SCom_SetHwTrqArbOffsetTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrqArbn_SCom_ClrHwTrqArbOffsetTrim 26
void NONTRUSTED_NtWrapS_HwTrqArbn_SCom_ClrHwTrqArbOffsetTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_MotMeclPosn1_Scom_WriteMotMeclPosn1CoeffTbl 27
void NONTRUSTED_NtWrapS_MotMeclPosn1_Scom_WriteMotMeclPosn1CoeffTbl(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_MotMeclPosn2_Scom_WriteMotMeclPosn2CoeffTbl 28
void NONTRUSTED_NtWrapS_MotMeclPosn2_Scom_WriteMotMeclPosn2CoeffTbl(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TrqOvlSta_SCom_SetGmLoaIgnCntr 29
void NONTRUSTED_NtWrapS_TrqOvlSta_SCom_SetGmLoaIgnCntr(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp8 30
void NONTRUSTED_NtWrapS_XcpWriteAp8(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp9 31
void NONTRUSTED_NtWrapS_XcpWriteAp9(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);



#endif /* _OS_TRUSTFCT_H_  End of File */

/* END OF C:\_synergy\9BXX_CZ8L9T\GM_9BXX_EPS_TMS570\Tools\AsrProject.\..\..\SwProject\Source\GenData\\..\GenDataOs\trustfct.h */

#endif /* _TRUSTCFT_H double include preventer */
